### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  id: NoStartupFormException
  children:
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: NoStartupFormException
  nameWithType: NoStartupFormException
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  type: Class
  summary: "Det här undantaget utlöstes av programmodell Visual Basic när den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm*>egenskapen har inte angetts.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm*>"
  remarks: "Visual Basic programmodell kräver att programmet anger den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A>egenskapen innan du kör den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A>metoden.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A> Om egenskapen inte anges genererar det här undantaget programmodell Visual Basic. Mer information finns i [utöka programmodell Visual Basic](~/add/includes/ajax-current-ext-md.md).      > [!NOTE] > Information om hur du ställer in startformulär med hjälp av den **projekt Designer**, se [appen på sidan, projekt Designer (Visual Basic)](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class NoStartupFormException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initierar en ny instans av den <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> klass."
  remarks: "Visual Basic programmodell kräver att programmet anger den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A>egenskapen innan du kör den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A>metoden.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A> Om egenskapen inte anges genererar det här undantaget programmodell Visual Basic. Mer information finns i [utöka programmodell Visual Basic](~/add/includes/ajax-current-ext-md.md).       I följande tabell visas de inledande egenskapsvärdena för en instans av <xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>.</xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>      |||   |-|-|   | Egenskapen | Värdet |   | <xref:System.Exception.InnerException%2A>| En null-referens (`Nothing` i Visual Basic). |   | <xref:System.Exception.Message%2A>| Felmeddelande lokaliserade strängen. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initierar en ny instans av den <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> klass med ett angivet meddelande."
  remarks: "Innehållet i den `message` parameter är avsedd att tolkas av människor. Anroparen av den här konstruktorn är behövs för att säkerställa att den här strängen lokaliserade för den aktuella systemkulturen.       <xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>ärver från <xref:System.Exception>.</xref:System.Exception></xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException> Den här konstruktorn anger egenskaperna för den <xref:System.Exception>objekt som visas i följande tabell.</xref:System.Exception>      |||   |-|-|   | Egenskapen | Värdet |   | <xref:System.Exception.InnerException%2A>| En null-referens (`Nothing` i Visual Basic) |   | <xref:System.Exception.Message%2A>| Den `message` sträng. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Ett meddelande som beskriver felet."
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initierar en ny instans av den <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> klass med serialiserade data."
  remarks: "Den här konstruktorn anropas under deserialisering till att fylla Undantagsobjektet som överförs via en dataström."
  syntax:
    content: protected NoStartupFormException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Den <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> objekt som innehåller det serialiserade objektdata om undantag som genereras."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Den <xref:System.Runtime.Serialization.StreamingContext>objekt som innehåller detaljerad information om käll- och målservrar.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initierar en ny instans av den <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;> </xref> klass med ett angivet meddelande och en referens till det interna undantaget som är orsaken till det här undantaget."
  remarks: "Innehållet i den `message` parameter är avsedd att tolkas av människor. Anroparen av den här konstruktorn är behövs för att säkerställa att den här strängen lokaliserade för den aktuella systemkulturen.       Ett undantag som utlöses när ett direkt resultat av ett tidigare undantag ska innehålla en referens till det tidigare undantaget i den <xref:System.Exception.InnerException%2A>egenskapen.</xref:System.Exception.InnerException%2A> Den <xref:System.Exception.InnerException%2A>-egenskap returnerar samma värde som överförs till konstruktorn eller en null-referens om den <xref:System.Exception.InnerException%2A>egenskapen tillhandahåller inte värdet i det interna undantaget för konstruktorn.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       I följande tabell visas de inledande egenskapsvärdena för en instans av <xref:System.ApplicationException>.</xref:System.ApplicationException>      |||   |-|-|   | Egenskapen | Värdet |   | <xref:System.Exception.InnerException%2A>| Den `inner` referens. |   | <xref:System.Exception.Message%2A>| Den `message` sträng. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "En <xref:System.String>-objektet som beskriver felet.</xref:System.String>"
    - id: inner
      type: System.Exception
      description: "Den <xref:System.Exception>objekt som är orsaken till det aktuella undantaget.</xref:System.Exception> Om den <xref:System.Exception.InnerException*>parametern är inte en null-referens (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> i Visual Basic), det aktuella undantaget utlöses i ett catch-block som hanterar det interna undantaget.</xref:System.Exception.InnerException*>"
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException
  nameWithType: NoStartupFormException.NoStartupFormException
