### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  id: StartupEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  langs:
  - csharp
  name: StartupEventArgs
  nameWithType: StartupEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  type: Class
  summary: "Tillhandahåller data för den <xref uid=&quot;langword_csharp_My.Application.Startup&quot; name=&quot;My.Application.Startup&quot; href=&quot;&quot;> </xref> händelse."
  remarks: "Den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>händelsen inträffar när programmet startas om programmet innehåller programmodell Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> Mer information finns i [översikt över programmodell Visual Basic](~/add/includes/ajax-current-ext-md.md).       StartupEventArgs innehåller kommandoradsargument för programmet och anger om tillämpningsprogrammet startas ska avbrytas."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class StartupEventArgs : System.ComponentModel.CancelEventArgs
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initierar en ny instans av den <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.StartupEventArgs&quot;> </xref> klass."
  remarks: "Den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>händelsen inträffar när programmet startas om programmet innehåller programmodell Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> Mer information finns i [översikt över programmodell Visual Basic](~/add/includes/ajax-current-ext-md.md).       <xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs>innehåller kommandoradsargument för programmet och anger om tillämpningsprogrammet startas ska avbrytas.</xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs>"
  syntax:
    content: public StartupEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "En &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; objekt som innehåller kommandoradsargument för programmet."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Hämtar kommandoradsargument för programmet."
  remarks: "Den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>händelsen inträffar när programmet startas om programmet innehåller programmodell Visual Basic.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> Mer information finns i [översikt över programmodell Visual Basic](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "En &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; objekt som innehåller kommandoradsargument för programmet."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: StartupEventArgs
  nameWithType: StartupEventArgs.StartupEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
