### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser
  id: WebUser
  children:
  - Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  - Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  langs:
  - csharp
  name: WebUser
  nameWithType: WebUser
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser
  type: Class
  summary: "Tillhandahåller åtkomst till information om den aktuella användaren."
  remarks: "Egenskaper och metoder som exponeras av den `My.User` objektet ger åtkomst till information om den aktuella användaren. Enligt &quot;aktuella användare&quot; skiljer sig något mellan Windows och webbprogram. Den aktuella användaren är den användare som kör programmet i ett Windows-program. Den aktuella användaren är den användare som har åtkomst till programmet i ett webbprogram.       Den `My.User` egenskapen ger också tillgång till den <xref:System.Security.Principal.IPrincipal>för den aktuella användaren.</xref:System.Security.Principal.IPrincipal> En UPN-objektet representerar användarens säkerhetskontext, inklusive användarens identitet och alla roller som användaren tillhör.       För Windows-program, den här egenskapen fungerar på samma sätt som den <xref:System.Threading.Thread.CurrentPrincipal%2A>egenskapen.</xref:System.Threading.Thread.CurrentPrincipal%2A> För webbprogram, den här egenskapen fungerar på samma sätt som den <xref:System.Web.HttpContext.User%2A>egenskap hos det objekt som returneras av den <xref:System.Web.HttpContext.Current%2A>egenskapen.</xref:System.Web.HttpContext.Current%2A> </xref:System.Web.HttpContext.User%2A>      > [!NOTE] > För Windows-program, endast projekt som bygger på den **Windows-program** mall initiera den `My.User` objekt som standard. I alla andra Windows projekttyper, måste du initiera den `My.User` objekt genom att anropa den <xref:Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser%2A>metoden uttryckligen eller genom att tilldela ett värde till <xref:System.Threading.Thread.CurrentPrincipal%2A>.</xref:System.Threading.Thread.CurrentPrincipal%2A> </xref:Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser%2A>      > [!NOTE] > Den `My.User` objekt kan inte rapportera information om den aktuella Windows-användaren när körs under Windows 95 och Windows 98 eftersom dessa operativsystem inte stöder begreppet en inloggad användare. Du måste implementera anpassad autentisering som ska användas i `My.User` objekt på dessa operativsystem..."
  example:
  - "This example checks if the application is using Windows or custom authentication, and uses that information to parse the `My.User.Name` property.  \n  \n [!code-vb[VbVbalrMyUser#3](~/add/codesnippet/visualbasic/VbVbalrMyUser/Class1.vb#3)]"
  syntax:
    content: 'public class WebUser : Microsoft.VisualBasic.ApplicationServices.User'
  inheritance:
  - System.Object
  - Microsoft.VisualBasic.ApplicationServices.User
  implements: []
  inheritedMembers:
  - Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal
  - Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser
  - Microsoft.VisualBasic.ApplicationServices.User.IsAuthenticated
  - Microsoft.VisualBasic.ApplicationServices.User.IsInRole(Microsoft.VisualBasic.ApplicationServices.BuiltInRole)
  - Microsoft.VisualBasic.ApplicationServices.User.IsInRole(System.String)
  - Microsoft.VisualBasic.ApplicationServices.User.Name
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  langs:
  - csharp
  name: WebUser()
  nameWithType: WebUser.WebUser()
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.WebUser()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initierar en ny instans av den <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.WebUser&quot;> </xref> klass."
  remarks: "Egenskaper och metoder som exponeras av den `My.User` objektet ger åtkomst till information om den aktuella användaren."
  syntax:
    content: public WebUser ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  id: InternalPrincipal
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  langs:
  - csharp
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Hämtar eller anger UPN-objekt som representerar den aktuella användaren."
  remarks: "I den <xref:Microsoft.VisualBasic.ApplicationServices.WebUser>objekt den här egenskapen radbryts den <xref:System.Web.HttpContext.User%2A>egenskapen för den <xref:System.Web.HttpContext.Current%2A?displayProperty=fullName>egenskapen.</xref:System.Web.HttpContext.Current%2A?displayProperty=fullName> </xref:System.Web.HttpContext.User%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WebUser>       Mer information finns i <xref:Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal%2A>egenskap.</xref:Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal%2A>"
  syntax:
    content: protected override System.Security.Principal.IPrincipal InternalPrincipal { get; set; }
    return:
      type: System.Security.Principal.IPrincipal
      description: "Ett <xref:System.Security.Principal.IPrincipal>-objekt som representerar den aktuella användaren.</xref:System.Security.Principal.IPrincipal>"
  overload: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal*
  exceptions: []
  platform:
  - net462
references:
- uid: Microsoft.VisualBasic.ApplicationServices.User
  isExternal: false
  name: Microsoft.VisualBasic.ApplicationServices.User
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: WebUser()
  nameWithType: WebUser.WebUser()
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.WebUser()
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
- uid: System.Security.Principal.IPrincipal
  parent: System.Security.Principal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: System.Security.Principal.IPrincipal
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: WebUser
  nameWithType: WebUser.WebUser
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal*
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
