### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings
  id: VisualBasicSettings
  children:
  - Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor
  - Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  - Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  langs:
  - csharp
  name: VisualBasicSettings
  nameWithType: VisualBasicSettings
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings
  type: Class
  summary: "Innehåller inställningar som &lt;xref:Microsoft.VisualBasic.Activities.VisualBasicValue%601&gt; och &lt;xref:Microsoft.VisualBasic.Activities.VisualBasicReference%601&gt; förekomster för att kompilera källtext av uttryck som de innehåller."
  remarks: "Inställningarna omfattar sammansättningsreferenser och importerade namnområden som krävs för att kompilera ett uttryck."
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter))]

      [System.Windows.Markup.ValueSerializer(typeof(Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer))]

      public class VisualBasicSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  langs:
  - csharp
  name: VisualBasicSettings()
  nameWithType: VisualBasicSettings.VisualBasicSettings()
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.VisualBasicSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities
  summary: "Initierar en ny instans av den <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> klass."
  syntax:
    content: public VisualBasicSettings ();
    parameters: []
  overload: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  id: Default
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  langs:
  - csharp
  name: Default
  nameWithType: VisualBasicSettings.Default
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  type: Property
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities
  summary: "Hämtar en <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> som innehåller en standarduppsättning av sammansättningsreferenser och importerade namnområden. Den här uppsättningen är tillgänglig för alla &lt;xref:Microsoft.VisualBasic.Activities.VisualBasicValue%601&gt; och &lt;xref:Microsoft.VisualBasic.Activities.VisualBasicReference%601&gt; instanser i en viss <xref href=&quot;System.AppDomain&quot;> </xref>."
  remarks: "I följande tabell visas standard importerade namnområden och sammansättningen refererar till.      | Importera Namespace | Sammansättningen |   |------------------------|--------------|   | System | mscorlib |   | System | System |   | System.Collections|mscorlib|   | System.Collections.Generic|mscorlib|   | System.Collections.Generic| System |   | System.Activities| System.Activities|   | System.Activities.Statements| System.Activities|   | System.Activities.Expressions| System.Activities|"
  syntax:
    content: public static Microsoft.VisualBasic.Activities.VisualBasicSettings Default { get; }
    return:
      type: Microsoft.VisualBasic.Activities.VisualBasicSettings
      description: "En <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> som innehåller en standarduppsättning av sammansättningsreferenser och importerade namnområden."
  overload: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  id: ImportReferences
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  langs:
  - csharp
  name: ImportReferences
  nameWithType: VisualBasicSettings.ImportReferences
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  type: Property
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities
  summary: "Hämtar en samling <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicImportReference&quot;> </xref> objekt, som representerar en sammansättningsreferens och ett namnområde som importerats från sammansättningen."
  syntax:
    content: public System.Collections.Generic.ISet<Microsoft.VisualBasic.Activities.VisualBasicImportReference> ImportReferences { get; }
    return:
      type: System.Collections.Generic.ISet{Microsoft.VisualBasic.Activities.VisualBasicImportReference}
      description: "En samling <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicImportReference&quot;> </xref> objekt, som representerar en sammansättningsreferens och ett namnområde som importerats från sammansättningen."
  overload: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: VisualBasicSettings()
  nameWithType: VisualBasicSettings.VisualBasicSettings()
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.VisualBasicSettings()
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: Default
  nameWithType: VisualBasicSettings.Default
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings
  parent: Microsoft.VisualBasic.Activities
  isExternal: false
  name: VisualBasicSettings
  nameWithType: VisualBasicSettings
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: ImportReferences
  nameWithType: VisualBasicSettings.ImportReferences
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
- uid: System.Collections.Generic.ISet{Microsoft.VisualBasic.Activities.VisualBasicImportReference}
  parent: System.Collections.Generic
  isExternal: true
  name: ISet<VisualBasicImportReference>
  nameWithType: ISet<VisualBasicImportReference>
  fullName: System.Collections.Generic.ISet<Microsoft.VisualBasic.Activities.VisualBasicImportReference>
  spec.csharp:
  - uid: System.Collections.Generic.ISet`1
    name: ISet
    nameWithType: ISet
    fullName: ISet<Microsoft.VisualBasic.Activities.VisualBasicImportReference>
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.VisualBasic.Activities.VisualBasicImportReference
    name: VisualBasicImportReference
    nameWithType: VisualBasicImportReference
    fullName: VisualBasicImportReference
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor*
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: VisualBasicSettings
  nameWithType: VisualBasicSettings.VisualBasicSettings
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default*
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: Default
  nameWithType: VisualBasicSettings.Default
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences*
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: ImportReferences
  nameWithType: VisualBasicSettings.ImportReferences
