### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings
  id: ProjectLoadSettings
  children:
  - Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  - Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  - Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  - Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  langs:
  - csharp
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings
  type: Enum
  summary: "Flaggorna för att styra inläsningen av projektet."
  remarks: "Det här är en &quot;flaggor&quot; uppräkning, att tillåta att framtida inställningar läggs till i ett additiva, inte bryta sätt."
  syntax:
    content: >-
      [System.Flags]

      public enum ProjectLoadSettings
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  id: Default
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  name: Default
  nameWithType: ProjectLoadSettings.Default
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  summary: "Normal belastning. Detta är standardinställningen."
  syntax:
    content: Default
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  id: IgnoreMissingImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  summary: "Ignorera inte existerar mål filer vid utvärdering av projektet."
  syntax:
    content: IgnoreMissingImports
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  id: RecordDuplicateButNotCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  name: RecordDuplicateButNotCircularImports
  nameWithType: ProjectLoadSettings.RecordDuplicateButNotCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  summary: "Visar att importen inklusive dubbla, men inte cirkulär import på den `ImportsIncludingDuplicates` egenskapen ska registreras"
  syntax:
    content: RecordDuplicateButNotCircularImports
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  id: RejectCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  name: RejectCircularImports
  nameWithType: ProjectLoadSettings.RejectCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  summary: "Anger att ett undantag om någon cirkulär import identifieras"
  syntax:
    content: RejectCircularImports
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: Default
  nameWithType: ProjectLoadSettings.Default
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings
  parent: Microsoft.Build.Evaluation
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: RecordDuplicateButNotCircularImports
  nameWithType: ProjectLoadSettings.RecordDuplicateButNotCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: RejectCircularImports
  nameWithType: ProjectLoadSettings.RejectCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
