### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost
  id: IInternalConfigWebHost
  children:
  - System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  - System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  langs:
  - csharp
  name: IInternalConfigWebHost
  nameWithType: IInternalConfigWebHost
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost
  type: Interface
  summary: "Definierar gränssnitt som används av internt .NET Framework-infrastrukturen för att komma åt och ändra värden konfigurationsfiler."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigWebHost
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  id: GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  langs:
  - csharp
  name: GetConfigPathFromSiteIDAndVPath(String,String)
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration.Internal
  summary: "Returnerar ett värde som representerar sökvägen till en konfigurationsfil som är associerade med den angivna webbplatsidentifieraren och programmets virtuella sökväg."
  syntax:
    content: public string GetConfigPathFromSiteIDAndVPath (string siteID, string vpath);
    parameters:
    - id: siteID
      type: System.String
      description: "Programmets identifierare för webbplatsen. Mer information finns i översikt över ASP.NET-konfiguration."
    - id: vpath
      type: System.String
      description: "Programmets virtuella sökväg som en sträng. Mer information finns i sökvägarna för ASP.NET-webbplats."
    return:
      type: System.String
      description: "En sträng som representerar sökvägen till en konfigurationsfil."
  overload: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  id: GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  langs:
  - csharp
  name: GetSiteIDAndVPathFromConfigPath(String,String,String)
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration.Internal
  summary: "Anger aktuella plats-ID för ett konfigurationsobjekt baserat på den virtuella sökvägen och sökvägen till programmet konfiguration."
  syntax:
    content: public void GetSiteIDAndVPathFromConfigPath (string configPath, out string siteID, out string vpath);
    parameters:
    - id: configPath
      type: System.String
      description: "En sträng som representerar sökvägen till programmets konfigurationsfil."
    - id: siteID
      type: System.String
      description: "Programmets plats identifierare. Mer information finns i översikt över ASP.NET-konfiguration."
    - id: vpath
      type: System.String
      description: "Programmets virtuella sökväg som en sträng. Mer information finns i sökvägarna för ASP.NET-webbplats."
  overload: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetConfigPathFromSiteIDAndVPath(String,String)
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetSiteIDAndVPathFromConfigPath(String,String,String)
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath*
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetConfigPathFromSiteIDAndVPath
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath*
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetSiteIDAndVPathFromConfigPath
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath
