### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  id: X509InitiatorCertificateServiceElement
  children:
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement)
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
  langs:
  - csharp
  name: X509InitiatorCertificateServiceElement
  nameWithType: X509InitiatorCertificateServiceElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  type: Class
  summary: "Representera en konfigurationselement som anger avsändarens krav för ett X.509-certifikat som används av mottagaren när du svarar på avsändaren. Den här klassen kan inte ärvas."
  syntax:
    content: 'public sealed class X509InitiatorCertificateServiceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: X509InitiatorCertificateServiceElement()
  nameWithType: X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement&quot;> </xref> klass."
  syntax:
    content: public X509InitiatorCertificateServiceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
  id: Authentication
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: Authentication
  nameWithType: X509InitiatorCertificateServiceElement.Authentication
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar klientcertifikatet används för autentisering."
  syntax:
    content: public System.ServiceModel.Configuration.X509ClientCertificateAuthenticationElement Authentication { get; }
    return:
      type: System.ServiceModel.Configuration.X509ClientCertificateAuthenticationElement
      description: "En <xref href=&quot;System.ServiceModel.Security.X509ClientCertificateAuthentication&quot;> </xref> som innehåller klientcertifikatet används för autentisering."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
  id: Certificate
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: Certificate
  nameWithType: X509InitiatorCertificateServiceElement.Certificate
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar det certifikat som används för att representera tjänsten när de kommunicerar tillbaka till klienten."
  syntax:
    content: public System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement Certificate { get; }
    return:
      type: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
      description: "En <xref href=&quot;System.Security.Cryptography.X509Certificates.X509Certificate2&quot;> </xref> som används för att representera tjänsten när de kommunicerar tillbaka till klienten."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement)
  id: Copy(System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: Copy(X509InitiatorCertificateServiceElement)
  nameWithType: X509InitiatorCertificateServiceElement.Copy(X509InitiatorCertificateServiceElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(X509InitiatorCertificateServiceElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Kopierar innehållet i det angivna konfigurationselementet till den här konfigurationselementet."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
      description: "Konfigurationselementet som ska kopieras."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Konfigurationsfilen är skrivskyddad."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509InitiatorCertificateServiceElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: X509InitiatorCertificateServiceElement()
  nameWithType: X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement()
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Authentication
  nameWithType: X509InitiatorCertificateServiceElement.Authentication
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
- uid: System.ServiceModel.Configuration.X509ClientCertificateAuthenticationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509ClientCertificateAuthenticationElement
  nameWithType: X509ClientCertificateAuthenticationElement
  fullName: System.ServiceModel.Configuration.X509ClientCertificateAuthenticationElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Certificate
  nameWithType: X509InitiatorCertificateServiceElement.Certificate
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509ClientCertificateCredentialsElement
  nameWithType: X509ClientCertificateCredentialsElement
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Copy(X509InitiatorCertificateServiceElement)
  nameWithType: X509InitiatorCertificateServiceElement.Copy(X509InitiatorCertificateServiceElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(X509InitiatorCertificateServiceElement)
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509InitiatorCertificateServiceElement
  nameWithType: X509InitiatorCertificateServiceElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateServiceElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: X509InitiatorCertificateServiceElement
  nameWithType: X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Authentication
  nameWithType: X509InitiatorCertificateServiceElement.Authentication
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Certificate
  nameWithType: X509InitiatorCertificateServiceElement.Certificate
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Copy
  nameWithType: X509InitiatorCertificateServiceElement.Copy
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateServiceElement.Properties
