### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceActivationElement
  id: ServiceActivationElement
  children:
  - System.ServiceModel.Configuration.ServiceActivationElement.#ctor
  - System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String)
  - System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String,System.String)
  - System.ServiceModel.Configuration.ServiceActivationElement.Factory
  - System.ServiceModel.Configuration.ServiceActivationElement.Properties
  - System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
  - System.ServiceModel.Configuration.ServiceActivationElement.Service
  langs:
  - csharp
  name: ServiceActivationElement
  nameWithType: ServiceActivationElement
  fullName: System.ServiceModel.Configuration.ServiceActivationElement
  type: Class
  summary: "Hanterar configuration elementinnehåll i samband med aktivering av ett tjänstprogram."
  syntax:
    content: 'public sealed class ServiceActivationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: ServiceActivationElement()
  nameWithType: ServiceActivationElement.ServiceActivationElement()
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Skapar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.ServiceActivationElement&quot;> </xref> klass."
  syntax:
    content: public ServiceActivationElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: ServiceActivationElement(String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Konfigurerar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.ServiceActivationElement&quot;> </xref> klass som innehåller en service aktivering directory plats som är i förhållande till en bas-URL."
  syntax:
    content: public ServiceActivationElement (string relativeAddress);
    parameters:
    - id: relativeAddress
      type: System.String
      description: "En plats för katalogen som kräver refereras från en bas-URL."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: ServiceActivationElement(String,String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String,String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Konfigurerar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.ServiceActivationElement&quot;> </xref> klass som innehåller den angivna tjänsten som ska aktiveras och dess relativ adress."
  syntax:
    content: public ServiceActivationElement (string relativeAddress, string service);
    parameters:
    - id: relativeAddress
      type: System.String
      description: "En URL-plats som kräver refereras från en basadress."
    - id: service
      type: System.String
      description: "Tjänstprogrammet som blir aktiverades."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: ServiceActivationElement(String,String,String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String,String,String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String,String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Konfigurerar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.ServiceActivationElement&quot;> </xref> klass med den angivna tjänsten som ska aktiveras och dess relativ adress system sökväg för en fabrik som genererar ett element för aktivering av tjänsten."
  syntax:
    content: public ServiceActivationElement (string relativeAddress, string service, string factory);
    parameters:
    - id: relativeAddress
      type: System.String
      description: "En URL-plats som kräver att referera från en basadress."
    - id: service
      type: System.String
      description: "Tjänstprogrammet som aktiveras."
    - id: factory
      type: System.String
      description: "CLR-typnamn för fabriken som genererar ett element för aktivering av tjänsten."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Factory
  id: Factory
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: Factory
  nameWithType: ServiceActivationElement.Factory
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Factory
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger en sträng som innehåller CLR-typnamn för fabriken som genererar ett element för aktivering av service configuration."
  syntax:
    content: public string Factory { get; set; }
    return:
      type: System.String
      description: "Den configuration-sträng som innehåller CLR-typnamn för fabriken."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.Factory*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: Properties
  nameWithType: ServiceActivationElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
  id: RelativeAddress
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: RelativeAddress
  nameWithType: ServiceActivationElement.RelativeAddress
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger den relativa adressen på en fil för aktivering av service."
  syntax:
    content: public string RelativeAddress { get; set; }
    return:
      type: System.String
      description: "Den relativa adressen för en fil för aktivering av tjänsten."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Service
  id: Service
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  langs:
  - csharp
  name: Service
  nameWithType: ServiceActivationElement.Service
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Service
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger namnet på tjänstprogrammet."
  syntax:
    content: public string Service { get; set; }
    return:
      type: System.String
      description: "Namnet på ett tjänstprogram."
  overload: System.ServiceModel.Configuration.ServiceActivationElement.Service*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement()
  nameWithType: ServiceActivationElement.ServiceActivationElement()
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement()
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement(String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String)
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement(String,String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String,String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String,String)
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor(System.String,System.String,System.String)
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement(String,String,String)
  nameWithType: ServiceActivationElement.ServiceActivationElement(String,String,String)
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.ServiceActivationElement(String,String,String)
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Factory
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Factory
  nameWithType: ServiceActivationElement.Factory
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Factory
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Properties
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Properties
  nameWithType: ServiceActivationElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: RelativeAddress
  nameWithType: ServiceActivationElement.RelativeAddress
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Service
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Service
  nameWithType: ServiceActivationElement.Service
  fullName: System.ServiceModel.Configuration.ServiceActivationElement.Service
- uid: System.ServiceModel.Configuration.ServiceActivationElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: ServiceActivationElement
  nameWithType: ServiceActivationElement.ServiceActivationElement
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Factory*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Factory
  nameWithType: ServiceActivationElement.Factory
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Properties*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Properties
  nameWithType: ServiceActivationElement.Properties
- uid: System.ServiceModel.Configuration.ServiceActivationElement.RelativeAddress*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: RelativeAddress
  nameWithType: ServiceActivationElement.RelativeAddress
- uid: System.ServiceModel.Configuration.ServiceActivationElement.Service*
  parent: System.ServiceModel.Configuration.ServiceActivationElement
  isExternal: false
  name: Service
  nameWithType: ServiceActivationElement.Service
