### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSettingAttribute
  id: SpecialSettingAttribute
  children:
  - System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  - System.Configuration.SpecialSettingAttribute.SpecialSetting
  langs:
  - csharp
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute
  fullName: System.Configuration.SpecialSettingAttribute
  type: Class
  summary: "Anger att ett program inställningsegenskapen har en särskild betydelse. Den här klassen kan inte ärvas."
  remarks: "Vissa egenskaper för inställningar av programmet har en särskild betydelse som ändrar det sätt som deras associerade inställningarna providern ska behandla dem. SpecialSettingAttribute används för att identifiera sådana egenskaper. Den här klassen använder den <xref:System.Configuration.SpecialSetting?displayProperty=fullName>uppräkningen för att ange vilka särskild kategori egenskapen tillhör.</xref:System.Configuration.SpecialSetting?displayProperty=fullName>       SpecialSettingAttribute kan endast tillämpas inställningarna klassen eller egenskapen individuella inställningar.       Ett exempel på hur en inställningsprovidern behandlar SpecialSettingAttribute, finns i <xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>metoden i <xref:System.Configuration.LocalFileSettingsProvider>klassen.</xref:System.Configuration.LocalFileSettingsProvider> </xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SpecialSettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  id: '#ctor(System.Configuration.SpecialSetting)'
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.SpecialSettingAttribute&quot;> </xref> klass."
  syntax:
    content: public SpecialSettingAttribute (System.Configuration.SpecialSetting specialSetting);
    parameters:
    - id: specialSetting
      type: System.Configuration.SpecialSetting
      description: "En <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> uppräkningsvärdet definierar kategorin inställningsegenskapen program."
  overload: System.Configuration.SpecialSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  id: SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar värdet som beskriver kategorin särskild inställning av egenskapen programmet inställningar."
  remarks: "Egenskapen SpecialSetting anges i <xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>konstruktören för den här klassen.</xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SpecialSetting SpecialSetting { get; }
    return:
      type: System.Configuration.SpecialSetting
      description: "En <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> uppräkningsvärdet definierar kategorin inställningsegenskapen program."
  overload: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.#ctor*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
