### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSavingEventHandler
  id: SettingsSavingEventHandler
  langs:
  - csharp
  name: SettingsSavingEventHandler
  nameWithType: SettingsSavingEventHandler
  fullName: System.Configuration.SettingsSavingEventHandler
  type: Delegate
  summary: "Representerar den metod som hanterar den <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsSaving&quot;> </xref> händelse."
  remarks: "<xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>Händelsen inträffar precis innan en grupp av program inställningarna bevaras, vanligtvis under körningen av <xref:System.Configuration.ApplicationSettingsBase.Save%2A>-metoden i en wrapper-klass som härleds från <xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase> </xref:System.Configuration.ApplicationSettingsBase.Save%2A> </xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>"
  syntax:
    content: public delegate void SettingsSavingEventHandler(object sender, CancelEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
