### YamlMime:ManagedReference
items:
- uid: System.Configuration.IgnoreSectionHandler
  id: IgnoreSectionHandler
  children:
  - System.Configuration.IgnoreSectionHandler.#ctor
  - System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler
  fullName: System.Configuration.IgnoreSectionHandler
  type: Class
  summary: "Innehåller en definition av äldre avsnittshanteraren för konfigurationsavsnitt som inte hanteras av den <xref href=&quot;System.Configuration&quot;> </xref> typer."
  remarks: "Konfigurationssystemet helt Parsar konfigurationsfiler för att samla in information om konfiguration och utlöser undantag när den stöter på konfigurationsavsnitt som saknar motsvarande post i den `configSections` avsnitt.       För dessa avsnitt som inte hanteras av den <xref:System.Configuration>typer, den nya adapterprogramstypen <xref:System.Configuration.IgnoreSection>tillhandahålls.</xref:System.Configuration.IgnoreSection> </xref:System.Configuration> Detta är att förhindra att konfigurationsfilen tolkning undantag.       IgnoreSectionHandler finns också för äldre ändamål."
  syntax:
    content: 'public class IgnoreSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.IgnoreSectionHandler&quot;> </xref> klass."
  syntax:
    content: public IgnoreSectionHandler ();
    parameters: []
  overload: System.Configuration.IgnoreSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Skapar en ny konfiguration hanterare och lägger till angivna konfigurationsobjektet avsnittshanteraren samlingen."
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Konfigurationsinställningarna i en motsvarande överordnade konfigurationsavsnittet."
    - id: configContext
      type: System.Object
      description: "Den virtuella sökvägen som beräknar avsnittshanteraren konfigurationsvärden. Normalt den här parametern är reserverat och kan <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
    - id: section
      type: System.Xml.XmlNode
      description: "En <xref href=&quot;System.Xml.XmlNode&quot;> </xref> som innehåller konfigurationsinformationen som ska hanteras. Ger direktåtkomst till XML-innehållet i konfigurationsavsnittet."
    return:
      type: System.Object
      description: "Skapade hanterare konfigurationsobjektet."
  overload: System.Configuration.IgnoreSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.IgnoreSectionHandler.#ctor*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler
- uid: System.Configuration.IgnoreSectionHandler.Create*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create
  nameWithType: IgnoreSectionHandler.Create
