### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  id: ServiceModelExtensionElement
  children:
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  langs:
  - csharp
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
  type: Class
  summary: "En abstrakt basklass för konfigurationselement som innehåller en dynamisk samling heterogena underordnade element."
  syntax:
    content: 'public abstract class ServiceModelExtensionElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: ServiceModelExtensionElement()
  nameWithType: ServiceModelExtensionElement.ServiceModelExtensionElement()
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.ServiceModelExtensionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.ServiceModelExtensionElement&quot;> </xref> klass."
  syntax:
    content: protected ServiceModelExtensionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  id: ConfigurationElementName
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: ConfigurationElementName
  nameWithType: ServiceModelExtensionElement.ConfigurationElementName
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar namnet på den här konfigurationselementet."
  syntax:
    content: public string ConfigurationElementName { get; }
    return:
      type: System.String
      description: "Det unika namnet för den här konfigurationselementet."
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Tilläggssamlingen konfigurationen finns inte."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ServiceModelExtensionElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Kopierar innehållet i det angivna konfigurationselementet till den här konfigurationselementet."
  syntax:
    content: public virtual void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "Konfigurationselementet som ska kopieras."
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Konfigurationsfilen är skrivskyddad."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  id: IsModified
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: IsModified()
  nameWithType: ServiceModelExtensionElement.IsModified()
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar ett värde som anger om den här konfigurationselementet har ändrats."
  syntax:
    content: protected override bool IsModified ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den här konfigurationselementet har ändrats; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: ServiceModelExtensionElement.Reset(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Återställer det interna tillståndet för det här elementet konfigurationsobjekt, inklusive Lås och egenskaper för samlingar."
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "Den överordnade noden för det här konfigurationselementet."
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  id: SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: ServiceModelExtensionElement.SerializeElement(XmlWriter,Boolean)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(XmlWriter,Boolean)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Skriver innehållet i den här konfigurationselementet i konfigurationsfilen."
  syntax:
    content: protected override bool SerializeElement (System.Xml.XmlWriter writer, bool serializeCollectionKey);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: "Den <xref:System.Xml.XmlWriter>som används för att skriva i konfigurationsfilen.</xref:System.Xml.XmlWriter>"
    - id: serializeCollectionKey
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>att serialisera endast samling nyckelegenskaper; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om några data serialiserades faktiskt; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: ServiceModelExtensionElement()
  nameWithType: ServiceModelExtensionElement.ServiceModelExtensionElement()
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.ServiceModelExtensionElement()
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: ConfigurationElementName
  nameWithType: ServiceModelExtensionElement.ConfigurationElementName
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ServiceModelExtensionElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: IsModified()
  nameWithType: ServiceModelExtensionElement.IsModified()
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: ServiceModelExtensionElement.Reset(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(ConfigurationElement)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: ServiceModelExtensionElement.SerializeElement(XmlWriter,Boolean)
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(XmlWriter,Boolean)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: ConfigurationElementName
  nameWithType: ServiceModelExtensionElement.ConfigurationElementName
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: CopyFrom
  nameWithType: ServiceModelExtensionElement.CopyFrom
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: IsModified
  nameWithType: ServiceModelExtensionElement.IsModified
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: Reset
  nameWithType: ServiceModelExtensionElement.Reset
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement*
  parent: System.ServiceModel.Configuration.ServiceModelExtensionElement
  isExternal: false
  name: SerializeElement
  nameWithType: ServiceModelExtensionElement.SerializeElement
