### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.NetNamedPipeSecurity
  id: NetNamedPipeSecurity
  children:
  - System.ServiceModel.NetNamedPipeSecurity.#ctor
  - System.ServiceModel.NetNamedPipeSecurity.Mode
  - System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport
  - System.ServiceModel.NetNamedPipeSecurity.Transport
  langs:
  - csharp
  name: NetNamedPipeSecurity
  nameWithType: NetNamedPipeSecurity
  fullName: System.ServiceModel.NetNamedPipeSecurity
  type: Class
  summary: "Tillhandahåller åtkomst till säkerhetsinställningarna för slutpunkter som konfigurerats med bindningen namngiven pipe."
  remarks: ''
  example:
  - "The following code shows how to add a NetNamedPipeSecurity object to a <xref:System.ServiceModel.NetNamedPipeBinding> instance.  \n  \n [!code-cs[S_UENetNamedPipeSecurity#1](~/add/codesnippet/csharp/t-system.servicemodel.ne_2_1.cs)]"
  syntax:
    content: public sealed class NetNamedPipeSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: NetNamedPipeSecurity()
  nameWithType: NetNamedPipeSecurity.NetNamedPipeSecurity()
  fullName: System.ServiceModel.NetNamedPipeSecurity.NetNamedPipeSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.NetNamedPipeSecurity&quot;> </xref> klass."
  syntax:
    content: public NetNamedPipeSecurity ();
    parameters: []
  overload: System.ServiceModel.NetNamedPipeSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.Mode
  id: Mode
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: NetNamedPipeSecurity.Mode
  fullName: System.ServiceModel.NetNamedPipeSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Hämtar eller anger säkerhetsläget för namngiven pipe-bindning."
  remarks: "Giltiga värden för den här egenskapen är: - Transport - användningen baserat på transport säkerhet. Standardinställningen använder NTLM som inte ger serverautentisering.      -Ingen - Använd ingen säkerhet."
  example:
  - "The following code shows how to set the Mode property:  \n  \n [!code-cs[S_UENetNamedPipeSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ne_3_1.cs)]"
  syntax:
    content: public System.ServiceModel.NetNamedPipeSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetNamedPipeSecurityMode
      description: "Värdet för den <xref href=&quot;System.ServiceModel.NetNamedPipeSecurityMode&quot;> </xref> för namngiven pipe-bindning. Standardvärdet är <xref href=&quot;System.ServiceModel.NetNamedPipeSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.NetNamedPipeSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: NetNamedPipeSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Returnerar en ett värde som anger om den <xref:System.ServiceModel.NetNamedPipeSecurity.Transport*>egenskap har ändrats från sitt standardvärde och ska serialiseras.</xref:System.ServiceModel.NetNamedPipeSecurity.Transport*> Detta används av WCF för XAML-integrering."
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <xref:System.ServiceModel.NetNamedPipeSecurity.Transport*>egenskapsvärdet måste vara serialiserade, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.NetNamedPipeSecurity.Transport*>"
  overload: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.Transport
  id: Transport
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: NetNamedPipeSecurity.Transport
  fullName: System.ServiceModel.NetNamedPipeSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Hämtar transportsäkerhet för namngiven pipe-bindning."
  remarks: "Den här metoden ger tillgång till <xref:System.Net.Security.ProtectionLevel>för namngiven pipe-transport via <xref:System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel%2A>.</xref:System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel%2A> </xref:System.Net.Security.ProtectionLevel>"
  example:
  - "The following code shows how to access the Transport property:  \n  \n [!code-cs[S_UENetNamedPipeSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ne_21_1.cs)]"
  syntax:
    content: public System.ServiceModel.NamedPipeTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.NamedPipeTransportSecurity
      description: "Värdet för den <xref href=&quot;System.ServiceModel.NamedPipeTransportSecurity&quot;> </xref> för namngiven pipe-bindning."
  overload: System.ServiceModel.NetNamedPipeSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.NetNamedPipeSecurity.#ctor
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: NetNamedPipeSecurity()
  nameWithType: NetNamedPipeSecurity.NetNamedPipeSecurity()
  fullName: System.ServiceModel.NetNamedPipeSecurity.NetNamedPipeSecurity()
- uid: System.ServiceModel.NetNamedPipeSecurity.Mode
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurity.Mode
  fullName: System.ServiceModel.NetNamedPipeSecurity.Mode
- uid: System.ServiceModel.NetNamedPipeSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetNamedPipeSecurityMode
  nameWithType: NetNamedPipeSecurityMode
  fullName: System.ServiceModel.NetNamedPipeSecurityMode
- uid: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: NetNamedPipeSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.NetNamedPipeSecurity.Transport
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurity.Transport
  fullName: System.ServiceModel.NetNamedPipeSecurity.Transport
- uid: System.ServiceModel.NamedPipeTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: NamedPipeTransportSecurity
  nameWithType: NamedPipeTransportSecurity
  fullName: System.ServiceModel.NamedPipeTransportSecurity
- uid: System.ServiceModel.NetNamedPipeSecurity.#ctor*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: NetNamedPipeSecurity
  nameWithType: NetNamedPipeSecurity.NetNamedPipeSecurity
- uid: System.ServiceModel.NetNamedPipeSecurity.Mode*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurity.Mode
- uid: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: NetNamedPipeSecurity.ShouldSerializeTransport
- uid: System.ServiceModel.NetNamedPipeSecurity.Transport*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurity.Transport
