### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallEventHandler
  id: InstallEventHandler
  langs:
  - csharp
  name: InstallEventHandler
  nameWithType: InstallEventHandler
  fullName: System.Configuration.Install.InstallEventHandler
  type: Delegate
  summary: "Represents the method that will handle the <xref href=&quot;System.Configuration.Install.Installer.BeforeInstall&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.AfterInstall&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.Committing&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.Committed&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.BeforeRollback&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.AfterRollback&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.BeforeUninstall&quot;></xref>, or <xref href=&quot;System.Configuration.Install.Installer.AfterUninstall&quot;></xref> event of an <xref href=&quot;System.Configuration.Install.Installer&quot;></xref>."
  remarks: "När du skapar en InstallEventHandler delegat kan identifiera den metod som hanterar händelsen. Lägga till en instans av delegaten händelsen om du vill associera händelsen med din händelsehanterare. Händelsehanteraren anropas när händelsen inträffar, om du tar bort delegaten. Mer information om händelsehanterare delegater finns [händelser](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public delegate void InstallEventHandler(object sender, InstallEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
