### YamlMime:ManagedReference
items:
- uid: System.Configuration.SubclassTypeValidator
  id: SubclassTypeValidator
  children:
  - System.Configuration.SubclassTypeValidator.#ctor(System.Type)
  - System.Configuration.SubclassTypeValidator.CanValidate(System.Type)
  - System.Configuration.SubclassTypeValidator.Validate(System.Object)
  langs:
  - csharp
  name: SubclassTypeValidator
  nameWithType: SubclassTypeValidator
  fullName: System.Configuration.SubclassTypeValidator
  type: Class
  summary: "Verifierar att en härledd klass för en viss typ av ett objekt."
  remarks: "Klassen SubclassTypeValidator används för att säkerställa att ett objekt som uppfyller särskilda kriterier. Kriterierna för verifiering upprättas när en instans av klassen SubclassTypeValidator skapas.       <xref:System.Configuration.SubclassTypeValidator.CanValidate%2A>Metoden avgör om typ av objekt som verifieras i själva verket är en <xref:System.Type>.</xref:System.Type> </xref:System.Configuration.SubclassTypeValidator.CanValidate%2A> Det objekt som verifieras skickas som en parameter för den <xref:System.Configuration.SubclassTypeValidator.Validate%2A>metoden.</xref:System.Configuration.SubclassTypeValidator.Validate%2A> Den här metoden först verifierar att objektet som inte är `null`, och verifierar sedan att objektet är en härledd klass av den förväntade typen."
  syntax:
    content: 'public sealed class SubclassTypeValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidator.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SubclassTypeValidator
  langs:
  - csharp
  name: SubclassTypeValidator(Type)
  nameWithType: SubclassTypeValidator.SubclassTypeValidator(Type)
  fullName: System.Configuration.SubclassTypeValidator.SubclassTypeValidator(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.SubclassTypeValidator&quot;> </xref> klass."
  remarks: "Kriterierna för verifiering är baserad på den `baseClass` parameter."
  syntax:
    content: public SubclassTypeValidator (Type baseClass);
    parameters:
    - id: baseClass
      type: System.Type
      description: "Basklass ska valideras mot."
  overload: System.Configuration.SubclassTypeValidator.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>baseClass</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.SubclassTypeValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: SubclassTypeValidator.CanValidate(Type)
  fullName: System.Configuration.SubclassTypeValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Anger om ett objekt kan verifieras baserat på typen."
  remarks: "Metoden CanValidate avgör om typ av objekt som verifieras i själva verket är en <xref:System.Type>.</xref:System.Type>"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Objekttyp."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <code> type </code> parametern matchar en typ som kan vara validerad, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.SubclassTypeValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.SubclassTypeValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: SubclassTypeValidator.Validate(Object)
  fullName: System.Configuration.SubclassTypeValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Anger om värdet för ett objekt är giltig."
  remarks: "När en instans av den <xref:System.Configuration.SubclassTypeValidator>klassen skapas, basklassen tillhandahålls och användas som kriterier.</xref:System.Configuration.SubclassTypeValidator> Objektet som har skickats som en parameter för Validate-metoden. Den här metoden utför verifieringen mellan basklassen och parametern-objektet."
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Värdet för objektet."
  overload: System.Configuration.SubclassTypeValidator.Validate*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>value</code>är inte av en <xref:System.Type> som kan härledas från <code>baseClass</code> som definierats i konstruktorn."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.SubclassTypeValidator.#ctor(System.Type)
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: SubclassTypeValidator(Type)
  nameWithType: SubclassTypeValidator.SubclassTypeValidator(Type)
  fullName: System.Configuration.SubclassTypeValidator.SubclassTypeValidator(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SubclassTypeValidator.CanValidate(System.Type)
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: SubclassTypeValidator.CanValidate(Type)
  fullName: System.Configuration.SubclassTypeValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SubclassTypeValidator.Validate(System.Object)
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: SubclassTypeValidator.Validate(Object)
  fullName: System.Configuration.SubclassTypeValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.SubclassTypeValidator.#ctor*
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: SubclassTypeValidator
  nameWithType: SubclassTypeValidator.SubclassTypeValidator
- uid: System.Configuration.SubclassTypeValidator.CanValidate*
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: CanValidate
  nameWithType: SubclassTypeValidator.CanValidate
- uid: System.Configuration.SubclassTypeValidator.Validate*
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: Validate
  nameWithType: SubclassTypeValidator.Validate
