### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigRecord
  id: IInternalConfigRecord
  children:
  - System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  - System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(System.String)
  - System.Configuration.Internal.IInternalConfigRecord.GetSection(System.String)
  - System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  - System.Configuration.Internal.IInternalConfigRecord.RefreshSection(System.String)
  - System.Configuration.Internal.IInternalConfigRecord.Remove
  - System.Configuration.Internal.IInternalConfigRecord.StreamName
  - System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors
  langs:
  - csharp
  name: IInternalConfigRecord
  nameWithType: IInternalConfigRecord
  fullName: System.Configuration.Internal.IInternalConfigRecord
  type: Interface
  summary: "Definierar gränssnitt som används av interna .NET-strukturer som stöder skapandet av nya configuration-poster."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigRecord
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  id: ConfigPath
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: ConfigPath
  nameWithType: IInternalConfigRecord.ConfigPath
  fullName: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hämtar en sträng som representerar en sökväg till konfigurationsfilen."
  syntax:
    content: public string ConfigPath { get; }
    return:
      type: System.String
      description: "En sträng som representerar en sökväg till konfigurationsfilen."
  overload: System.Configuration.Internal.IInternalConfigRecord.ConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(System.String)
  id: GetLkgSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: GetLkgSection(String)
  nameWithType: IInternalConfigRecord.GetLkgSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar ett objekt som representerar en del av en konfiguration från den senaste fungerande (LKG)-konfigurationen."
  syntax:
    content: public object GetLkgSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: "En sträng som representerar en nyckel till ett konfigurationsavsnitt."
    return:
      type: System.Object
      description: "En <xref:System.Object>instans som representerar delen av den senaste fungerande konfiguration som angetts av <code> configKey </code>.</xref:System.Object>"
  overload: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: IInternalConfigRecord.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar en <xref:System.Object>förekomst som representerar en del av en konfigurationsfil.</xref:System.Object>"
  syntax:
    content: public object GetSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: "En sträng som representerar en nyckel till ett konfigurationsavsnitt."
    return:
      type: System.Object
      description: "En <xref:System.Object>förekomst som representerar en del av en konfigurationsfil.</xref:System.Object>"
  overload: System.Configuration.Internal.IInternalConfigRecord.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  id: HasInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: HasInitErrors
  nameWithType: IInternalConfigRecord.HasInitErrors
  fullName: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar ett värde som anger om ett fel uppstod under initieringen av ett konfigurationsobjekt."
  syntax:
    content: public bool HasInitErrors { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om ett fel uppstod under initieringen av ett konfigurationsobjekt; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(System.String)
  id: RefreshSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: RefreshSection(String)
  nameWithType: IInternalConfigRecord.RefreshSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Gör ett angivet avsnitt i konfigurationsobjektet återinitieras."
  syntax:
    content: public void RefreshSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: "En sträng som representerar en nyckel till ett konfigurationsavsnitt som ska uppdateras."
  overload: System.Configuration.Internal.IInternalConfigRecord.RefreshSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.Remove
  id: Remove
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: Remove()
  nameWithType: IInternalConfigRecord.Remove()
  fullName: System.Configuration.Internal.IInternalConfigRecord.Remove()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Tar bort en konfigurationspost."
  syntax:
    content: public void Remove ();
    parameters: []
  overload: System.Configuration.Internal.IInternalConfigRecord.Remove*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.StreamName
  id: StreamName
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: StreamName
  nameWithType: IInternalConfigRecord.StreamName
  fullName: System.Configuration.Internal.IInternalConfigRecord.StreamName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar namnet på en <xref:System.IO.Stream>objekt som utför i/o-aktiviteter i konfigurationsfilen.</xref:System.IO.Stream>"
  syntax:
    content: public string StreamName { get; }
    return:
      type: System.String
      description: "En sträng som representerar namnet på en <xref:System.IO.Stream>objekt som utför i/o-aktiviteter i konfigurationsfilen.</xref:System.IO.Stream>"
  overload: System.Configuration.Internal.IInternalConfigRecord.StreamName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors
  id: ThrowIfInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: ThrowIfInitErrors()
  nameWithType: IInternalConfigRecord.ThrowIfInitErrors()
  fullName: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Ger konfigurationsobjektet behörighet att utlösa ett undantag om det uppstår ett fel under initieringen."
  syntax:
    content: public void ThrowIfInitErrors ();
    parameters: []
  overload: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ConfigPath
  nameWithType: IInternalConfigRecord.ConfigPath
  fullName: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetLkgSection(String)
  nameWithType: IInternalConfigRecord.GetLkgSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.Internal.IInternalConfigRecord.GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetSection(String)
  nameWithType: IInternalConfigRecord.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetSection(String)
- uid: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: HasInitErrors
  nameWithType: IInternalConfigRecord.HasInitErrors
  fullName: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: RefreshSection(String)
  nameWithType: IInternalConfigRecord.RefreshSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(String)
- uid: System.Configuration.Internal.IInternalConfigRecord.Remove
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: Remove()
  nameWithType: IInternalConfigRecord.Remove()
  fullName: System.Configuration.Internal.IInternalConfigRecord.Remove()
- uid: System.Configuration.Internal.IInternalConfigRecord.StreamName
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: StreamName
  nameWithType: IInternalConfigRecord.StreamName
  fullName: System.Configuration.Internal.IInternalConfigRecord.StreamName
- uid: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ThrowIfInitErrors()
  nameWithType: IInternalConfigRecord.ThrowIfInitErrors()
  fullName: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors()
- uid: System.Configuration.Internal.IInternalConfigRecord.ConfigPath*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ConfigPath
  nameWithType: IInternalConfigRecord.ConfigPath
- uid: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetLkgSection
  nameWithType: IInternalConfigRecord.GetLkgSection
- uid: System.Configuration.Internal.IInternalConfigRecord.GetSection*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetSection
  nameWithType: IInternalConfigRecord.GetSection
- uid: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: HasInitErrors
  nameWithType: IInternalConfigRecord.HasInitErrors
- uid: System.Configuration.Internal.IInternalConfigRecord.RefreshSection*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: RefreshSection
  nameWithType: IInternalConfigRecord.RefreshSection
- uid: System.Configuration.Internal.IInternalConfigRecord.Remove*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: Remove
  nameWithType: IInternalConfigRecord.Remove
- uid: System.Configuration.Internal.IInternalConfigRecord.StreamName*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: StreamName
  nameWithType: IInternalConfigRecord.StreamName
- uid: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ThrowIfInitErrors
  nameWithType: IInternalConfigRecord.ThrowIfInitErrors
