### YamlMime:ManagedReference
items:
- uid: System.Web.UI.ExtractTemplateValuesMethod
  id: ExtractTemplateValuesMethod
  langs:
  - csharp
  name: ExtractTemplateValuesMethod
  nameWithType: ExtractTemplateValuesMethod
  fullName: System.Web.UI.ExtractTemplateValuesMethod
  type: Delegate
  summary: "Ger en delegat som ASP.NET extraherar en uppsättning namn/värde-par från en <xref href=&quot;System.Web.UI.IBindableTemplate&quot;> </xref> objekt vid körning. Den här klassen kan inte ärvas."
  remarks: "Delegaten ExtractTemplateValuesMethod används av ASP.NET och är inte avsedd att användas direkt från din kod.       Det här ombudet används av den <xref:System.Web.UI.CompiledBindableTemplateBuilder>klassen, som är standardimplementering av den <xref:System.Web.UI.IBindableTemplate>gränssnitt som ASP.NET genererar när ASP.NET-parsern påträffar dubbelriktad databindning i mallbaserat innehåll.</xref:System.Web.UI.IBindableTemplate> </xref:System.Web.UI.CompiledBindableTemplateBuilder>"
  syntax:
    content: public delegate System.Collections.Specialized.IOrderedDictionary ExtractTemplateValuesMethod(Control control);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
