### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer
  id: IRemoteWebConfigurationHostServer
  children:
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  - System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  langs:
  - csharp
  name: IRemoteWebConfigurationHostServer
  nameWithType: IRemoteWebConfigurationHostServer
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer
  type: Interface
  summary: "Används internt för att stödja fjärråtkomst till konfigurationsdata."
  remarks: "Basklassen som <xref:System.Web.Configuration.RemoteWebConfigurationHostServer>utökar.</xref:System.Web.Configuration.RemoteWebConfigurationHostServer>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Runtime.InteropServices.Guid("A99B591A-23C6-4238-8452-C7B0E895063D")]

      public interface IRemoteWebConfigurationHostServer
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  id: DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Villkorligt krypterar eller dekrypterar värdet för strängen som refererar till den <code> xmlString </code> parameter."
  syntax:
    content: public string DoEncryptOrDecrypt (bool doEncrypt, string xmlString, string protectionProviderName, string protectionProviderType, string[] parameterKeys, string[] parameterValues);
    parameters:
    - id: doEncrypt
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>att kryptera; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> att dekryptera."
    - id: xmlString
      type: System.String
      description: "XML-filen ska krypteras och dekrypteras."
    - id: protectionProviderName
      type: System.String
      description: "Providern som används för att skydda konfigurationsdata."
    - id: protectionProviderType
      type: System.String
      description: "Den <xref:System.Type>av skydd providern.</xref:System.Type>"
    - id: parameterKeys
      type: System.String[]
      description: "Nycklar för valfria parametrar för providern skydd."
    - id: parameterValues
      type: System.String[]
      description: "Värden för valfria parametrar för providern skydd."
    return:
      type: System.String
      description: "En sträng som innehåller antingen krypterade eller dekrypterade värdet för den <code> xmlString </code>."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  id: GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetData(String,Boolean,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Används internt för att stödja fjärråtkomst till konfigurationsdata."
  syntax:
    content: public byte[] GetData (string fileName, bool getReadTimeOnly, out long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Sökvägen till filen fjärrkonfiguration ska kunna nås."
    - id: getReadTimeOnly
      type: System.Boolean
      description: "Ett booleskt värde som anger om bara den `readTime` returneras."
    - id: readTime
      type: System.Int64
      description: "Tid som filen senast användes."
    return:
      type: System.Byte[]
      description: "En <xref uid=&quot;langword_csharp_array&quot; name=&quot;array&quot; href=&quot;&quot;> </xref> av 8-bitars heltal utan tecken (byte) som innehåller konfigurationsdata."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  id: GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar information om konfigurationsfilen."
  syntax:
    content: public void GetFileDetails (string name, out bool exists, out long size, out long createDate, out long lastWriteDate);
    parameters:
    - id: name
      type: System.String
      description: "Namnet på filen."
    - id: exists
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om filen finns; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: size
      type: System.Int64
      description: "Storleken på filen."
    - id: createDate
      type: System.Int64
      description: "Det datum då filen skapades."
    - id: lastWriteDate
      type: System.Int64
      description: "Det datum då filen senast skrevs."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  id: GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Används internt för att stödja fjärråtkomst till konfigurationsdata."
  syntax:
    content: public string GetFilePaths (int webLevel, string path, string site, string locationSubPath);
    parameters:
    - id: webLevel
      type: System.Int32
      description: "Nivån i konfigurationsfilen."
    - id: path
      type: System.String
      description: "Sökvägen till filen fjärrkonfiguration ska kunna nås."
    - id: site
      type: System.String
      description: "Sökvägen till fjärrdatorn."
    - id: locationSubPath
      type: System.String
      description: "Undersökvägen för platsen för konfigurationsfilen."
    return:
      type: System.String
      description: "En sammanfogad sträng som representerar sökvägen till filen i konfigurationsfilen."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  id: WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  langs:
  - csharp
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Används internt för att stödja fjärråtkomst till konfigurationsdata."
  syntax:
    content: public void WriteData (string fileName, string templateFileName, byte[] data, ref long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Sökvägen till filen fjärrkonfiguration ska kunna nås."
    - id: templateFileName
      type: System.String
      description: "Duplicera attribut från filen."
    - id: data
      type: System.Byte[]
      description: "Data som ska skrivas."
    - id: readTime
      type: System.Int64
      description: "Tid som filen senast användes."
  overload: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetData(String,Boolean,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt
  nameWithType: IRemoteWebConfigurationHostServer.DoEncryptOrDecrypt
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetData*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetData
  nameWithType: IRemoteWebConfigurationHostServer.GetData
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFileDetails*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails
  nameWithType: IRemoteWebConfigurationHostServer.GetFileDetails
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.GetFilePaths*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths
  nameWithType: IRemoteWebConfigurationHostServer.GetFilePaths
- uid: System.Web.Configuration.IRemoteWebConfigurationHostServer.WriteData*
  parent: System.Web.Configuration.IRemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData
  nameWithType: IRemoteWebConfigurationHostServer.WriteData
