### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement
  id: WebHttpSecurityElement
  children:
  - System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  langs:
  - csharp
  name: WebHttpSecurityElement
  nameWithType: WebHttpSecurityElement
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement
  type: Class
  summary: "Ett XML-element som konfigureras för en tjänst med slutpunkter som tar emot HTTP-begäranden. Den här klassen kan inte ärvas."
  syntax:
    content: 'public sealed class WebHttpSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: WebHttpSecurityElement()
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.WebHttpSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.WebHttpSecurityElement&quot;> </xref> klass."
  syntax:
    content: public WebHttpSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar ett XML-element som anger säkerhetsläget för en grundläggande HTTP-tjänsten."
  remarks: "Den här egenskapen anger om inställningarna från den <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>egenskapen börjar gälla.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A>"
  syntax:
    content: public System.ServiceModel.WebHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WebHttpSecurityMode
      description: "Ett värde av <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref> som anger om säkerhet på transportnivå eller ingen säkerhet används av en slutpunkt. Standardvärdet är <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Värdet är inte ett giltigt <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar ett XML-element som anger transportnivå säkerhetsinställningarna för en tjänstslutpunkt som konfigurerats för att ta emot HTTP-begäranden."
  remarks: "Använd den <xref:System.ServiceModel.Configuration.WebHttpSecurityElement>objektet som returneras av den här egenskapen anges transporten säkerhetsparametrar.</xref:System.ServiceModel.Configuration.WebHttpSecurityElement> Den <xref:System.ServiceModel.WebHttpSecurityMode>måste anges till den <xref:System.ServiceModel.WebHttpSecurityMode>eller <xref:System.ServiceModel.WebHttpSecurityMode>värde för de inställningar som den <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>egenskap som ska gälla för tjänstslutpunkten.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A> </xref:System.ServiceModel.WebHttpSecurityMode> </xref:System.ServiceModel.WebHttpSecurityMode> </xref:System.ServiceModel.WebHttpSecurityMode> Det här värdet kan anges i konfigurationen eller i den <xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>konstruktor.</xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>"
  syntax:
    content: public System.ServiceModel.Configuration.HttpTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.HttpTransportSecurityElement
      description: "En <xref href=&quot;System.ServiceModel.Configuration.WebHttpSecurityElement&quot;> </xref> som anger säkerhetsinställningar för på transportnivå. En standarduppsättning värden är en <> </> *> av <xref:System.ServiceModel.HttpClientCredentialType>, <> </> *> av <xref href=&quot;System.ServiceModel.HttpProxyCredentialType&quot;> </xref>, och <xref:System.ServiceModel.HttpTransportSecurity.Realm*>= &quot;&quot;.</xref:System.ServiceModel.HttpTransportSecurity.Realm*> </xref:System.ServiceModel.HttpClientCredentialType>"
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: WebHttpSecurityElement()
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.WebHttpSecurityElement()
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
- uid: System.ServiceModel.WebHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WebHttpSecurityMode
  nameWithType: WebHttpSecurityMode
  fullName: System.ServiceModel.WebHttpSecurityMode
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HttpTransportSecurityElement
  nameWithType: HttpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: WebHttpSecurityElement
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
