### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationScopedSettingAttribute
  id: ApplicationScopedSettingAttribute
  children:
  - System.Configuration.ApplicationScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute
  fullName: System.Configuration.ApplicationScopedSettingAttribute
  type: Class
  summary: "Anger att ett program inställningsegenskapen har ett värde som är gemensamma för alla användare på ett program. Den här klassen kan inte ärvas."
  remarks: "Egenskaper för inställningar av programmet har en omfattning som baseras antingen på programmet eller användarnivå. Eftersom kategorierna innebär presentera egenskaper för program som definitionsområde inställningar enhetliga värden för alla användare av programmet, medan användarspecifika egenskaper har särskilda värden för varje användare.       ApplicationScopedSettingAttribute tyder på att en inställning på programnivå bör betraktas som en egenskap att lämpliga lagring beslut bör göras i enlighet med detta av för inställningsprovidern.       Ett scope-attribut krävs för varje egenskap för inställningar. Om en egenskap inte har tillämpats med antingen ApplicationScopedSettingAttribute eller <xref:System.Configuration.UserScopedSettingAttribute>, egenskapen identifieras inte av inställningsprovidern – serialiseras inte.</xref:System.Configuration.UserScopedSettingAttribute> Det går dock inte, tillämpa båda attributen för samma egenskap. Sådana ett försök kommer en <xref:System.Configuration.ConfigurationErrorsException>positionsundantagsfel.</xref:System.Configuration.ConfigurationErrorsException>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ApplicationScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationScopedSettingAttribute
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.ApplicationScopedSettingAttribute&quot;> </xref> klass."
  remarks: "Varje program inställningsegenskapen måste användas med ett enda scope-attribut för att den ska identifieras och serialiseras av för inställningsprovidern."
  syntax:
    content: public ApplicationScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute
