### YamlMime:ManagedReference
items:
- uid: System.Runtime.Hosting.ApplicationActivator
  id: ApplicationActivator
  children:
  - System.Runtime.Hosting.ApplicationActivator.#ctor
  - System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext)
  - System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext,System.String[])
  - System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(System.AppDomainSetup)
  langs:
  - csharp
  name: ApplicationActivator
  nameWithType: ApplicationActivator
  fullName: System.Runtime.Hosting.ApplicationActivator
  type: Class
  summary: "Innehåller basklassen för aktivering av manifest-baserade sammansättningar."
  remarks: "Det finns en enda avsedda instans av klassen ApplicationActivator i varje <xref:System.AppDomain>till vilka alla aktivering anrop dirigeras.</xref:System.AppDomain> Den <xref:System.AppDomainManager>för aktuellt <xref:System.AppDomain>kan ge en egen anpassad ApplicationActivator för detta ändamål.</xref:System.AppDomain> </xref:System.AppDomainManager> Om en anpassad ApplicationActivator inte tillhandahålls, en instans av standard ApplicationActivator skapas.       Följande steg beskriver hur standard <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstance%2A>metodimplementering: 1.</xref:System.Runtime.Hosting.ApplicationActivator.CreateInstance%2A>  Kontrollerar om den <xref:System.ActivationContext>av tillägget ska vara aktiverad matchar den <xref:System.ActivationContext>aktuella domänen; om inte, fortsätter du till steg 2.</xref:System.ActivationContext> </xref:System.ActivationContext> Annars kör sammansättningen och returnerar resultatet kapslas in i ett objekthandtag.      2.  Aktiverar tillägget i en ny <xref:System.AppDomain>.</xref:System.AppDomain> Följande steg vidtas för att initiera en ny <xref:System.AppDomain>med <xref:System.Runtime.Hosting.ActivationArguments>för tillägget.</xref:System.Runtime.Hosting.ActivationArguments> </xref:System.AppDomain>          1.  Skapar ett nytt <xref:System.AppDomainSetup>objekt med hjälp av ett <xref:System.Runtime.Hosting.ActivationArguments>objekt som innehåller aktiveringskontexten för tillägget.</xref:System.Runtime.Hosting.ActivationArguments> </xref:System.AppDomainSetup>          2.  Anrop av <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>metoden för att skapa en ny domän med hjälp av <xref:System.AppDomainSetup>objekt.</xref:System.AppDomainSetup> </xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>          3.  <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>Metoden anropar <xref:System.Security.HostSecurityManager.DetermineApplicationTrust%2A?displayProperty=fullName>metoden för att hämta ett <xref:System.Security.Policy.ApplicationTrust>objekt för tillägget.</xref:System.Security.Policy.ApplicationTrust> </xref:System.Security.HostSecurityManager.DetermineApplicationTrust%2A?displayProperty=fullName> </xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A> Om den <xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A>egenskapen returnerar `true`, tillägget körs.</xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A> Om inte, <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>utlöser en <xref:System.Security.Policy.PolicyException>som anger att körningen behörighet inte att hämta.</xref:System.Security.Policy.PolicyException> </xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>          4.  Om tillägget är betrott kör sedan en ny <xref:System.AppDomain>har skapats och konfigurerats för den <xref:System.ActivationContext>av tillägget, och det tillägg som är inlästa och köras.</xref:System.ActivationContext> </xref:System.AppDomain>          5.  Resultatet av aktivering av tillägget returnerade kapslas in i ett objekthandtag.       En anpassad aktiveraren kan skräddarsy aktivering av ett tillägg till en viss uppsättning omständigheter. Till exempel en anpassad aktiveraren hittade en befintlig <xref:System.AppDomain>att aktivera tillägget i stället för att skapa en ny domän varje gång.</xref:System.AppDomain>       Följande steg beskriver hur en anpassad ApplicationActivator som aktiverar ett tillägg i en befintlig <xref:System.AppDomain>: 1.</xref:System.AppDomain>  Anpassade aktiveraren hittar en domän som har samma <xref:System.ActivationContext>som de tillägg som aktiveras.</xref:System.ActivationContext>      2.  Om <xref:System.ActivationContext>setts aldrig innan pågående, anpassade aktiveraren skapar en ny <xref:System.AppDomain>för det här <xref:System.ActivationContext>genom att anropa den <xref:System.AppDomain.CreateDomain%2A>direkt, metoden eller delegera aktiviteten <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>i grundläggande klassen.</xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A> </xref:System.AppDomain.CreateDomain%2A> </xref:System.ActivationContext> </xref:System.AppDomain> </xref:System.ActivationContext>      3.  Om det finns en befintlig domän med samma <xref:System.ActivationContext>, och sedan aktiveraren kan delegera den <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstance%2A>anrop till ApplicationActivator i måldomänen.</xref:System.Runtime.Hosting.ApplicationActivator.CreateInstance%2A> </xref:System.ActivationContext> Observera att detta är ett domänerna anrop till ett ApplicationActivator som finns i målet <xref:System.AppDomain>.</xref:System.AppDomain>"
  example:
  - "The following code example shows how to obtain an ApplicationActivator object from the current <xref:System.AppDomain.DomainManager%2A> for a manifest-based application.  \n  \n [!code-vb[System.Runtime.Hosting.ApplicationActivator#1](~/add/codesnippet/visualbasic/t-system.runtime.hosting_0_1.vb)]\n [!code-cs[System.Runtime.Hosting.ApplicationActivator#1](~/add/codesnippet/csharp/t-system.runtime.hosting_0_1.cs)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class ApplicationActivator
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Hosting.ApplicationActivator.#ctor
  id: '#ctor'
  parent: System.Runtime.Hosting.ApplicationActivator
  langs:
  - csharp
  name: ApplicationActivator()
  nameWithType: ApplicationActivator.ApplicationActivator()
  fullName: System.Runtime.Hosting.ApplicationActivator.ApplicationActivator()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Hosting
  summary: "Initierar en ny instans av den <xref href=&quot;System.Runtime.Hosting.ApplicationActivator&quot;> </xref> klass."
  syntax:
    content: public ApplicationActivator ();
    parameters: []
  overload: System.Runtime.Hosting.ApplicationActivator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext)
  id: CreateInstance(System.ActivationContext)
  parent: System.Runtime.Hosting.ApplicationActivator
  langs:
  - csharp
  name: CreateInstance(ActivationContext)
  nameWithType: ApplicationActivator.CreateInstance(ActivationContext)
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.Hosting
  summary: "Skapar en instans av programmet som ska aktiveras med hjälp av angivna aktiveringskontexten."
  remarks: "Den här metoden är avsedd för manifest-baserad aktivering av program."
  syntax:
    content: public virtual System.Runtime.Remoting.ObjectHandle CreateInstance (ActivationContext activationContext);
    parameters:
    - id: activationContext
      type: System.ActivationContext
      description: "En <xref href=&quot;System.ActivationContext&quot;> </xref> som identifierar programmet vill aktivera."
    return:
      type: System.Runtime.Remoting.ObjectHandle
      description: "En <xref href=&quot;System.Runtime.Remoting.ObjectHandle&quot;> </xref> som är en Omslutning för det returnera värdet för det program som körs. Returvärdet måste vara packats upp för att komma åt det verkliga objektet."
  overload: System.Runtime.Hosting.ApplicationActivator.CreateInstance*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>activationContext</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext,System.String[])
  id: CreateInstance(System.ActivationContext,System.String[])
  parent: System.Runtime.Hosting.ApplicationActivator
  langs:
  - csharp
  name: CreateInstance(ActivationContext,String[])
  nameWithType: ApplicationActivator.CreateInstance(ActivationContext,String[])
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext,String[])
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.Hosting
  summary: "Skapar en instans av programmet som ska aktiveras med hjälp av angivna aktiveringskontexten och anpassade Aktiveringsdata."
  remarks: "Den här metoden är avsedd för manifest-baserad aktivering av program. Aktiveringsdata består av information, till exempel fråga sträng del i en URL."
  syntax:
    content: public virtual System.Runtime.Remoting.ObjectHandle CreateInstance (ActivationContext activationContext, string[] activationCustomData);
    parameters:
    - id: activationContext
      type: System.ActivationContext
      description: "En <xref href=&quot;System.ActivationContext&quot;> </xref> som identifierar programmet vill aktivera."
    - id: activationCustomData
      type: System.String[]
      description: "Anpassade Aktiveringsdata."
    return:
      type: System.Runtime.Remoting.ObjectHandle
      description: "En <xref href=&quot;System.Runtime.Remoting.ObjectHandle&quot;> </xref> som är en Omslutning för det returnera värdet för det program som körs. Returvärdet måste vara packats upp för att komma åt det verkliga objektet."
  overload: System.Runtime.Hosting.ApplicationActivator.CreateInstance*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>activationContext</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(System.AppDomainSetup)
  id: CreateInstanceHelper(System.AppDomainSetup)
  parent: System.Runtime.Hosting.ApplicationActivator
  langs:
  - csharp
  name: CreateInstanceHelper(AppDomainSetup)
  nameWithType: ApplicationActivator.CreateInstanceHelper(AppDomainSetup)
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(AppDomainSetup)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.Hosting
  summary: "Skapar en instans av ett program med det angivna <xref href=&quot;System.AppDomainSetup&quot;> </xref> objekt."
  remarks: "Den här metoden är avsedd för manifest-baserad aktivering av program."
  syntax:
    content: protected static System.Runtime.Remoting.ObjectHandle CreateInstanceHelper (AppDomainSetup adSetup);
    parameters:
    - id: adSetup
      type: System.AppDomainSetup
      description: "En <xref href=&quot;System.AppDomainSetup&quot;> </xref> objekt vars <xref:System.AppDomainSetup.ActivationArguments*>egenskapen identifierar programmet för att aktivera.</xref:System.AppDomainSetup.ActivationArguments*>"
    return:
      type: System.Runtime.Remoting.ObjectHandle
      description: "En <xref href=&quot;System.Runtime.Remoting.ObjectHandle&quot;> </xref> som är en Omslutning för det returnera värdet för det program som körs. Returvärdet måste vara packats upp för att komma åt det verkliga objektet."
  overload: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "The <xref:System.AppDomainSetup.ActivationArguments*> property of <code>adSetup </code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>.</xref:System.AppDomainSetup.ActivationArguments*>"
  - type: System.Security.Policy.PolicyException
    commentId: T:System.Security.Policy.PolicyException
    description: "Programinstansen kunde inte köras eftersom principinställningar på den aktuella programdomänen inte ger behörighet för det här programmet ska köras."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Security.Policy.PolicyException
  parent: System.Security.Policy
  isExternal: false
  name: PolicyException
  nameWithType: PolicyException
  fullName: System.Security.Policy.PolicyException
- uid: System.Runtime.Hosting.ApplicationActivator.#ctor
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: ApplicationActivator()
  nameWithType: ApplicationActivator.ApplicationActivator()
  fullName: System.Runtime.Hosting.ApplicationActivator.ApplicationActivator()
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext)
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstance(ActivationContext)
  nameWithType: ApplicationActivator.CreateInstance(ActivationContext)
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext)
- uid: System.Runtime.Remoting.ObjectHandle
  parent: System.Runtime.Remoting
  isExternal: false
  name: ObjectHandle
  nameWithType: ObjectHandle
  fullName: System.Runtime.Remoting.ObjectHandle
- uid: System.ActivationContext
  parent: System
  isExternal: false
  name: ActivationContext
  nameWithType: ActivationContext
  fullName: System.ActivationContext
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext,System.String[])
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstance(ActivationContext,String[])
  nameWithType: ApplicationActivator.CreateInstance(ActivationContext,String[])
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext,String[])
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(System.AppDomainSetup)
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstanceHelper(AppDomainSetup)
  nameWithType: ApplicationActivator.CreateInstanceHelper(AppDomainSetup)
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(AppDomainSetup)
- uid: System.AppDomainSetup
  parent: System
  isExternal: false
  name: AppDomainSetup
  nameWithType: AppDomainSetup
  fullName: System.AppDomainSetup
- uid: System.Runtime.Hosting.ApplicationActivator.#ctor*
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: ApplicationActivator
  nameWithType: ApplicationActivator.ApplicationActivator
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance*
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstance
  nameWithType: ApplicationActivator.CreateInstance
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper*
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstanceHelper
  nameWithType: ApplicationActivator.CreateInstanceHelper
