### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPropertyAttribute
  id: ConfigurationPropertyAttribute
  children:
  - System.Configuration.ConfigurationPropertyAttribute.#ctor(System.String)
  - System.Configuration.ConfigurationPropertyAttribute.DefaultValue
  - System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
  - System.Configuration.ConfigurationPropertyAttribute.IsKey
  - System.Configuration.ConfigurationPropertyAttribute.IsRequired
  - System.Configuration.ConfigurationPropertyAttribute.Name
  - System.Configuration.ConfigurationPropertyAttribute.Options
  langs:
  - csharp
  name: ConfigurationPropertyAttribute
  nameWithType: ConfigurationPropertyAttribute
  fullName: System.Configuration.ConfigurationPropertyAttribute
  type: Class
  summary: "Deklarativt instruerar .NET Framework för att skapa en instans av en konfigurationsegenskap. Den här klassen kan inte ärvas."
  remarks: "Du kan använda ConfigurationPropertyAttribute för att skapa snygga en konfigurationsegenskap som instruerar .NET Framework att instansiera och för att initiera egenskapen med värdet för parametern decorating.      > [!NOTE] > Det enklaste sättet att skapa en anpassad konfigurationselement är att använda attributed (deklarativ) modellen. Du deklarera anpassade offentliga egenskaper och skapa snygga dem med attributet ConfigurationPropertyAttribute. För varje egenskap som markerats med attributet använder .NET Framework reflektion läsa decorating parametrar och skapa en relaterad <xref:System.Configuration.ConfigurationProperty>instans.</xref:System.Configuration.ConfigurationProperty> Du kan också använda programmässiga modellen, i så fall är det ditt ansvar att deklarera anpassade offentliga egenskaper och returnera sin samling.       Konfigurationssystemet för .NET Framework ger attributtyper som du kan använda när du skapar anpassade konfigurationselement. Det finns två typer av attributtyper: 1.  De typer som instruerar så att instansiera anpassade konfigurationselementet egenskaperna för .NET Framework. Dessa typer är:- <xref:System.Configuration.ConfigurationCollectionAttribute>-ConfigurationPropertyAttribute 2.</xref:System.Configuration.ConfigurationCollectionAttribute>  De typer som instruerar hur du verifierar anpassade konfigurationselementet egenskaperna för .NET Framework. These types include:          -   <xref:System.Configuration.IntegerValidatorAttribute>          -   <xref:System.Configuration.LongValidatorAttribute>          -   <xref:System.Configuration.RegexStringValidatorAttribute>          -   <xref:System.Configuration.StringValidatorAttribute>          -   <xref:System.Configuration.TimeSpanValidatorAttribute></xref:System.Configuration.TimeSpanValidatorAttribute></xref:System.Configuration.StringValidatorAttribute></xref:System.Configuration.RegexStringValidatorAttribute></xref:System.Configuration.LongValidatorAttribute></xref:System.Configuration.IntegerValidatorAttribute>"
  example:
  - "The following example shows how to define the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the ConfigurationPropertyAttribute attribute.  \n  \n The example contains two classes. The `UrlsSection` custom class uses the ConfigurationPropertyAttribute to define its own properties. The `UsingConfigurationPropertyAttribute` class uses the `UrlsSection` to read and write the custom section in the application configuration file.  \n  \n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#1](~/add/codesnippet/csharp/t-system.configuration.c_21_1.cs)]\n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#1](~/add/codesnippet/visualbasic/t-system.configuration.c_21_1.vb)]  \n  \n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#21](~/add/codesnippet/visualbasic/t-system.configuration.c_21_2.vb)]\n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#21](~/add/codesnippet/csharp/t-system.configuration.c_21_2.cs)]  \n  \n The following is an excerpt of the configuration file containing the custom section as defined in the previous sample.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n    <configSections>  \n        <section name=\"CustomSection\" type=\"UrlsSection, UsingConfigurationPropertyAttribute, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\" />  \n    </configSections>  \n    <CustomSection name=\"Contoso\" url=\"http://www.contoso.com\" />  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ConfigurationPropertyAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: ConfigurationPropertyAttribute(String)
  nameWithType: ConfigurationPropertyAttribute.ConfigurationPropertyAttribute(String)
  fullName: System.Configuration.ConfigurationPropertyAttribute.ConfigurationPropertyAttribute(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initierar en ny instans av <xref href=&quot;System.Configuration.ConfigurationPropertyAttribute&quot;> </xref> klass."
  syntax:
    content: public ConfigurationPropertyAttribute (string name);
    parameters:
    - id: name
      type: System.String
      description: "Namnet på den <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> objekt som definieras."
  overload: System.Configuration.ConfigurationPropertyAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.DefaultValue
  id: DefaultValue
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: DefaultValue
  nameWithType: ConfigurationPropertyAttribute.DefaultValue
  fullName: System.Configuration.ConfigurationPropertyAttribute.DefaultValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hämtar eller anger standardvärdet för egenskapen dekorerade."
  remarks: ''
  example:
  - "The following example shows how to use the DefaultValue property.  \n  \n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#3](~/add/codesnippet/csharp/p-system.configuration.c_19_1.cs)]\n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#3](~/add/codesnippet/visualbasic/p-system.configuration.c_19_1.vb)]"
  syntax:
    content: public object DefaultValue { get; set; }
    return:
      type: System.Object
      description: "Objektet som representerar standardvärdet för egenskapen dekorerade konfigurationselementet."
  overload: System.Configuration.ConfigurationPropertyAttribute.DefaultValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
  id: IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyAttribute.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hämtar eller anger ett värde som anger om detta är egenskapsuppsättningen standardvärdet för konfigurationsegenskapen dekorerade."
  remarks: "IsDefaultCollection egenskapens värde ignoreras om egenskapen dekorerade inte är en samling."
  syntax:
    content: public bool IsDefaultCollection { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om egenskapen representerar standardsamling för ett element. Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standardvärdet är <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.IsKey
  id: IsKey
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: IsKey
  nameWithType: ConfigurationPropertyAttribute.IsKey
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsKey
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hämtar eller anger ett värde som anger om detta är en nyckelegenskap för egenskapen dekorerade element."
  remarks: "IsKey-egenskapen gäller bara om egenskapen du skapa snygga är en samling. Den har inte någon effekt om egenskapen inte är en samling. Flera element kan markeras som IsKey."
  example:
  - "The following example shows how to use the IsKey property.  \n  \n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#2](~/add/codesnippet/csharp/p-system.configuration.c_4_1.cs)]\n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#2](~/add/codesnippet/visualbasic/p-system.configuration.c_4_1.vb)]"
  syntax:
    content: public bool IsKey { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om egenskapen är en nyckelegenskap för ett element i mängden; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standardvärdet är <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationPropertyAttribute.IsKey*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.IsRequired
  id: IsRequired
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: IsRequired
  nameWithType: ConfigurationPropertyAttribute.IsRequired
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsRequired
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hämtar eller anger ett värde som anger om egenskapen dekorerade element krävs."
  remarks: ''
  example:
  - "The following example shows how to use the <xref:System.Configuration.ConfigurationPropertyAttribute.DefaultValue%2A> property.  \n  \n [!code-cs[System.Configuration.ConfigurationPropertyAttribute#3](~/add/codesnippet/csharp/p-system.configuration.c_44_1.cs)]\n [!code-vb[System.Configuration.ConfigurationPropertyAttribute#3](~/add/codesnippet/visualbasic/p-system.configuration.c_44_1.vb)]"
  syntax:
    content: public bool IsRequired { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om egenskapen är obligatoriskt. Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standardvärdet är <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationPropertyAttribute.IsRequired*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.Name
  id: Name
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: Name
  nameWithType: ConfigurationPropertyAttribute.Name
  fullName: System.Configuration.ConfigurationPropertyAttribute.Name
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hämtar namnet på egenskapen dekorerade konfigurationselementet."
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "Namnet på egenskapen dekorerade konfigurationselementet."
  overload: System.Configuration.ConfigurationPropertyAttribute.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPropertyAttribute.Options
  id: Options
  parent: System.Configuration.ConfigurationPropertyAttribute
  langs:
  - csharp
  name: Options
  nameWithType: ConfigurationPropertyAttribute.Options
  fullName: System.Configuration.ConfigurationPropertyAttribute.Options
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hämtar eller anger den <xref href=&quot;System.Configuration.ConfigurationPropertyOptions&quot;> </xref> för egenskapen dekorerade konfigurationselementet."
  syntax:
    content: public System.Configuration.ConfigurationPropertyOptions Options { get; set; }
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: "En av de <xref href=&quot;System.Configuration.ConfigurationPropertyOptions&quot;> </xref> uppräkningsvärden som är associerade med egenskapen."
  overload: System.Configuration.ConfigurationPropertyAttribute.Options*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.ConfigurationPropertyAttribute.#ctor(System.String)
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: ConfigurationPropertyAttribute(String)
  nameWithType: ConfigurationPropertyAttribute.ConfigurationPropertyAttribute(String)
  fullName: System.Configuration.ConfigurationPropertyAttribute.ConfigurationPropertyAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationPropertyAttribute.DefaultValue
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: DefaultValue
  nameWithType: ConfigurationPropertyAttribute.DefaultValue
  fullName: System.Configuration.ConfigurationPropertyAttribute.DefaultValue
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyAttribute.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationPropertyAttribute.IsKey
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsKey
  nameWithType: ConfigurationPropertyAttribute.IsKey
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsKey
- uid: System.Configuration.ConfigurationPropertyAttribute.IsRequired
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsRequired
  nameWithType: ConfigurationPropertyAttribute.IsRequired
  fullName: System.Configuration.ConfigurationPropertyAttribute.IsRequired
- uid: System.Configuration.ConfigurationPropertyAttribute.Name
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: Name
  nameWithType: ConfigurationPropertyAttribute.Name
  fullName: System.Configuration.ConfigurationPropertyAttribute.Name
- uid: System.Configuration.ConfigurationPropertyAttribute.Options
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: Options
  nameWithType: ConfigurationPropertyAttribute.Options
  fullName: System.Configuration.ConfigurationPropertyAttribute.Options
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyAttribute.#ctor*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: ConfigurationPropertyAttribute
  nameWithType: ConfigurationPropertyAttribute.ConfigurationPropertyAttribute
- uid: System.Configuration.ConfigurationPropertyAttribute.DefaultValue*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: DefaultValue
  nameWithType: ConfigurationPropertyAttribute.DefaultValue
- uid: System.Configuration.ConfigurationPropertyAttribute.IsDefaultCollection*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyAttribute.IsDefaultCollection
- uid: System.Configuration.ConfigurationPropertyAttribute.IsKey*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsKey
  nameWithType: ConfigurationPropertyAttribute.IsKey
- uid: System.Configuration.ConfigurationPropertyAttribute.IsRequired*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: IsRequired
  nameWithType: ConfigurationPropertyAttribute.IsRequired
- uid: System.Configuration.ConfigurationPropertyAttribute.Name*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: Name
  nameWithType: ConfigurationPropertyAttribute.Name
- uid: System.Configuration.ConfigurationPropertyAttribute.Options*
  parent: System.Configuration.ConfigurationPropertyAttribute
  isExternal: false
  name: Options
  nameWithType: ConfigurationPropertyAttribute.Options
