### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.UnicodeDecodingConformance
  id: UnicodeDecodingConformance
  children:
  - System.Net.Configuration.UnicodeDecodingConformance.Auto
  - System.Net.Configuration.UnicodeDecodingConformance.Compat
  - System.Net.Configuration.UnicodeDecodingConformance.Loose
  - System.Net.Configuration.UnicodeDecodingConformance.Strict
  langs:
  - csharp
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
  type: Enum
  summary: "Styr hur Unicode-tecken tolkas av den <xref:System.Net.WebUtility.HtmlDecode*>metoder.</xref:System.Net.WebUtility.HtmlDecode*>"
  remarks: "Mer information om hur Unicode-tecken som är avsedda att vara kodad i HTML finns [tecken hoppas i påläggs- och CSS](http://go.microsoft.com/fwlink/?LinkId=256607)."
  syntax:
    content: public enum UnicodeDecodingConformance
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  id: Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Använd automatiska funktioner. Beteendet avkodning bestäms av aktuella programmet mål Framework. För [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)] och senare, Unicode-kodning avkodats är strikt."
  syntax:
    content: Auto
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  id: Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Använd kompatibel beteendet. Anger att inkommande data inte är markerat för giltighet innan som avkodas. Till exempel en indatasträng med &quot;&amp;amp; #xD84C;&quot; skulle avkoda som U + D84C, vilket är en lediga surrogat. Dessutom avkodaren förstår inte i SMP-kodpunkter om de ska visas i form av HTML-kodade surrogat så inputstring &quot;&amp;#144308;&quot; skulle leda till Utdatasträngen &quot;&amp;#144308;&quot;."
  syntax:
    content: Compat
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  id: Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Använd Lös problemet. Liknande kompatibilitets i att det finns ingen giltigheten kontroll, men avkodaren även förstår kodpunkter. Den inmatade strängen &quot;&amp;#144308;&quot; skulle avkoda till tecknet U +&233;B4 korrekt. Den här växeln är tänkt att ge maximala samverkan när avkodaren inte vet vilket format som providern använder för att skapa en kodad sträng."
  syntax:
    content: Loose
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  id: Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Använd strikt beteendet. Anger att inkommande kodade data är markerad för giltighet innan som avkodas. Till exempel en indatasträng med &quot;&amp;#144308;&quot; skulle avkoda som U +&233;B4, men en indatasträng med &quot;&amp;#xD84C;&amp; #xDFB4;&quot;inte avkoda korrekt. Avkoda redan data i strängen är inte markerad för giltighet. Till exempel leder en indatasträng med &quot;\\ud800&quot; utdata-strängen &quot;\\ud800&quot;, som redan avkodas surrogat ignoreras under avkodning, även om det är lediga."
  syntax:
    content: Strict
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
- uid: System.Net.Configuration.UnicodeDecodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
