### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ServerWebConfig
  id: ServerWebConfig
  children:
  - System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  - System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: ServerWebConfig
  nameWithType: ServerWebConfig
  fullName: System.EnterpriseServices.Internal.ServerWebConfig
  type: Class
  summary: "Skapar en Web.config-fil för ett SOAP-aktiverade COM +-program. Kan också lägga till komponenten poster filen för COM-gränssnitt som publiceras i programmet."
  remarks: "Klassen ServerWebConfig används för att skapa en Web.config-fil under skapandet av en virtuell rot i Internet Information Services (IIS) 6.0 för ett SOAP-aktiverade COM +-program. Det kan också lägga till XML-element i filen Web.config för gränssnitt som läggs till i programmet.       ServerWebConfig används internt av .NET Framework. Du behöver inte använda den direkt i din kod."
  syntax:
    content: 'public class ServerWebConfig : System.EnterpriseServices.Internal.IServerWebConfig'
  inheritance:
  - System.Object
  implements:
  - System.EnterpriseServices.Internal.IServerWebConfig
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Initierar en ny instans av den <xref href=&quot;System.EnterpriseServices.Internal.ServerWebConfig&quot;> </xref> klass."
  syntax:
    content: public ServerWebConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Lägger till XML-element i en Web.config-fil för ett COM-gränssnitt som publiceras i ett SOAP-aktiverade COM +-program."
  remarks: "För den angivna typen AddElement metoden lägger till Web.config-filen i `<wellknown>` och `<activated>` element som underordnade till den `<service>` element med följande XPath: `/configuration/system.runtime.remoting/application/service` den `AssemblyName`, `TypeName`, `ProgId`, och `WkoMode` parametrar ingår i attributvärden lagts till två element.       AddElement ska inte anropas direkt. Anropa i stället den <xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>metoden.</xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>"
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string WkoMode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Sökvägen till den befintliga Web.config-filen."
    - id: AssemblyName
      type: System.String
      description: "Namnet på sammansättningen som innehåller typen som läggs till."
    - id: TypeName
      type: System.String
      description: "Namnet på den typ som läggs till."
    - id: ProgId
      type: System.String
      description: "Den programmässiga identifieraren för den typ som läggs till."
    - id: WkoMode
      type: System.String
      description: "En strängkonstant som motsvarar namnet på en medlem från den <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> -uppräkningen, som anger hur ett välkänt objekt aktiveras."
    - id: Error
      type: System.String
      description: "En sträng som ett felmeddelande kan skrivas."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Skapar en Web.config-fil för ett SOAP-aktiverade COM +-program så att filen är redo för XML-element som lagts till för COM-gränssnitt som publiceras."
  remarks: "Metoden Create skapar en Web.config-fil som innehåller hierarkin för ett tomt element med följande XPath: ```   /configuration/system.runtime.remoting/application/service   ``` i stället för en instans skapades av en <xref:System.EnterpriseServices.Internal.ServerWebConfig>klassen objektet och anropas direkt, skapa anropet den <xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A>metoden.</xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A> </xref:System.EnterpriseServices.Internal.ServerWebConfig>"
  syntax:
    content: public void Create (string FilePath, string FilePrefix, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Den mapp där konfigurationsfilen ska skapas."
    - id: FilePrefix
      type: System.String
      description: "Strängvärdet som &quot;Web&quot; som en config-tillägget ska läggas till."
    - id: Error
      type: System.String
      description: "En sträng som ett felmeddelande kan skrivas."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig
  nameWithType: ServerWebConfig.ServerWebConfig
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: ServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create
  nameWithType: ServerWebConfig.Create
