### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.UdpTransportSettings
  id: UdpTransportSettings
  children:
  - System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  - System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  - System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  langs:
  - csharp
  name: UdpTransportSettings
  nameWithType: UdpTransportSettings
  fullName: System.ServiceModel.Discovery.UdpTransportSettings
  type: Class
  summary: "Gör att du kan ange inställningar för UDP-transport."
  syntax:
    content: public class UdpTransportSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  id: DuplicateMessageHistoryLength
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Hämtar eller anger ett värde som anger det maximala antalet hashar för meddelanden används av transporten för att identifiera dubblerade meddelanden."
  remarks: "Den här egenskapen gör administratörer och utvecklare att stänga av algoritmer för identifiering av dubbla meddelanden. Det här värdet inaktiveras 0 dubbla meddelanden identifiering. Standardvärdet är 4112."
  syntax:
    content: public int DuplicateMessageHistoryLength { get; set; }
    return:
      type: System.Int32
      description: "Det maximala antalet hashar för meddelanden ska användas."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  id: MaxBufferPoolSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Hämtar eller anger den maximala storleken i byte för alla pooler för buffert som används av transporten."
  syntax:
    content: public long MaxBufferPoolSize { get; set; }
    return:
      type: System.Int64
      description: "Maximal buffertpoolstorlek."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  id: MaxMulticastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Hämtar eller anger ett värde som anger det maximala antalet gånger som en multicast-meddelande ska skickas vidare (förutom den första överföringen)."
  remarks: "Standardvärdet är 2."
  syntax:
    content: public int MaxMulticastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "Maximalt antal gånger som en multicast-meddelande har skickats."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  id: MaxPendingMessageCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Hämtar eller anger ett värde som anger det maximala antalet meddelanden som har tagits emot men har ännu inte tagits bort från kön för en enskild kanal-instans."
  remarks: "Om kön har nått gränsen för antalet väntande meddelanden, har meddelandet släppts. Standardvärdet är 32."
  syntax:
    content: public int MaxPendingMessageCount { get; set; }
    return:
      type: System.Int32
      description: "Antal meddelanden."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  id: MaxReceivedMessageSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Hämtar eller anger den maximala storleken i byte för ett meddelande kan bearbetas av bindningen."
  remarks: "Standardvärdet är 65507."
  syntax:
    content: public long MaxReceivedMessageSize { get; set; }
    return:
      type: System.Int64
      description: "Den maximala storleken för ett meddelande."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  id: MaxUnicastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Hämtar eller anger ett värde som anger det maximala antalet gånger som ett Unicastmeddelande ska skickas vidare (förutom den första överföringen)."
  remarks: "Standardvärdet är 1."
  syntax:
    content: public int MaxUnicastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "Maximalt antal gånger som ett Unicastmeddelande har skickats."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  id: MulticastInterfaceId
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Hämtar eller anger ett värde som unikt identifierar det nätverkskort som används när du skickar och tar emot multicast-meddelanden."
  remarks: "Vid körning, transport använder det här värdet för att söka efter gränssnittsindexet, som sedan används för att ange den `IP_MULTICAST_IF` och `IPV6_MULTICAST_IF` socket alternativ. Samma gränssnittsindexet används när du ansluter till en multicast-grupp. Standardvärdet är `null`."
  syntax:
    content: public string MulticastInterfaceId { get; set; }
    return:
      type: System.String
      description: "Nätverkskortet identifierare."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  id: SocketReceiveBufferSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Hämtar eller anger storlek på den underliggande WinSock-socketen."
  remarks: "En användare av en mottagande kanal kan använda det här värdet på bindningen för att styra hur systemet beter sig när den tar emot data. Till exempel få ett program som har åtkomst till inkommande [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] meddelanden med den högsta tröskelvärde med ett högre värde skulle Tillåt att meddelanden stackar i bufferten WinSock väntan för programmet att behandla dem.. Med ett lägre värde i samma situation skulle resultera i meddelanden avbryts. Den här egenskapen visar den underliggande WinSock `SO_RCVBUF` socket inställningen. Den här egenskapens värde måste vara minst storleken på <xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A>.</xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A> Anger ett värde mindre än den <xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A>resulterar i ett runtime-undantag.</xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A> Standardvärdet är 65536."
  syntax:
    content: public int SocketReceiveBufferSize { get; set; }
    return:
      type: System.Int32
      description: "Storlek."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  id: TimeToLive
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Hämtar eller anger ett värde som anger antalet nätverkshopp för segmentet som kan bläddra i ett multicast-paket."
  remarks: "Den här egenskapen visar funktioner som är associerade med den `IP_MULTICAST_TTL` och `IP_TTL` socket alternativ. Standardvärdet är 1."
  syntax:
    content: public int TimeToLive { get; set; }
    return:
      type: System.Int32
      description: "Antalet nätverkshopp segment."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
