### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IConfigMapPathFactory
  id: IConfigMapPathFactory
  children:
  - System.Web.Configuration.IConfigMapPathFactory.Create(System.String,System.String)
  langs:
  - csharp
  name: IConfigMapPathFactory
  nameWithType: IConfigMapPathFactory
  fullName: System.Web.Configuration.IConfigMapPathFactory
  type: Interface
  summary: "Mappar configuration virtuella och fysiska sökvägarna."
  remarks: "IConfigMapPathFactory introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public interface IConfigMapPathFactory
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPathFactory.Create(System.String,System.String)
  id: Create(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPathFactory
  langs:
  - csharp
  name: Create(String,String)
  nameWithType: IConfigMapPathFactory.Create(String,String)
  fullName: System.Web.Configuration.IConfigMapPathFactory.Create(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Skapar gränssnitt för mappning mellan configuration-virtuella och fysiska sökvägar."
  remarks: "Skapa introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public System.Web.Configuration.IConfigMapPath Create (string virtualPath, string physicalPath);
    parameters:
    - id: virtualPath
      type: System.String
      description: "Den virtuella sökvägen konfigurationsfilen."
    - id: physicalPath
      type: System.String
      description: "Den fysiska sökvägen konfigurationsfilen."
    return:
      type: System.Web.Configuration.IConfigMapPath
      description: "Den <xref href=&quot;System.Web.Configuration.IConfigMapPath&quot;> </xref> som är associerat med den angivna konfigurationsfilen sökvägsmappning."
  overload: System.Web.Configuration.IConfigMapPathFactory.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.IConfigMapPathFactory.Create(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPathFactory
  isExternal: false
  name: Create(String,String)
  nameWithType: IConfigMapPathFactory.Create(String,String)
  fullName: System.Web.Configuration.IConfigMapPathFactory.Create(String,String)
- uid: System.Web.Configuration.IConfigMapPath
  parent: System.Web.Configuration
  isExternal: false
  name: IConfigMapPath
  nameWithType: IConfigMapPath
  fullName: System.Web.Configuration.IConfigMapPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.IConfigMapPathFactory.Create*
  parent: System.Web.Configuration.IConfigMapPathFactory
  isExternal: false
  name: Create
  nameWithType: IConfigMapPathFactory.Create
