### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpWebRequestElement
  id: HttpWebRequestElement
  children:
  - System.Net.Configuration.HttpWebRequestElement.#ctor
  - System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  - System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  - System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  - System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  - System.Net.Configuration.HttpWebRequestElement.Properties
  - System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  langs:
  - csharp
  name: HttpWebRequestElement
  nameWithType: HttpWebRequestElement
  fullName: System.Net.Configuration.HttpWebRequestElement
  type: Class
  summary: "Representerar den maximala längden för svarshuvuden. Den här klassen kan inte ärvas."
  remarks: "This class corresponds to the `maximumResponseHeadersLength` attribute of the [\\&lt;httpWebRequest\\&gt; Element (Network Settings)](../Topic/%3ChttpWebRequest%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n The information in this class applies to responses to requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class HttpWebRequestElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: HttpWebRequestElement()
  nameWithType: HttpWebRequestElement.HttpWebRequestElement()
  fullName: System.Net.Configuration.HttpWebRequestElement.HttpWebRequestElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Net.Configuration.HttpWebRequestElement&quot;> </xref> klass."
  remarks: "Den här konstruktorn lägger till en <xref:System.Configuration.ConfigurationProperty>objekt som representerar den <xref:System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength%2A>till den <xref:System.Configuration.ConfigurationElement.Properties%2A>samling.</xref:System.Configuration.ConfigurationElement.Properties%2A> </xref:System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength%2A> </xref:System.Configuration.ConfigurationProperty>"
  syntax:
    content: public HttpWebRequestElement ();
    parameters: []
  overload: System.Net.Configuration.HttpWebRequestElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  id: MaximumErrorResponseLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Hämtar eller anger den maximala tillåtna längden på ett felsvar."
  syntax:
    content: public int MaximumErrorResponseLength { get; set; }
    return:
      type: System.Int32
      description: "En 32-bitars signerat heltal som innehåller den maximala längden i kilobyte (1 024 byte) på felsvar. Standardvärdet är 64."
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  id: MaximumResponseHeadersLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Hämtar eller anger den högsta tillåtna längden för svarshuvuden."
  remarks: "Längden mäts i kilobyte (1&024; byte) och innehåller Statusrad svar och svarshuvuden samt alla extra kontrolltecken som tas emot som en del av HTTP-protokollet.       Värdet-1 innebär inga begränsningar på svarshuvuden; värdet 0 innebär att alla begäranden som misslyckas."
  syntax:
    content: public int MaximumResponseHeadersLength { get; set; }
    return:
      type: System.Int32
      description: "En 32-bitars signerat heltal som innehåller den maximala längden i kilobyte (1 024 byte) för svarshuvuden. Standardvärdet är 64."
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  id: MaximumUnauthorizedUploadLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Hämtar eller anger den maximala längden på en överföring som svar på en obehörig felkod."
  syntax:
    content: public int MaximumUnauthorizedUploadLength { get; set; }
    return:
      type: System.Int32
      description: "En 32-bitars heltal som innehåller den maximala längden (i flera enheter på 1 024 byte) på en överföring som svar på en obehörig felkod. Värdet&1; anger att ingen storleksgräns kommer att gälla för överföringen. Ange egenskapen MaximumUnauthorizedUploadLength till ett annat värde skickas endast begärandetexten om det är mindre än antalet byte som anges. Så skulle värdet 1 anger att endast skicka begärandetexten om det är mindre än 1 024 byte.       Standardvärdet för den här egenskapen är-1."
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  id: PostDeserialize
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: HttpWebRequestElement.PostDeserialize()
  fullName: System.Net.Configuration.HttpWebRequestElement.PostDeserialize()
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Net.Configuration.HttpWebRequestElement.PostDeserialize*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
  fullName: System.Net.Configuration.HttpWebRequestElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.Net.Configuration.HttpWebRequestElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  id: UseUnsafeHeaderParsing
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
  fullName: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Den här egenskapen ignoreras valideringsfel som kan uppstå under parsning av HTTP."
  remarks: "När den här egenskapen har angetts `false`, att följande verifieringar utförs under HTTP-parsning:-Använd CRLF i slutet av raden kod; med CR eller LF enbart är inte tillåten.      -Huvuden namn får inte innehålla blanksteg.      – Om det finns flera status rader, behandlas alla ytterligare status rader som felaktigt huvud namn/värde-par.      -Statusrad måste ha en beskrivning av status, förutom en statuskod.      -Huvudet namn får innehålla inte icke-ASCII-tecken i dem. Verifieringen utförs om den här egenskapen anges till `true` eller `false`.       När ett brott mot protokollet inträffar, ett <xref:System.Net.WebException>undantag med statusen inställd på <xref:System.Net.WebExceptionStatus>.</xref:System.Net.WebExceptionStatus> </xref:System.Net.WebException> Om den `UseUnsafeHeaderParsing` egenskap är inställd på `true`, verifieringsfel ignoreras.       Egenskapen `true` har säkerhetsaspekter, så den bör endast göras om bakåtkompatibilitet med en server krävs."
  syntax:
    content: public bool UseUnsafeHeaderParsing { get; set; }
    return:
      type: System.Boolean
      description: "Booleskt värde som anger om den här egenskapen har ställts in."
  overload: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: HttpWebRequestElement()
  nameWithType: HttpWebRequestElement.HttpWebRequestElement()
  fullName: System.Net.Configuration.HttpWebRequestElement.HttpWebRequestElement()
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: PostDeserialize()
  nameWithType: HttpWebRequestElement.PostDeserialize()
  fullName: System.Net.Configuration.HttpWebRequestElement.PostDeserialize()
- uid: System.Net.Configuration.HttpWebRequestElement.Properties
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
  fullName: System.Net.Configuration.HttpWebRequestElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
  fullName: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: HttpWebRequestElement
  nameWithType: HttpWebRequestElement.HttpWebRequestElement
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: PostDeserialize
  nameWithType: HttpWebRequestElement.PostDeserialize
- uid: System.Net.Configuration.HttpWebRequestElement.Properties*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
