### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationInstance
  id: WorkflowApplicationInstance
  children:
  - System.Activities.WorkflowApplicationInstance.Abandon
  - System.Activities.WorkflowApplicationInstance.Abandon(System.TimeSpan)
  - System.Activities.WorkflowApplicationInstance.BeginAbandon(System.AsyncCallback,System.Object)
  - System.Activities.WorkflowApplicationInstance.BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  - System.Activities.WorkflowApplicationInstance.CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  - System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  - System.Activities.WorkflowApplicationInstance.EndAbandon(System.IAsyncResult)
  - System.Activities.WorkflowApplicationInstance.InstanceId
  - System.Activities.WorkflowApplicationInstance.InstanceStore
  langs:
  - csharp
  name: WorkflowApplicationInstance
  nameWithType: WorkflowApplicationInstance
  fullName: System.Activities.WorkflowApplicationInstance
  type: Class
  summary: "Anger information om en arbetsflödesinstans för programmet."
  remarks: "Den här klassen stöder versionshantering och funktionerna för dynamisk uppdatering i Windows Workflow Foundation. [!INCLUDE[crabout](~/add/includes/ajax-current-ext-md.md)]arbetsflöde för versionshantering, arbetsflöde identitet och dynamisk uppdatering, finns i följande avsnitt.       [Arbetsflöde för versionshantering](http://go.microsoft.com/fwlink/?LinkID=271561) beskriver versionshantering arbetsflödesfunktionen lanserades i [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)].       [Dynamisk uppdatering](http://go.microsoft.com/fwlink/?LinkId=271563) beskriver hur du uppdaterar Arbetsflödesdefinitionen för en beständiga arbetsflödesinstans med hjälp av dynamisk uppdatering.       [Med hjälp av WorkflowApplication identitet och versionshantering](http://go.microsoft.com/fwlink/?LinkId=271564) beskriver hur du använder <xref:System.Activities.WorkflowIdentity>som värd för flera versioner av ett arbetsflöde sida-vid-sida.</xref:System.Activities.WorkflowIdentity>       [Sida vid sida versionshantering i WorkflowServiceHost](http://go.microsoft.com/fwlink/?LinkId=271565) beskriver hur som värd för flera versioner av ett arbetsflöde på en enda slutpunkt.       [Så här: värden flera versioner av ett arbetsflöde sida-vid-sida](http://go.microsoft.com/fwlink/?LinkId=271566) detta steg den [komma igång-Självstudier](http://go.microsoft.com/fwlink/?LinkId=271570) visar uppdaterar en arbetsflödesdefinition och vara värd för arbetsflöden med hjälp av både gamla och nya definition på samma gång.       [Så här: uppdatera definitionen av en arbetsflödesinstans som körs](http://go.microsoft.com/fwlink/?LinkId=271567) detta steg den [komma igång-Självstudier](http://go.microsoft.com/fwlink/?LinkId=271570) visar uppdatera beständiga arbetsflödesinstanser om du vill använda en ny arbetsflödesdefinitionen."
  syntax:
    content: public class WorkflowApplicationInstance
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.Abandon
  id: Abandon
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: Abandon()
  nameWithType: WorkflowApplicationInstance.Abandon()
  fullName: System.Activities.WorkflowApplicationInstance.Abandon()
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Gör att du övergår till tillståndet övergivna tillståndsdatorn."
  syntax:
    content: public void Abandon ();
    parameters: []
  overload: System.Activities.WorkflowApplicationInstance.Abandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.Abandon(System.TimeSpan)
  id: Abandon(System.TimeSpan)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: Abandon(TimeSpan)
  nameWithType: WorkflowApplicationInstance.Abandon(TimeSpan)
  fullName: System.Activities.WorkflowApplicationInstance.Abandon(TimeSpan)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Orsakar tillståndsdator övergår till tillståndet övergivna med det angivna tidsgränsvärdet."
  syntax:
    content: public void Abandon (TimeSpan timeout);
    parameters:
    - id: timeout
      type: System.TimeSpan
      description: "Tidsgräns för avbryta åtgärden slutförts."
  overload: System.Activities.WorkflowApplicationInstance.Abandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.AsyncCallback,System.Object)
  id: BeginAbandon(System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: BeginAbandon(AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Börjar en asynkron avbryta åtgärden."
  syntax:
    content: public IAsyncResult BeginAbandon (AsyncCallback callback, object state);
    parameters:
    - id: callback
      type: System.AsyncCallback
      description: "Det asynkrona återanrop ombud som tar emot ett meddelande om genomförandet asynkron åtgärd."
    - id: state
      type: System.Object
      description: "Användardefinierat tillståndsdata."
    return:
      type: System.IAsyncResult
      description: "En asynkron avbryta åtgärden."
  overload: System.Activities.WorkflowApplicationInstance.BeginAbandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  id: BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: BeginAbandon(TimeSpan,AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Börjar en asynkron avbryta åtgärden."
  syntax:
    content: public IAsyncResult BeginAbandon (TimeSpan timeout, AsyncCallback callback, object state);
    parameters:
    - id: timeout
      type: System.TimeSpan
      description: "Tidsgränsen som innehåller orsaken till att avbryta åtgärden."
    - id: callback
      type: System.AsyncCallback
      description: "Det asynkrona återanrop ombud som tar emot ett meddelande om genomförandet asynkron åtgärd."
    - id: state
      type: System.Object
      description: "Användardefinierat tillståndsdata."
    return:
      type: System.IAsyncResult
      description: "En asynkron avbryta åtgärden."
  overload: System.Activities.WorkflowApplicationInstance.BeginAbandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  id: CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  nameWithType: WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  fullName: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Returnerar ett värde som anger om WorkflowApplicationInstance kan installera uppdateringen."
  syntax:
    content: public bool CanApplyUpdate (System.Activities.DynamicUpdate.DynamicUpdateMap updateMap, out System.Collections.Generic.IList<System.Activities.DynamicUpdate.ActivityBlockingUpdate> activitiesBlockingUpdate);
    parameters:
    - id: updateMap
      type: System.Activities.DynamicUpdate.DynamicUpdateMap
      description: "Uppdaterar en karta."
    - id: activitiesBlockingUpdate
      type: System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}
      description: "Aktiviteter som blockerar uppdateringen."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>Om WorkflowApplicationInstance kan tillämpa uppdateringen. Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.WorkflowApplicationInstance.CanApplyUpdate*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  id: DefinitionIdentity
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: DefinitionIdentity
  nameWithType: WorkflowApplicationInstance.DefinitionIdentity
  fullName: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Hämtar eller anger definitionsidentitet av arbetsflödet."
  syntax:
    content: public System.Activities.WorkflowIdentity DefinitionIdentity { get; }
    return:
      type: System.Activities.WorkflowIdentity
      description: "Definitionsidentitet av arbetsflödet."
  overload: System.Activities.WorkflowApplicationInstance.DefinitionIdentity*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.EndAbandon(System.IAsyncResult)
  id: EndAbandon(System.IAsyncResult)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: EndAbandon(IAsyncResult)
  nameWithType: WorkflowApplicationInstance.EndAbandon(IAsyncResult)
  fullName: System.Activities.WorkflowApplicationInstance.EndAbandon(IAsyncResult)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Slutför en asynkron avbryta åtgärden."
  syntax:
    content: public void EndAbandon (IAsyncResult asyncResult);
    parameters:
    - id: asyncResult
      type: System.IAsyncResult
      description: "IAsyncResult som returneras av ett anrop till någon av BeginAbandon metoder."
  overload: System.Activities.WorkflowApplicationInstance.EndAbandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.InstanceId
  id: InstanceId
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: InstanceId
  nameWithType: WorkflowApplicationInstance.InstanceId
  fullName: System.Activities.WorkflowApplicationInstance.InstanceId
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Hämtar den unika identifieraren för arbetsflödesinstansen."
  syntax:
    content: public Guid InstanceId { get; }
    return:
      type: System.Guid
      description: "Unik identifierare för arbetsflödesinstansen."
  overload: System.Activities.WorkflowApplicationInstance.InstanceId*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.InstanceStore
  id: InstanceStore
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: InstanceStore
  nameWithType: WorkflowApplicationInstance.InstanceStore
  fullName: System.Activities.WorkflowApplicationInstance.InstanceStore
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Hämtar eller anger ett objekt som ger åtkomst till det beständiga tillståndet för den aktuella instansen av arbetsflöde för programmet."
  syntax:
    content: public System.Runtime.DurableInstancing.InstanceStore InstanceStore { get; }
    return:
      type: System.Runtime.DurableInstancing.InstanceStore
      description: "Ett objekt som ger åtkomst till det beständiga tillståndet för den aktuella instansen av arbetsflöde för programmet."
  overload: System.Activities.WorkflowApplicationInstance.InstanceStore*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.WorkflowApplicationInstance.Abandon
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: Abandon()
  nameWithType: WorkflowApplicationInstance.Abandon()
  fullName: System.Activities.WorkflowApplicationInstance.Abandon()
- uid: System.Activities.WorkflowApplicationInstance.Abandon(System.TimeSpan)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: Abandon(TimeSpan)
  nameWithType: WorkflowApplicationInstance.Abandon(TimeSpan)
  fullName: System.Activities.WorkflowApplicationInstance.Abandon(TimeSpan)
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: BeginAbandon(AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
- uid: System.IAsyncResult
  parent: System
  isExternal: true
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: System.AsyncCallback
  parent: System
  isExternal: true
  name: AsyncCallback
  nameWithType: AsyncCallback
  fullName: System.AsyncCallback
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: BeginAbandon(TimeSpan,AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
- uid: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  nameWithType: WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  fullName: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.DynamicUpdate.DynamicUpdateMap
  parent: System.Activities.DynamicUpdate
  isExternal: false
  name: DynamicUpdateMap
  nameWithType: DynamicUpdateMap
  fullName: System.Activities.DynamicUpdate.DynamicUpdateMap
- uid: System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}
  parent: System.Collections.Generic
  isExternal: true
  name: IList<ActivityBlockingUpdate>
  nameWithType: IList<ActivityBlockingUpdate>
  fullName: System.Collections.Generic.IList<System.Activities.DynamicUpdate.ActivityBlockingUpdate>
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: IList<System.Activities.DynamicUpdate.ActivityBlockingUpdate>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Activities.DynamicUpdate.ActivityBlockingUpdate
    name: ActivityBlockingUpdate
    nameWithType: ActivityBlockingUpdate
    fullName: ActivityBlockingUpdate
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: DefinitionIdentity
  nameWithType: WorkflowApplicationInstance.DefinitionIdentity
  fullName: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
- uid: System.Activities.WorkflowIdentity
  parent: System.Activities
  isExternal: false
  name: WorkflowIdentity
  nameWithType: WorkflowIdentity
  fullName: System.Activities.WorkflowIdentity
- uid: System.Activities.WorkflowApplicationInstance.EndAbandon(System.IAsyncResult)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: EndAbandon(IAsyncResult)
  nameWithType: WorkflowApplicationInstance.EndAbandon(IAsyncResult)
  fullName: System.Activities.WorkflowApplicationInstance.EndAbandon(IAsyncResult)
- uid: System.Activities.WorkflowApplicationInstance.InstanceId
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationInstance.InstanceId
  fullName: System.Activities.WorkflowApplicationInstance.InstanceId
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationInstance.InstanceStore
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceStore
  nameWithType: WorkflowApplicationInstance.InstanceStore
  fullName: System.Activities.WorkflowApplicationInstance.InstanceStore
- uid: System.Runtime.DurableInstancing.InstanceStore
  parent: System.Runtime.DurableInstancing
  isExternal: false
  name: InstanceStore
  nameWithType: InstanceStore
  fullName: System.Runtime.DurableInstancing.InstanceStore
- uid: System.Activities.WorkflowApplicationInstance.Abandon*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: Abandon
  nameWithType: WorkflowApplicationInstance.Abandon
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: BeginAbandon
  nameWithType: WorkflowApplicationInstance.BeginAbandon
- uid: System.Activities.WorkflowApplicationInstance.CanApplyUpdate*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: CanApplyUpdate
  nameWithType: WorkflowApplicationInstance.CanApplyUpdate
- uid: System.Activities.WorkflowApplicationInstance.DefinitionIdentity*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: DefinitionIdentity
  nameWithType: WorkflowApplicationInstance.DefinitionIdentity
- uid: System.Activities.WorkflowApplicationInstance.EndAbandon*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: EndAbandon
  nameWithType: WorkflowApplicationInstance.EndAbandon
- uid: System.Activities.WorkflowApplicationInstance.InstanceId*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationInstance.InstanceId
- uid: System.Activities.WorkflowApplicationInstance.InstanceStore*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceStore
  nameWithType: WorkflowApplicationInstance.InstanceStore
