### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Compiler
  id: Compiler
  children:
  - System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  - System.Web.Configuration.Compiler.CompilerOptions
  - System.Web.Configuration.Compiler.Extension
  - System.Web.Configuration.Compiler.Language
  - System.Web.Configuration.Compiler.Properties
  - System.Web.Configuration.Compiler.Type
  - System.Web.Configuration.Compiler.WarningLevel
  langs:
  - csharp
  name: Compiler
  nameWithType: Compiler
  fullName: System.Web.Configuration.Compiler
  type: Class
  summary: "Definierar en kompilator som används för att stödja infrastrukturen för kompilering av webbprogram. Den här klassen kan inte ärvas."
  remarks: "Klassen kompileraren ger ett sätt att komma åt en kompilator konfigurationselementet."
  syntax:
    content: 'public sealed class Compiler : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  id: '#ctor(System.String,System.String,System.String,System.String,System.Int32)'
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Skapar en instans av en <xref href=&quot;System.Web.Configuration.Compiler&quot;> </xref> initieras till de angivna värdena."
  syntax:
    content: public Compiler (string compilerOptions, string extension, string language, string type, int warningLevel);
    parameters:
    - id: compilerOptions
      type: System.String
      description: "Visar en lista över ytterligare kompileraren-specifika alternativ som kan skickas under kompilering."
    - id: extension
      type: System.String
      description: "Innehåller en semikolonavgränsad lista med filtillägget används för dynamiska bakgrundskod filer. Till exempel &quot;.cs&quot;."
    - id: language
      type: System.String
      description: "Innehåller en semikolonavgränsad lista över språk som används i dynamiska kompileringsfiler. Till exempel &quot;c#; cs; csharp&quot;."
    - id: type
      type: System.String
      description: "Anger en kommaavgränsad klass/sammansättningen kombination som anger den .NET Framework-klassen."
    - id: warningLevel
      type: System.Int32
      description: "Anger varningsnivåer för kompilatorn."
  overload: System.Web.Configuration.Compiler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.CompilerOptions
  id: CompilerOptions
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar en lista över kompileraren-specifika alternativ under kompilering."
  syntax:
    content: public string CompilerOptions { get; }
    return:
      type: System.String
      description: "Ett värde som anger kompileraren-specifika alternativ under kompilering. Detta är inte en sammanfogad uppsättning men snarare åsidosätter eventuella tidigare definierade värden i tidigare konfigurationsposter."
  overload: System.Web.Configuration.Compiler.CompilerOptions*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Extension
  id: Extension
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar en lista med filtillägget används för dynamiska bakgrundskod filer."
  remarks: "När listan med filtillägget innehåller mer än ett tillägg är är listan avgränsade med semikolon."
  syntax:
    content: public string Extension { get; }
    return:
      type: System.String
      description: "Ett värde som anger filnamn-tillägg som används för dynamiska bakgrundskod filer refereras filer i katalogen kod och andra filer."
  overload: System.Web.Configuration.Compiler.Extension*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Language
  id: Language
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar en lista över programmeringsspråk som ska användas i dynamiska kompileringsfiler."
  remarks: "När listan över programmeringsspråk innehåller flera olika språk, är avgränsade med semikolon."
  syntax:
    content: public string Language { get; }
    return:
      type: System.String
      description: "Ett värde som anger de programmeringsspråk som ska användas i dynamiska kompileringsfiler."
  overload: System.Web.Configuration.Compiler.Language*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Properties
  id: Properties
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.Web.Configuration.Compiler.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Type
  id: Type
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar kompileraren ange namnet på providern språk för dynamiska kompileringsfiler."
  remarks: "Anger namnet på providern språk, inklusive namnet på den sammansättning som innehåller providerns implementering."
  syntax:
    content: public string Type { get; }
    return:
      type: System.String
      description: "Ett värde som anger namnet på språket kompileraren ska användas i dynamiska kompileringsfiler."
  overload: System.Web.Configuration.Compiler.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.WarningLevel
  id: WarningLevel
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar varningsnivå kompileraren."
  remarks: "Anger standard-kompilatorn varningsnivå; Anger nivån som behandlar språk providern kompileringsvarningar som fel."
  syntax:
    content: public int WarningLevel { get; }
    return:
      type: System.Int32
      description: "Ett värde som anger varningsnivå kompileraren."
  overload: System.Web.Configuration.Compiler.WarningLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.Compiler.CompilerOptions
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.Compiler.Type
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
- uid: System.Web.Configuration.Compiler.#ctor*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler
  nameWithType: Compiler.Compiler
- uid: System.Web.Configuration.Compiler.CompilerOptions*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
- uid: System.Web.Configuration.Compiler.Type*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
