### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebConfigurationFileMap
  id: WebConfigurationFileMap
  children:
  - System.Web.Configuration.WebConfigurationFileMap.#ctor
  - System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  - System.Web.Configuration.WebConfigurationFileMap.Clone
  - System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  langs:
  - csharp
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap
  fullName: System.Web.Configuration.WebConfigurationFileMap
  type: Class
  summary: "Definierar konfigurationen filen mappningar för ett webbprogram. Den här klassen kan inte ärvas."
  remarks: "Klassen WebConfigurationFileMap används för att ange filen för Web konfigurationshierarki. Som standard använder konfigurationssystemet för IIS-metabasen för att avgöra Web filen hierarkin. Om IIS inte är installerat, eller om ett program riktar sig till en version av .NET Framework som inte är den senaste versionen som är installerad på servern, ger klassen WebConfigurationFileMap dig möjlighet att definiera en anpassad hierarki.       Klassen WebConfigurationFileMap kan ange en enskild sökväg eller flera sökvägar som rör konfigurationsfiler."
  syntax:
    content: 'public sealed class WebConfigurationFileMap : System.Configuration.ConfigurationFileMap'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationFileMap
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Skapar en ny instans av den <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klass."
  syntax:
    content: public WebConfigurationFileMap ();
    parameters: []
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klassen med konfigurationsfilnamnet angivna datorn."
  remarks: "Du använder den här konstruktorn när du utvecklar en version av den [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] som är äldre än den senaste som är installerad på datorn. Metoden kan du ange en konfigurationsfil för datorn som är lämpligt för versionen av den [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] som är målet.      > [!NOTE] > Trots att konstruktorn accepterar bara sökvägen till filen Machine.config, Konfigurationssystemet får också information Web.config-rotfilen i samma katalog där Machine.config-filen finns."
  syntax:
    content: public WebConfigurationFileMap (string machineConfigFileName);
    parameters:
    - id: machineConfigFileName
      type: System.String
      description: "Datornamnet på konfigurationsfilen med den fullständiga fysiska sökvägen (till exempel `c:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\CONFIG\\machine.config`)."
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  id: Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Skapar en ny instans av en <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klass med samma värde som den befintliga instansen."
  syntax:
    content: public override object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "En ny instans av en <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klass."
  overload: System.Web.Configuration.WebConfigurationFileMap.Clone*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  id: VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar listan samlingen med virtuella kataloger för ett webbprogram."
  remarks: "Virtuella kataloger för ett webbprogram kanske inte nödvändigtvis mappar till fysiska kataloger på servern. Den <xref:System.Web.Configuration.VirtualDirectoryMapping>klassen är beroende av IIS.</xref:System.Web.Configuration.VirtualDirectoryMapping>"
  syntax:
    content: public System.Web.Configuration.VirtualDirectoryMappingCollection VirtualDirectories { get; }
    return:
      type: System.Web.Configuration.VirtualDirectoryMappingCollection
      description: "En samling <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> objekt."
  overload: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: System.Configuration.ConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
- uid: System.Web.Configuration.VirtualDirectoryMappingCollection
  parent: System.Web.Configuration
  isExternal: false
  name: VirtualDirectoryMappingCollection
  nameWithType: VirtualDirectoryMappingCollection
  fullName: System.Web.Configuration.VirtualDirectoryMappingCollection
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone
  nameWithType: WebConfigurationFileMap.Clone
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
