### YamlMime:ManagedReference
items:
- uid: System.Xml.Schema.XmlSchemaCompilationSettings
  id: XmlSchemaCompilationSettings
  children:
  - System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  - System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  langs:
  - csharp
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings
  type: Class
  summary: "Innehåller alternativ för kompilering av schemat för den <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> klass som den här klassen inte kan ärvas."
  remarks: "XmlSchemaCompilationSettings-klassen innehåller kompilering Schemaalternativ för <xref:System.Xml.Schema.XmlSchemaSet>klass.</xref:System.Xml.Schema.XmlSchemaSet> Till exempel den <xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>egenskapen anger att den <xref:System.Xml.Schema.XmlSchemaSet>ska söka efter unikt partikel tillskrivningar UPA ()-överträdelser när scheman i den <xref:System.Xml.Schema.XmlSchemaSet>kompileras.</xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>"
  syntax:
    content: public sealed class XmlSchemaCompilationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  id: '#ctor'
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "Initierar en ny instans av den <xref href=&quot;System.Xml.Schema.XmlSchemaCompilationSettings&quot;> </xref> klass."
  syntax:
    content: public XmlSchemaCompilationSettings ();
    parameters: []
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  id: EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "Hämtar eller anger ett värde som anger om den <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> ska söka efter unikt partikel tillskrivningar UPA ()-överträdelser."
  remarks: "När egenskapen EnableUpaCheck har angetts `false`, verifiering ska utföras baserat på följande regler.      1.  Om det finns ett val mellan en stark typ och ett jokertecken i <xref:System.Xml.Schema.XmlSchemaSet>hämtar strikt typkontroll partikel enligt följande schema- och XML-exempel.</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:any namespace=&quot;##any&quot;/>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `</xs:sequence>`I följande Xml den `A` element ska kopplas till `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>` i schemat.       `<A>some text</A>`      1.  Om det finns ett val mellan två strikt typkontroll element i <xref:System.Xml.Schema.XmlSchemaSet>ska välja den första.</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot;/>`       `</xs:sequence>`I följande Xml den `B` element ska kopplas till `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>` i schemat.       `<A/>`       `<B/>`"
  syntax:
    content: public bool EnableUpaCheck { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> ska söka efter överträdelser unika partikel tillskrivningar UPA (); annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standardvärdet är <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
