### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlWriterSettings
  id: XamlXmlWriterSettings
  children:
  - System.Xaml.XamlXmlWriterSettings.#ctor
  - System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  - System.Xaml.XamlXmlWriterSettings.CloseOutput
  - System.Xaml.XamlXmlWriterSettings.Copy
  langs:
  - csharp
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
  type: Class
  summary: "Ger initieringsinställningar för den <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> XAML writer implementering."
  remarks: "Standardvärdena för alla XamlXmlWriterSettings värden är `false`."
  syntax:
    content: 'public class XamlXmlWriterSettings : System.Xaml.XamlWriterSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlWriterSettings
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initierar en ny instans av den <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> klass."
  syntax:
    content: public XamlXmlWriterSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  id: AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Hämtar eller anger ett värde som anger om den <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> alltid anta att den giltiga XAML indata för dubbla lösning eller kontrollera andra fel."
  syntax:
    content: public bool AssumeValidInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> hoppar över vissa verifiering eller fel kontroller, till exempel hantera undantag på dubbletter av medlemmar. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Om den <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> utlöser undantag när felaktig XAML påträffades. Standardvärdet är <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  id: CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Hämtar eller anger ett värde som anger om den <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> ska avslutas omedelbart <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> eller andra åtgärder, eller om XAML-skrivaren i stället ska skriva utdata bufferten innan du stänger. Använd den här inställningen med försiktighet; stänger omedelbart kan resultera i ogiltigt XAML inte kan läsas in igen."
  remarks: "Den här inställningen påverkar logiken för <xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>, som anropar `Close` på den underliggande <xref:System.Xml.XmlWriter>eller <xref:System.IO.TextWriter>när CloseOutput är `true`; och den anropar <xref:System.Xaml.XamlXmlWriter.Flush%2A>(igen knutna till den underliggande <xref:System.Xml.XmlWriter>eller <xref:System.IO.TextWriter>) om CloseOutput `false`.</xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Flush%2A> </xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>"
  syntax:
    content: public bool CloseOutput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> stängs direkt på en <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> eller liknande åtgärder. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Om återstående buffert utdata skrivs innan den <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> släpps. Standardvärdet är <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  id: Copy
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
  type: Method
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Returnerar en kopia av detta <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> instans."
  syntax:
    content: public System.Xaml.XamlXmlWriterSettings Copy ();
    parameters: []
    return:
      type: System.Xaml.XamlXmlWriterSettings
      description: "Returnerade kopia."
  overload: System.Xaml.XamlXmlWriterSettings.Copy*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlWriterSettings
  isExternal: false
  name: System.Xaml.XamlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
- uid: System.Xaml.XamlXmlWriterSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy
  nameWithType: XamlXmlWriterSettings.Copy
