### YamlMime:ManagedReference
items:
- uid: System.Configuration.OverrideMode
  id: OverrideMode
  children:
  - System.Configuration.OverrideMode.Allow
  - System.Configuration.OverrideMode.Deny
  - System.Configuration.OverrideMode.Inherit
  langs:
  - csharp
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
  type: Enum
  summary: "Anger beteendet åsidosättning av en konfigurationselement för konfigurationselement i underkataloger."
  remarks: "Använda uppräkningsvärdena OverrideMode för att ange <xref:System.Configuration.SectionInformation.OverrideMode%2A>egenskapen för <xref:System.Configuration.SectionInformation>klassen.</xref:System.Configuration.SectionInformation> </xref:System.Configuration.SectionInformation.OverrideMode%2A> Du kan ange den här egenskapen för att ange programmässigt åsidosättning beteendet för en konfigurationselementet eller grupp. Deklarativt ange åsidosättning beteendet för alla konfigurationselement i ett element i `allowOverride` attribut. Den <xref:System.Configuration.SectionInformation.OverrideMode%2A>egenskapen ger mer detaljerad kontroll över elementen i en `location` element.</xref:System.Configuration.SectionInformation.OverrideMode%2A>"
  syntax:
    content: public enum OverrideMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Allow
  id: Allow
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konfigurationsinställningen element eller grupp kan åsidosättas med konfigurationsinställningar som finns i underkataloger."
  syntax:
    content: Allow
    return:
      type: System.Configuration.OverrideMode
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Deny
  id: Deny
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konfigurationsinställningen element eller grupp kan inte åsidosättas av konfigurationsinställningar som finns i underkataloger."
  syntax:
    content: Deny
    return:
      type: System.Configuration.OverrideMode
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Inherit
  id: Inherit
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konfigurationsinställningen element eller grupp åsidosätts av konfigurationsinställningar som finns i underkataloger om uttryckligen tillåts i ett överordnat element på den aktuella konfigurationselementet eller grupp. Behörigheter för att åsidosätta anges med hjälp av den <xref uid=&quot;langword_csharp_OverrideMode&quot; name=&quot;OverrideMode&quot; href=&quot;&quot;> </xref> attribut."
  syntax:
    content: Inherit
    return:
      type: System.Configuration.OverrideMode
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.OverrideMode.Allow
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
- uid: System.Configuration.OverrideMode
  parent: System.Configuration
  isExternal: false
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
- uid: System.Configuration.OverrideMode.Deny
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
- uid: System.Configuration.OverrideMode.Inherit
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
