### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupNameAttribute
  id: SettingsGroupNameAttribute
  children:
  - System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupNameAttribute.GroupName
  langs:
  - csharp
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute
  fullName: System.Configuration.SettingsGroupNameAttribute
  type: Class
  summary: "Anger ett namn för programgruppen inställningar för egenskapen. Den här klassen kan inte ärvas."
  remarks: "Ett program inställningar klass som härletts från <xref:System.Configuration.ApplicationSettingsBase>, definierar en eller flera egenskaper som hör till samma inställningar för egenskapen programgrupp.</xref:System.Configuration.ApplicationSettingsBase> Som standard tilldelas gruppen namnet på klassen inställningar. SettingsGroupNameAttribute kan dock användas för att explicit ange ett namn för Egenskapsgruppen. Det här namnet kan vara till hjälp för att ordna stora mängder egenskaper för att få hjälp i designläge programming verktyg och körning administrativa verktyg, och så vidare. Providern tillhörande inställningar kan även använda det här namnet för att organisera inställningar i datalagret.       SettingsGroupNameAttribute kan endast tillämpas på klassnivå."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupNameAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.SettingsGroupNameAttribute&quot;> </xref> klass."
  remarks: "Även om teoretisk maxlängd på `groupName` parameter är begränsad av de övre gränserna för en <xref:System.Int32>, praktiska gränserna som bestäms av användbarhet och kvotbegränsningar av inställningsprovidern blir mycket mindre.</xref:System.Int32>      > [!NOTE] > Inställningar gruppnamnet behöver inte vara unika."
  syntax:
    content: public SettingsGroupNameAttribute (string groupName);
    parameters:
    - id: groupName
      type: System.String
      description: "En <xref:System.String>som innehåller namnet på programgruppen inställningar egenskap.</xref:System.String>"
  overload: System.Configuration.SettingsGroupNameAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  id: GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar namnet på programgruppen inställningar för egenskapen."
  remarks: "Egenskapsvärdet GroupName anges av den <xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A>konstruktor.</xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A>"
  syntax:
    content: public string GroupName { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som innehåller namnet på programgruppen inställningar egenskap.</xref:System.String>"
  overload: System.Configuration.SettingsGroupNameAttribute.GroupName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
