### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationAllowDefinition
  id: ConfigurationAllowDefinition
  children:
  - System.Configuration.ConfigurationAllowDefinition.Everywhere
  - System.Configuration.ConfigurationAllowDefinition.MachineOnly
  - System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  - System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  langs:
  - csharp
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
  type: Enum
  summary: "Anger platser i hierarkin configuration-fil som kan ange eller åsidosätta egenskaper som ingår i en <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> objekt."
  remarks: "Värdena i den här uppräkningen är eventuellt används när du skapar en ny instans av <xref:System.Configuration.ConfigurationSection>klassen.</xref:System.Configuration.ConfigurationSection>"
  syntax:
    content: public enum ConfigurationAllowDefinition
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowDefinition.Everywhere
  id: Everywhere
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: Everywhere
  nameWithType: ConfigurationAllowDefinition.Everywhere
  fullName: System.Configuration.ConfigurationAllowDefinition.Everywhere
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Den <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> kan definieras var som helst."
  syntax:
    content: Everywhere
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  id: MachineOnly
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: MachineOnly
  nameWithType: ConfigurationAllowDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Den <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> kan definieras endast i filen Machine.config."
  syntax:
    content: MachineOnly
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  id: MachineToApplication
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: MachineToApplication
  nameWithType: ConfigurationAllowDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Den <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> kan definieras i antingen filen Machine.config datornivå Web.config-filen finns i samma katalog som Machine.config, eller på den översta nivån programmets Web.config-file hittades i virtuella rotkatalog, men inte i underkataloger i en virtuell rot."
  syntax:
    content: MachineToApplication
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  id: MachineToWebRoot
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: MachineToWebRoot
  nameWithType: ConfigurationAllowDefinition.MachineToWebRoot
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Den <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> kan definieras i filen Machine.config eller Web.config-filen datornivå finns i samma katalog som Machine.config, men inte i programmets Web.config-filer."
  syntax:
    content: MachineToWebRoot
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationAllowDefinition.Everywhere
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: Everywhere
  nameWithType: ConfigurationAllowDefinition.Everywhere
  fullName: System.Configuration.ConfigurationAllowDefinition.Everywhere
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
- uid: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineOnly
  nameWithType: ConfigurationAllowDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineOnly
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineToApplication
  nameWithType: ConfigurationAllowDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineToWebRoot
  nameWithType: ConfigurationAllowDefinition.MachineToWebRoot
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
