### YamlMime:ManagedReference
items:
- uid: System.Windows.Forms.FlowLayoutSettings
  id: FlowLayoutSettings
  children:
  - System.Windows.Forms.FlowLayoutSettings.FlowDirection
  - System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(System.Object)
  - System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  - System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(System.Object,System.Boolean)
  - System.Windows.Forms.FlowLayoutSettings.WrapContents
  langs:
  - csharp
  name: FlowLayoutSettings
  nameWithType: FlowLayoutSettings
  fullName: System.Windows.Forms.FlowLayoutSettings
  type: Class
  summary: "Samlar in de egenskaper som är kopplade till flödet layouter."
  remarks: "Klassen FlowLayoutSettings samlar in och hanterar de egenskaper som är kopplade till schemat flödet layout. Den här klassen används internt av den <xref:System.Windows.Forms.FlowLayoutPanel>och <xref:System.Windows.Forms.ToolStrip>klasser, samt layoutmotor flöde.</xref:System.Windows.Forms.ToolStrip> </xref:System.Windows.Forms.FlowLayoutPanel> Klassen FlowLayoutSettings används av layoutmotorn för att avgöra hur till layout behållarens underordnade kontroller.       Klassen FlowLayoutSettings hanterar följande uppgifter:-flödesriktning av på varandra följande kontroller.      – Om bör innehållet radbryts eller bryts om underordnade kontroller inte kan ingå i sina överordnade.       FlowLayoutSettings saknar en offentlig konstruktor."
  syntax:
    content: >-
      [System.ComponentModel.DefaultProperty("FlowDirection")]

      public class FlowLayoutSettings : System.Windows.Forms.LayoutSettings
  inheritance:
  - System.Object
  - System.Windows.Forms.LayoutSettings
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.FlowDirection
  id: FlowDirection
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: FlowDirection
  nameWithType: FlowLayoutSettings.FlowDirection
  fullName: System.Windows.Forms.FlowLayoutSettings.FlowDirection
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Hämtar eller anger ett värde som anger flödesriktning av på varandra följande kontroller."
  remarks: "FlowDirection är standardinställningen för egenskapen för <xref:System.Windows.Forms.FlowLayoutSettings>klassen.</xref:System.Windows.Forms.FlowLayoutSettings>"
  syntax:
    content: public System.Windows.Forms.FlowDirection FlowDirection { get; set; }
    return:
      type: System.Windows.Forms.FlowDirection
      description: "En <xref href=&quot;System.Windows.Forms.FlowDirection&quot;> </xref> som anger flödesriktning av på varandra följande kontroller i behållaren. Standardvärdet är <xref href=&quot;System.Windows.Forms.FlowDirection&quot;> </xref>."
  overload: System.Windows.Forms.FlowLayoutSettings.FlowDirection*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(System.Object)
  id: GetFlowBreak(System.Object)
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: GetFlowBreak(Object)
  nameWithType: FlowLayoutSettings.GetFlowBreak(Object)
  fullName: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(Object)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Returnerar ett värde som representerar flödet bryta för kontrollen."
  syntax:
    content: public bool GetFlowBreak (object child);
    parameters:
    - id: child
      type: System.Object
      description: "Den underordnade kontrollen."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>om flödet break anges; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  id: LayoutEngine
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: LayoutEngine
  nameWithType: FlowLayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Hämtar den aktuella layoutmotorn flöde."
  remarks: "Den <xref:System.Windows.Forms.TableLayoutSettings.LayoutEngine%2A>egenskapen används vanligtvis i två kontexter:-en behållare som använder en flödeslayout.</xref:System.Windows.Forms.TableLayoutSettings.LayoutEngine%2A>      -En kontroll som ingår i en behållare för layout av flödet (till exempel en knapp som finns i en cell i en <xref:System.Windows.Forms.FlowLayoutPanel>).</xref:System.Windows.Forms.FlowLayoutPanel>"
  syntax:
    content: public override System.Windows.Forms.Layout.LayoutEngine LayoutEngine { get; }
    return:
      type: System.Windows.Forms.Layout.LayoutEngine
      description: "Den <xref href=&quot;System.Windows.Forms.Layout.LayoutEngine&quot;> </xref> för närvarande används."
  overload: System.Windows.Forms.FlowLayoutSettings.LayoutEngine*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(System.Object,System.Boolean)
  id: SetFlowBreak(System.Object,System.Boolean)
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: SetFlowBreak(Object,Boolean)
  nameWithType: FlowLayoutSettings.SetFlowBreak(Object,Boolean)
  fullName: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(Object,Boolean)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Anger det värde som representerar flödet bryta för kontrollen."
  syntax:
    content: public void SetFlowBreak (object child, bool value);
    parameters:
    - id: child
      type: System.Object
      description: "Den underordnade kontrollen."
    - id: value
      type: System.Boolean
      description: "Flödet break värdet som ska anges."
  overload: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.FlowLayoutSettings.WrapContents
  id: WrapContents
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: WrapContents
  nameWithType: FlowLayoutSettings.WrapContents
  fullName: System.Windows.Forms.FlowLayoutSettings.WrapContents
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Hämtar eller anger ett värde som anger om innehållet ska radbryts eller bryts när de överskrider de ursprungliga gränserna för deras behållare."
  remarks: "Om behållaren är för liten för att visa alla underordnade kontroller, kommer åtminstone en kontroll att beskäras oavsett WrapContents värde.       Efterföljande storleksändring av behållaren ska behålla layout på kontrollerna."
  syntax:
    content: public bool WrapContents { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om innehållet ska omslutas; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> om innehållet ska beskäras. Standardvärdet är <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Forms.FlowLayoutSettings.WrapContents*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: System.Windows.Forms.LayoutSettings
- uid: System.Windows.Forms.FlowLayoutSettings.FlowDirection
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: FlowDirection
  nameWithType: FlowLayoutSettings.FlowDirection
  fullName: System.Windows.Forms.FlowLayoutSettings.FlowDirection
- uid: System.Windows.Forms.FlowDirection
  parent: System.Windows.Forms
  isExternal: false
  name: FlowDirection
  nameWithType: FlowDirection
  fullName: System.Windows.Forms.FlowDirection
- uid: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(System.Object)
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: GetFlowBreak(Object)
  nameWithType: FlowLayoutSettings.GetFlowBreak(Object)
  fullName: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: FlowLayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
- uid: System.Windows.Forms.Layout.LayoutEngine
  parent: System.Windows.Forms.Layout
  isExternal: false
  name: LayoutEngine
  nameWithType: LayoutEngine
  fullName: System.Windows.Forms.Layout.LayoutEngine
- uid: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(System.Object,System.Boolean)
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: SetFlowBreak(Object,Boolean)
  nameWithType: FlowLayoutSettings.SetFlowBreak(Object,Boolean)
  fullName: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(Object,Boolean)
- uid: System.Windows.Forms.FlowLayoutSettings.WrapContents
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: WrapContents
  nameWithType: FlowLayoutSettings.WrapContents
  fullName: System.Windows.Forms.FlowLayoutSettings.WrapContents
- uid: System.Windows.Forms.FlowLayoutSettings.FlowDirection*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: FlowDirection
  nameWithType: FlowLayoutSettings.FlowDirection
- uid: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: GetFlowBreak
  nameWithType: FlowLayoutSettings.GetFlowBreak
- uid: System.Windows.Forms.FlowLayoutSettings.LayoutEngine*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: FlowLayoutSettings.LayoutEngine
- uid: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: SetFlowBreak
  nameWithType: FlowLayoutSettings.SetFlowBreak
- uid: System.Windows.Forms.FlowLayoutSettings.WrapContents*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: WrapContents
  nameWithType: FlowLayoutSettings.WrapContents
