### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSerializeAsAttribute
  id: SettingsSerializeAsAttribute
  children:
  - System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  - System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  langs:
  - csharp
  name: SettingsSerializeAsAttribute
  nameWithType: SettingsSerializeAsAttribute
  fullName: System.Configuration.SettingsSerializeAsAttribute
  type: Class
  summary: "Anger serialiseringsmekanismen som ska användas i inställningarna för providern. Den här klassen kan inte ärvas."
  remarks: "En inställningsprovider stöder ofta mer än en av scheman som standard serialisering .NET Framework. Dessa scheman beskrivs av den <xref:System.Configuration.SettingsSerializeAs>uppräkning och innehålla oformaterad text, XML- och binär serialisering.</xref:System.Configuration.SettingsSerializeAs> En provider stöder dessutom eventuellt ett schema för anpassad serialisering.       Med SettingsSerializeAsAttribute, kan du ange vilka serialiseringsmekanism som ska användas för ett givet programklassen eller en egenskap. Det här attributet betraktas som en begäran till inställningar för leverantören. Det kan du ignorera eller orsaka fel om providern eller enskilda egenskapstypen inte stöder det angivna serialisering schemat. Om det här attributet inte är tillgänglig ger providern oftast en standardmekanism för serialisering, oftast oformaterad text.       Även om inställningsprovidern kan ge ett sätt att ändra dynamiskt serialiseringsmekanism vid körning kan är detta inte en vanlig funktion."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsSerializeAsAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  id: '#ctor(System.Configuration.SettingsSerializeAs)'
  parent: System.Configuration.SettingsSerializeAsAttribute
  langs:
  - csharp
  name: SettingsSerializeAsAttribute(SettingsSerializeAs)
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  fullName: System.Configuration.SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initierar en instans av den <xref href=&quot;System.Configuration.SettingsSerializeAsAttribute&quot;> </xref> klass."
  remarks: "Om inställningar för leverantören eller typen för egenskapen som ska konverteras inte stöder serialisering schemat som anges av den `serializeAs` parameter, åtgärden kan ha något av följande:-inställningsprovidern kan ignorera attributet och använda dess standardschema för serialisering.      -Serialisering misslyckas utan ett svar. Inställningsegenskapen programmet sparas inte.      -Undantag kan uppstå under serialiseringen."
  syntax:
    content: public SettingsSerializeAsAttribute (System.Configuration.SettingsSerializeAs serializeAs);
    parameters:
    - id: serializeAs
      type: System.Configuration.SettingsSerializeAs
      description: "En <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> räknas upp värde som anger schemat för serialisering."
  overload: System.Configuration.SettingsSerializeAsAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  id: SerializeAs
  parent: System.Configuration.SettingsSerializeAsAttribute
  langs:
  - csharp
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
  fullName: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar den <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> uppräkningsvärde som anger schemat för serialisering."
  remarks: "Den här egenskapen har angetts i den <xref:System.Configuration.SettingsSerializeAsAttribute.%23ctor%2A>konstruktor.</xref:System.Configuration.SettingsSerializeAsAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SettingsSerializeAs SerializeAs { get; }
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "En <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> räknas upp värde som anger schemat för serialisering."
  overload: System.Configuration.SettingsSerializeAsAttribute.SerializeAs*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SettingsSerializeAsAttribute(SettingsSerializeAs)
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  fullName: System.Configuration.SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
  fullName: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor*
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SettingsSerializeAsAttribute
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs*
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
