### YamlMime:ManagedReference
items:
- uid: System.Configuration.ValidatorCallback
  id: ValidatorCallback
  langs:
  - csharp
  name: ValidatorCallback
  nameWithType: ValidatorCallback
  fullName: System.Configuration.ValidatorCallback
  type: Delegate
  summary: "Representerar en metod som ska anropas efter verifiering av ett objekt."
  syntax:
    content: public delegate void ValidatorCallback(object value);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
