### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.IServerWebConfig
  id: IServerWebConfig
  children:
  - System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: IServerWebConfig
  nameWithType: IServerWebConfig
  fullName: System.EnterpriseServices.Internal.IServerWebConfig
  type: Interface
  summary: "Skapar en Web.config-fil för ett SOAP-aktiverade COM +-program och lägger till komponenten poster i filen för COM-gränssnitt som publiceras i programmet."
  remarks: "Gränssnittet IServerWebConfig implementeras endast av den <xref:System.EnterpriseServices.Internal.ServerWebConfig>klassen och används bara i .NET Framework-infrastruktur.</xref:System.EnterpriseServices.Internal.ServerWebConfig> I stället för att implementera gränssnittet eller en instans skapades av ett IServerWebConfig gränssnitt objekt, använda den <xref:System.EnterpriseServices.Internal.Publish>klassen som implementerar det <xref:System.EnterpriseServices.Internal.IComSoapPublisher>gränssnittet.</xref:System.EnterpriseServices.Internal.IComSoapPublisher> </xref:System.EnterpriseServices.Internal.Publish>       IServerWebConfig används internt av .NET Framework. Du behöver inte använda den direkt i din kod."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("6261e4b5-572a-4142-a2f9-1fe1a0c97097")]

      public interface IServerWebConfig
  implements: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Lägger till XML-element i en Web.config-fil för ett COM-gränssnitt som publiceras i ett SOAP-aktiverade COM +-program."
  remarks: "Finns det <xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A>metod för implementeringsinformation.</xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A> Men du behöver inte att anropa `AddElement` metoden direkt."
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string Mode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Sökvägen för den befintliga Web.config-filen."
    - id: AssemblyName
      type: System.String
      description: "Namnet på sammansättningen som innehåller typen som läggs till."
    - id: TypeName
      type: System.String
      description: "Namnet på den typ som läggs till."
    - id: ProgId
      type: System.String
      description: "Den programmässiga identifieraren för den typ som läggs till."
    - id: Mode
      type: System.String
      description: "En strängkonstant som motsvarar namnet på en medlem från den <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> -uppräkningen, som anger hur ett välkänt objekt aktiveras."
    - id: Error
      type: System.String
      description: "En sträng som ett felmeddelande kan skrivas."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Skapar en Web.config-fil för ett SOAP-aktiverade COM +-program så att filen är redo för XML-element som lagts till för COM-gränssnitt som publiceras."
  remarks: "Finns det <xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A>metod för implementeringsinformation.</xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A> Men du behöver inte att anropa `Create` direkt."
  syntax:
    content: public void Create (string FilePath, string FileRootName, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Den mapp där du vill skapa konfigurationsfilen."
    - id: FileRootName
      type: System.String
      description: "Det strängvärde som tillägget config kan läggas till (till exempel Web för Web.config)."
    - id: Error
      type: System.String
      description: "En sträng som ett felmeddelande kan skrivas."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: IServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create
  nameWithType: IServerWebConfig.Create
