### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs
  id: SelectingProviderEventArgs
  children:
  - System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  - System.Web.ApplicationServices.SelectingProviderEventArgs.User
  langs:
  - csharp
  name: SelectingProviderEventArgs
  nameWithType: SelectingProviderEventArgs
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs
  type: Class
  summary: "Tillhandahåller data för den <xref href=&quot;System.Web.ApplicationServices.RoleService.SelectingProvider&quot;> </xref> händelse."
  remarks: "Klassen SelectingProviderEventArgs tillhandahåller värden till den <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>händelsehanteraren.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider> Du skapar en <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>händelsehanterare för att välja rollprovider vid körning.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>       Den <xref:System.Web.ApplicationServices.RoleService>klassen aktiverar den <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>händelse när antingen den <xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>metoden eller <xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A>-metoden i den <xref:System.Web.ApplicationServices.RoleService>klassen kallas.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A> </xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A> </xref:System.Web.ApplicationServices.RoleService.SelectingProvider> </xref:System.Web.ApplicationServices.RoleService>       Du använder den <xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A>egenskapen för att hämta information om den inloggade användaren.</xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A> Om du vill hämta rollinformation via en icke-förvalt rollprovider, ange den <xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>egenskapen till namnet på den rollprovider som du vill i <xref:System.Web.ApplicationServices.RoleService>objekt som ska användas.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the SelectingProviderEventArgs object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/t-system.web.application_0_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/t-system.web.application_0_1.asax)]"
  syntax:
    content: 'public class SelectingProviderEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  id: ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Hämtar eller anger rollen providern som används för att hämta användarens roller."
  remarks: "Du kan använda egenskapen ProviderName ange rollprovider under den <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>händelse.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_3_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_3_1.asax)]"
  syntax:
    content: public string ProviderName { get; set; }
    return:
      type: System.String
      description: "Namnet på den rollprovider som används för att hämta användarens roller."
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  id: User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Hämtar den autentiserade användaren."
  remarks: "Du kan använda egenskapen användaren för att hämta information om användaren under den <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>händelse.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_9_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_9_1.asax)]"
  syntax:
    content: public System.Security.Principal.IPrincipal User { get; }
    return:
      type: System.Security.Principal.IPrincipal
      description: "Ett objekt som innehåller den autentiserade användaren."
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
- uid: System.Security.Principal.IPrincipal
  parent: System.Security.Principal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: System.Security.Principal.IPrincipal
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
