### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelLogLevel
  id: ProcessModelLogLevel
  children:
  - System.Web.Configuration.ProcessModelLogLevel.All
  - System.Web.Configuration.ProcessModelLogLevel.Errors
  - System.Web.Configuration.ProcessModelLogLevel.None
  langs:
  - csharp
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
  type: Enum
  summary: "Anger händelsetyper som ska loggas i händelseloggen."
  remarks: "Uppräkningen ProcessModelLogLevel innehåller värdena som ska användas när du ställer in den <xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>egenskapen.</xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>       Standardvärdet är fel."
  example:
  - "The following code example shows how to set the <xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/csharp/t-system.web.configurati_95_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/visualbasic/t-system.web.configurati_95_1.vb)]"
  syntax:
    content: public enum ProcessModelLogLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  id: All
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att alla bearbeta händelser loggas. Det här fältet är konstant."
  remarks: "Använd det här alternativet om du vill utforska eventuella fel som ett program kan utfärda utan någon filtrering. Det här alternativet är användbart under byggnaden och felsökning fasen."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  id: Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att endast oväntade avstängningar minnesgränsen avstängningar och deadlock avstängningar loggas. Det här fältet är konstant."
  remarks: "Detta är standardvärdet."
  syntax:
    content: Errors
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  id: None
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att inga händelser loggas. Det här fältet är konstant."
  remarks: "Du kanske vill använda det här alternativet för testade och distribuerade program."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
- uid: System.Web.Configuration.ProcessModelLogLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
