### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ClientTarget
  id: ClientTarget
  children:
  - System.Web.Configuration.ClientTarget.#ctor(System.String,System.String)
  - System.Web.Configuration.ClientTarget.Alias
  - System.Web.Configuration.ClientTarget.Properties
  - System.Web.Configuration.ClientTarget.UserAgent
  langs:
  - csharp
  name: ClientTarget
  nameWithType: ClientTarget
  fullName: System.Web.Configuration.ClientTarget
  type: Class
  summary: "Definierar det alias som är associerade med användaren målagenten som ASP.NET serverkontroller ska återge innehållet. Den här klassen kan inte ärvas."
  remarks: "Klassen ClientTarget refererar till element som har lagts till i den `clientTarget` avsnittet i konfigurationsfilen.       Klassen ClientTarget tillhör en grupp som innehåller <xref:System.Web.Configuration.ClientTargetCollection>klassen och <xref:System.Web.Configuration.ClientTargetSection>klass.</xref:System.Web.Configuration.ClientTargetSection> </xref:System.Web.Configuration.ClientTargetCollection>       ClientTarget-klassen innehåller två egenskaper som identifierar en klientwebbläsare som också kallas användaragent. En egenskap är det alias som är kopplade till klientens webbläsare som identifieras av den andra egenskapen. ASP.NET använder denna information för att återge serverkontroller på en sida.       Information om hur du användaragenten eller dess alias programmässigt finns i <xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName>egenskap.</xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName> Information om hur du användaragenten eller dess alias deklarativt finns [@ Page](http://msdn.microsoft.com/en-us/f06cf9e5-22bb-461d-8b8f-549e53ff40a4).       Om den <xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName>egenskapen inte har angetts i <xref:System.Web.HttpBrowserCapabilities>objekt som är associerad med den <xref:System.Web.UI.Page.Request%2A?displayProperty=fullName>egenskapen visar funktionerna i klientens webbläsare.</xref:System.Web.UI.Page.Request%2A?displayProperty=fullName> </xref:System.Web.HttpBrowserCapabilities> </xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName> (Den visar funktionerna i typ av webbläsare, men inte nödvändigtvis inställningarna i en specifik instans av webbläsaren.) Om egenskapen har värdet klientens webbläsaridentifiering är inaktiverat och sidan använder webbläsarfunktioner som är associerade med användaragentsträngen som du definierar. Du kan ange egenskapen till någon giltig användaragentsträngen."
  example:
  - "This section provides two code examples. The first demonstrates how to declaratively specify values for several properties of the ClientTarget class. The second shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file. You use this object to access the ClientTarget objects it contains.  \n  \n The following code example shows how to declaratively specify values for several properties of the ClientTarget class.  \n  \n```  \n<clientTarget>  \n  <add alias=  \n    \"uplevel\"   \n    userAgent=\"Mozilla/5.0 (compatible;MSIE 6.0;Windows NT 5.1)\"/>  \n  <add alias=\"downlevel\" userAgent=\"Generic Downlevel\"/>  \n</clientTarget>  \n```  \n  \n The following code example shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#1](~/add/codesnippet/visualbasic/t-system.web.configurati_29_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#1](~/add/codesnippet/csharp/t-system.web.configurati_29_1.cs)]"
  syntax:
    content: 'public sealed class ClientTarget : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: ClientTarget(String,String)
  nameWithType: ClientTarget.ClientTarget(String,String)
  fullName: System.Web.Configuration.ClientTarget.ClientTarget(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Web.Configuration.ClientTarget&quot;> </xref> klass."
  syntax:
    content: public ClientTarget (string alias, string userAgent);
    parameters:
    - id: alias
      type: System.String
      description: "Namnet som används för att referera till en specifik användaragent."
    - id: userAgent
      type: System.String
      description: "Användaragenten identifieringsnamn."
  overload: System.Web.Configuration.ClientTarget.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.Alias
  id: Alias
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: Alias
  nameWithType: ClientTarget.Alias
  fullName: System.Web.Configuration.ClientTarget.Alias
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar användaragenten alias."
  remarks: "Egenskapen refererar till den `alias` attribut för den `add` element i den `clientTarget` avsnittet i konfigurationsfilen.       Standardinställningar för ASP.NET-konfiguration innehåller följande alias:- `uplevel`, som talar om att skicka HTML och ECMAScript som stöds av Internet Explorer 6.0 och senare versioner av ASP.NET.      - `downlevel`, vilket instruerar ASP.NET att begränsa HTML och skript för att de versioner som stöds av webbläsare tidigare än Internet Explorer 6.0."
  example:
  - "The following code example shows how to get the Alias from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#3](~/add/codesnippet/visualbasic/p-system.web.configurati_91_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#3](~/add/codesnippet/csharp/p-system.web.configurati_91_1.cs)]"
  syntax:
    content: public string Alias { get; }
    return:
      type: System.String
      description: "Namnet som används för att referera till en specifik användaragent."
  overload: System.Web.Configuration.ClientTarget.Alias*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.Properties
  id: Properties
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: Properties
  nameWithType: ClientTarget.Properties
  fullName: System.Web.Configuration.ClientTarget.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.Web.Configuration.ClientTarget.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.UserAgent
  id: UserAgent
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: UserAgent
  nameWithType: ClientTarget.UserAgent
  fullName: System.Web.Configuration.ClientTarget.UserAgent
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar användaragenten identifieringsnamn."
  remarks: "Egenskapen UserAgent refererar till den `userAgent` attribut för den `add` element i den `clientTarget` avsnittet i konfigurationsfilen.       Standardinställningarna för ASP.NET-konfiguration tillåter anpassa sidor för olika versioner av Microsoft Internet Explorer. Mellan dem. du hitta alias `uplevel`, som talar om att skicka klienten HTML och ECMAScript som stöds av Internet Explorer 4.0 och senare, ASP.NET och `downlevel`, vilket instruerar ASP.NET att begränsa HTML och skript som stöds av tidigare versioner än Internet Explorer 4.0."
  example:
  - "The following code example shows how to get the UserAgent from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#4](~/add/codesnippet/visualbasic/p-system.web.configurati_190_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#4](~/add/codesnippet/csharp/p-system.web.configurati_190_1.cs)]"
  syntax:
    content: public string UserAgent { get; }
    return:
      type: System.String
      description: "Användaragenten identifieringsnamn."
  overload: System.Web.Configuration.ClientTarget.UserAgent*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ClientTarget.#ctor(System.String,System.String)
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: ClientTarget(String,String)
  nameWithType: ClientTarget.ClientTarget(String,String)
  fullName: System.Web.Configuration.ClientTarget.ClientTarget(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.ClientTarget.Alias
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Alias
  nameWithType: ClientTarget.Alias
  fullName: System.Web.Configuration.ClientTarget.Alias
- uid: System.Web.Configuration.ClientTarget.Properties
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Properties
  nameWithType: ClientTarget.Properties
  fullName: System.Web.Configuration.ClientTarget.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ClientTarget.UserAgent
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: UserAgent
  nameWithType: ClientTarget.UserAgent
  fullName: System.Web.Configuration.ClientTarget.UserAgent
- uid: System.Web.Configuration.ClientTarget.#ctor*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: ClientTarget
  nameWithType: ClientTarget.ClientTarget
- uid: System.Web.Configuration.ClientTarget.Alias*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Alias
  nameWithType: ClientTarget.Alias
- uid: System.Web.Configuration.ClientTarget.Properties*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Properties
  nameWithType: ClientTarget.Properties
- uid: System.Web.Configuration.ClientTarget.UserAgent*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: UserAgent
  nameWithType: ClientTarget.UserAgent
