### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.WSHttpSecurity
  id: WSHttpSecurity
  children:
  - System.ServiceModel.WSHttpSecurity.#ctor
  - System.ServiceModel.WSHttpSecurity.Message
  - System.ServiceModel.WSHttpSecurity.Mode
  - System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage
  - System.ServiceModel.WSHttpSecurity.ShouldSerializeMode
  - System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport
  - System.ServiceModel.WSHttpSecurity.Transport
  langs:
  - csharp
  name: WSHttpSecurity
  nameWithType: WSHttpSecurity
  fullName: System.ServiceModel.WSHttpSecurity
  type: Class
  summary: "Representerar säkerhetsinställningarna för den <xref href=&quot;System.ServiceModel.WSHttpBinding&quot;> </xref>."
  remarks: "Den <xref:System.ServiceModel.WSHttpBinding>klass är avsedd för interoperation med tjänster som implementerar WS-* specifikationer.</xref:System.ServiceModel.WSHttpBinding> Transportsäkerhet för den här bindningen är Secure Sockets Layer (SSL) via HTTP eller HTTPS."
  syntax:
    content: public sealed class WSHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: WSHttpSecurity()
  nameWithType: WSHttpSecurity.WSHttpSecurity()
  fullName: System.ServiceModel.WSHttpSecurity.WSHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.WSHttpSecurity&quot;> </xref> klass."
  syntax:
    content: public WSHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.WSHttpSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.Message
  id: Message
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: Message
  nameWithType: WSHttpSecurity.Message
  fullName: System.ServiceModel.WSHttpSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Hämtar meddelandenivå säkerhetsinställningarna för den här bindningen."
  remarks: ''
  example:
  - "The following code illustrates use of this property.  \n  \n [!code-cs[c_CreateSecureSession#4](~/add/codesnippet/csharp/p-system.servicemodel.ws_20_1.cs)]"
  syntax:
    content: public System.ServiceModel.NonDualMessageSecurityOverHttp Message { get; set; }
    return:
      type: System.ServiceModel.NonDualMessageSecurityOverHttp
      description: "En <xref href=&quot;System.ServiceModel.NonDualMessageSecurityOverHttp&quot;> </xref> instans.       The default value includes: <>*> with default set to <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>, <>*> is <xref:System.ServiceModel.MessageCredentialType>, <>*> is <>*>, and <xref:System.ServiceModel.MessageSecurityOverHttp.NegotiateServiceCredential*> is <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>.</xref:System.ServiceModel.MessageSecurityOverHttp.NegotiateServiceCredential*></xref:System.ServiceModel.MessageCredentialType>"
  overload: System.ServiceModel.WSHttpSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: WSHttpSecurity.Mode
  fullName: System.ServiceModel.WSHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Anger meddelandet som <xref:System.ServiceModel.SecurityMode>för den här bindningen.</xref:System.ServiceModel.SecurityMode>"
  remarks: "Den här egenskapen anger om inställningarna från den <xref:System.ServiceModel.WSHttpSecurity.Transport%2A>och/eller <xref:System.ServiceModel.WSHttpSecurity.Message%2A>egenskapen buckets kan eller inte börjar gälla.</xref:System.ServiceModel.WSHttpSecurity.Message%2A> </xref:System.ServiceModel.WSHttpSecurity.Transport%2A>"
  example:
  - "The following code sets this property.  \n  \n [!code-cs[c_CreateSecureSession#3](~/add/codesnippet/csharp/p-system.servicemodel.ws_11_1.cs)]"
  syntax:
    content: public System.ServiceModel.SecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.SecurityMode
      description: "Den <xref:System.ServiceModel.SecurityMode>för den här bindningen.</xref:System.ServiceModel.SecurityMode> Standardvärdet är <xref:System.ServiceModel.SecurityMode>.</xref:System.ServiceModel.SecurityMode>"
  overload: System.ServiceModel.WSHttpSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Värdet för uppsättningen läge har inte definierats."
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage
  id: ShouldSerializeMessage
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMessage()
  nameWithType: WSHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Returnerar ett värde som anger om den <xref:System.ServiceModel.WSHttpSecurity.Message*>egenskap har ändrats från sitt standardvärde och ska serialiseras.</xref:System.ServiceModel.WSHttpSecurity.Message*> Det här används av [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] för XAML-integrering."
  syntax:
    content: public bool ShouldSerializeMessage ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <xref:System.ServiceModel.WSHttpSecurity.Message*>egenskapsvärdet måste vara serialiserade, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSHttpSecurity.Message*>"
  overload: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: WSHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Returnerar ett värde som anger om den <xref:System.ServiceModel.WSHttpSecurity.Mode*>egenskap har ändrats från sitt standardvärde och ska serialiseras.</xref:System.ServiceModel.WSHttpSecurity.Mode*> Det här används av [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] för XAML-integrering."
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <xref:System.ServiceModel.WSHttpSecurity.Mode*>egenskapsvärdet måste vara serialiserade, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSHttpSecurity.Mode*>"
  overload: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: WSHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Returnerar ett värde som anger om den <xref:System.ServiceModel.WSHttpSecurity.Transport*>egenskap har ändrats från sitt standardvärde och ska serialiseras.</xref:System.ServiceModel.WSHttpSecurity.Transport*>"
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <xref:System.ServiceModel.WSHttpSecurity.Transport*>egenskapsvärdet måste vara serialiserade, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSHttpSecurity.Transport*>"
  overload: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.Transport
  id: Transport
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: WSHttpSecurity.Transport
  fullName: System.ServiceModel.WSHttpSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Hämtar ett objekt som innehåller transportnivå säkerhetsinställningarna för den här bindningen."
  remarks: "Du kan använda objektet som returneras av den här egenskapen för att ange säkerhetsinställningar för bindningen för transporten."
  example:
  - "The following code sets the client credential type to Windows.  \n  \n```c#  \n// The code uses a shortcut to specify the security mode to Transport.  \nWSHttpBinding b = new WSHttpBinding(SecurityMode.Transport);  \nb.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;  \n```  \n  \n```vb#  \n' The code uses a shortcut to specify the security mode to Transport.  \nDim b As WSHttpBinding = new WSHttpBinding(SecurityMode.Transport)  \nb.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows  \n```"
  syntax:
    content: public System.ServiceModel.HttpTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.HttpTransportSecurity
      description: "Den <xref:System.ServiceModel.HttpTransportSecurity>för den här bindningen.</xref:System.ServiceModel.HttpTransportSecurity>       Standardvärdet innehåller en <> </> *> av <xref:System.ServiceModel.HttpClientCredentialType>och en <> </> *> av <xref href=&quot;System.ServiceModel.HttpProxyCredentialType&quot;> </xref>.</xref:System.ServiceModel.HttpClientCredentialType>"
  overload: System.ServiceModel.WSHttpSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.WSHttpSecurity.#ctor
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: WSHttpSecurity()
  nameWithType: WSHttpSecurity.WSHttpSecurity()
  fullName: System.ServiceModel.WSHttpSecurity.WSHttpSecurity()
- uid: System.ServiceModel.WSHttpSecurity.Message
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSHttpSecurity.Message
  fullName: System.ServiceModel.WSHttpSecurity.Message
- uid: System.ServiceModel.NonDualMessageSecurityOverHttp
  parent: System.ServiceModel
  isExternal: false
  name: NonDualMessageSecurityOverHttp
  nameWithType: NonDualMessageSecurityOverHttp
  fullName: System.ServiceModel.NonDualMessageSecurityOverHttp
- uid: System.ServiceModel.WSHttpSecurity.Mode
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSHttpSecurity.Mode
  fullName: System.ServiceModel.WSHttpSecurity.Mode
- uid: System.ServiceModel.SecurityMode
  parent: System.ServiceModel
  isExternal: true
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: System.ServiceModel.SecurityMode
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage()
  nameWithType: WSHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: WSHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode()
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: WSHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport()
- uid: System.ServiceModel.WSHttpSecurity.Transport
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: WSHttpSecurity.Transport
  fullName: System.ServiceModel.WSHttpSecurity.Transport
- uid: System.ServiceModel.HttpTransportSecurity
  parent: System.ServiceModel
  isExternal: true
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: System.ServiceModel.HttpTransportSecurity
- uid: System.ServiceModel.WSHttpSecurity.#ctor*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: WSHttpSecurity
  nameWithType: WSHttpSecurity.WSHttpSecurity
- uid: System.ServiceModel.WSHttpSecurity.Message*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSHttpSecurity.Message
- uid: System.ServiceModel.WSHttpSecurity.Mode*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSHttpSecurity.Mode
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage
  nameWithType: WSHttpSecurity.ShouldSerializeMessage
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: WSHttpSecurity.ShouldSerializeMode
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: WSHttpSecurity.ShouldSerializeTransport
- uid: System.ServiceModel.WSHttpSecurity.Transport*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: WSHttpSecurity.Transport
