### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.StreamChangeCallback
  id: StreamChangeCallback
  langs:
  - csharp
  name: StreamChangeCallback
  nameWithType: StreamChangeCallback
  fullName: System.Configuration.Internal.StreamChangeCallback
  type: Delegate
  summary: "Representerar en metod för att värdar ska anropas när en dataström med övervakade har ändrats."
  syntax:
    content: public delegate void StreamChangeCallback(string streamName);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
