### YamlMime:ManagedReference
items:
- uid: System.EnvironmentVariableTarget
  id: EnvironmentVariableTarget
  children:
  - System.EnvironmentVariableTarget.Machine
  - System.EnvironmentVariableTarget.Process
  - System.EnvironmentVariableTarget.User
  langs:
  - csharp
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
  type: Enum
  summary: "Anger platsen där en miljövariabel lagras eller hämtas i en set eller get-åtgärd."
  remarks: "Uppräkningen EnvironmentVariableTarget används av vissa överlagringar av den <xref:System.Environment.SetEnvironmentVariable%2A>, <xref:System.Environment.GetEnvironmentVariable%2A>, och <xref:System.Environment.GetEnvironmentVariables%2A>metoder för att ange platsen eller mål, där namnet och värdet för en miljövariabel lagras eller hämta.</xref:System.Environment.GetEnvironmentVariables%2A> </xref:System.Environment.GetEnvironmentVariable%2A> </xref:System.Environment.SetEnvironmentVariable%2A>       Målet kan vara något av tre platser: det miljöblock som är associerade med den aktuella processen, Windows operativsystem registernyckeln har reserverats för miljövariabler som är associerade med den aktuella användaren eller registernyckeln som är reserverade för miljövariabler som är associerade med alla användare på den lokala datorn."
  example:
  - "The following code example demonstrates the EnvironmentVariableTarget enumeration in methods that create, modify, and delete environment variables.  \n  \n [!code-cpp[environment.getsetenvar#1](~/add/codesnippet/cpp/t-system.environmentvari_1.cpp)]\n [!code-vb[environment.getsetenvar#1](~/add/codesnippet/visualbasic/t-system.environmentvari_1.vb)]\n [!code-cs[environment.getsetenvar#1](~/add/codesnippet/csharp/t-system.environmentvari_1.cs)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentVariableTarget
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Machine
  id: Machine
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "Miljövariabeln lagras eller hämtas från den <xref uid=&quot;langword_csharp_HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; name=&quot;HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; href=&quot;&quot;> </xref> nyckel i registret för Windows-operativsystem."
  remarks: "När en användare skapar miljövariabeln i en set-åtgärd, lagrar operativsystemet miljövariabeln i registret, men inte i den aktuella processen. Om alla användare på den lokala datorn startar en ny process, kopierar operativsystemet miljövariabeln från registret till den processen.       När processen avslutas, förstör operativsystemet miljövariabeln i den här processen. Miljövariabeln i registret kvarstår dock förrän en användare tas den bort programmatiskt eller med hjälp av ett verktyg för operativsystemet."
  syntax:
    content: Machine
    return:
      type: System.EnvironmentVariableTarget
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Process
  id: Process
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "Miljövariabeln lagras eller hämtas från det miljöblock som är associerade med den aktuella processen."
  remarks: "Användaren skapar miljövariabeln i en set-åtgärd.       När processen avslutas, förstör operativsystemet miljövariabeln i den här processen."
  syntax:
    content: Process
    return:
      type: System.EnvironmentVariableTarget
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.User
  id: User
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "Miljövariabeln lagras eller hämtas från den <xref uid=&quot;langword_csharp_HKEY_CURRENT_USER\\Environment&quot; name=&quot;HKEY_CURRENT_USER\\Environment&quot; href=&quot;&quot;> </xref> nyckel i registret för Windows-operativsystem."
  remarks: "När användaren skapar miljövariabeln i en set-åtgärd, lagrar operativsystemet miljövariabeln i registret, men inte i den aktuella processen. Om användaren startar en ny process, kopierar operativsystemet miljövariabeln från registret till den processen.       När processen avslutas, förstör operativsystemet miljövariabeln i den här processen. Miljövariabeln i registret kvarstår dock tills användaren raderar den programmässigt eller med hjälp av ett verktyg för operativsystemet."
  syntax:
    content: User
    return:
      type: System.EnvironmentVariableTarget
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.EnvironmentVariableTarget.Machine
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
- uid: System.EnvironmentVariableTarget
  parent: System
  isExternal: false
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.Process
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
- uid: System.EnvironmentVariableTarget.User
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
