### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs
  id: CreatingCookieEventArgs
  children:
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  - System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  - System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  - System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  langs:
  - csharp
  name: CreatingCookieEventArgs
  nameWithType: CreatingCookieEventArgs
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs
  type: Class
  summary: "Tillhandahåller data för den <xref href=&quot;System.Web.ApplicationServices.AuthenticationService.CreatingCookie&quot;> </xref> händelse."
  remarks: "Klassen CreatingCookieEventArgs ger värden till någon <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>händelsehanteraren.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Du kan hämta autentiseringsuppgifter när du skapar en anpassad autentiseringscookie med hjälp av egenskaperna för den här klassen.       Den <xref:System.Web.ApplicationServices.AuthenticationService>klassen aktiverar den <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>händelse när autentiserings-cookie anges när autentiseringsuppgifter har autentiserats.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService> Den <xref:System.Web.ApplicationServices.AuthenticationService>klassen skapas ett CreatingCookieEventArgs-objekt och skickar den till någon <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>händelsehanteraren.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>       Du kan hämta autentiseringsuppgifter via <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A> <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A>, och <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>Egenskaper.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A></xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A> Den <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>egenskapen kan innehålla anpassade värden som du behöver för att autentisera, till exempel ett identifieringsnummer.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> Den <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A>egenskapen anger om cookien för autentisering ska behållas förbi den aktuella sessionen.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A> Ange den <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>egenskapen `true` om du skapar cookien för autentisering, så att den <xref:System.Web.ApplicationServices.AuthenticationService>klassen inte skapar en cookie.</xref:System.Web.ApplicationServices.AuthenticationService> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the CreatingCookieEventArgs object to customize the authentication cookie. The handler saves the value from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> property in the authentication ticket and sets the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A> property to `true` to indicate that the authentication cookie has been created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/t-system.web.application_1_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/t-system.web.application_1_1.asax)]"
  syntax:
    content: 'public class CreatingCookieEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  id: CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Hämtar eller anger ett värde som anger om autentiseringscookien har skapats."
  remarks: "Den <xref:System.Web.ApplicationServices.AuthenticationService>klass kontrollerar CookieIsSet-egenskapen för att avgöra om autentiseringscookien har skapats.</xref:System.Web.ApplicationServices.AuthenticationService> Det här värdet till `true` om du skapar en autentiseringscookie i en händelsehanterare för den <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>händelse.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Om CookieIsSet anges till `false` (standardvärdet) den <xref:System.Web.ApplicationServices.AuthenticationService>klassen skapas en autentiseringscookie, skriver du över alla cookie som du har skapat i hanteraren för den <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>händelse.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The CookieIsSet property is set to `true` after the authentication ticket is created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_11_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_11_1.asax)]"
  syntax:
    content: public bool CookieIsSet { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om autentiseringscookien skapades; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  id: CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Hämtar ytterligare autentisering värden som anges av användaren."
  remarks: "Du kan använda egenskapen CustomCredential för att hämta anpassade värden i autentiseringsbiljetten. Egenskapen CustomCredential innehåller värdet som skickas till den <xref:System.Web.ApplicationServices.AuthenticationService.Login%2A>metoden.</xref:System.Web.ApplicationServices.AuthenticationService.Login%2A> Den här egenskapen används normalt för att skicka anpassade värden som måste verifieras med användarnamn och lösenord, till exempel ett ID-nummer. Om fler än ett värde är lagrat i egenskapen, måste du analysera egenskapen CustomCredential för att hämta värden."
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The value passed in the CustomCredential property is stored in the <xref:System.Web.Security.FormsAuthenticationTicket.UserData%2A> property of the forms authentication ticket.  \n  \n> [!NOTE]\n>  Store the CustomCredential property in a cookie only when you know that the data in the property is not sensitive. Malicious users can access the values in the cookie.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_2_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_2_1.asax)]"
  syntax:
    content: public string CustomCredential { get; }
    return:
      type: System.String
      description: "De anpassade värdena som krävs för autentisering, förutom användarnamn och lösenord."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  id: IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Hämtar ett värde som anger om cookien för autentisering ska behållas utanför den aktuella sessionen."
  remarks: "När du skapar en <xref:System.Web.Security.FormsAuthenticationTicket>objekt du kan använda egenskapen IsPersistent för att ange om autentiseringscookien behålls längre än den aktuella sessionen.</xref:System.Web.Security.FormsAuthenticationTicket>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.IsPersistent%2A> property of the <xref:System.Web.Security.FormsAuthenticationTicket> object is set to the value in the IsPersistent property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_0_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_0_1.asax)]"
  syntax:
    content: public bool IsPersistent { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om cookien ska behållas utanför den aktuella sessionen; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  id: Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Hämtar lösenordet för användaren."
  remarks: "Du kan använda egenskapen lösenord för att hämta lösenordet när du ställer in anpassade värden i autentiseringsbiljetten.      > [!NOTE] > Spara inte värdet för egenskapen lösenord i autentiseringsbiljetten. En obehörig användare kan komma åt cookien och hämta lösenordet trots att cookien krypteras."
  syntax:
    content: public string Password { get; }
    return:
      type: System.String
      description: "Lösenordet som angetts av användaren för autentisering."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  id: UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Hämtar namnet för användaren."
  remarks: "Du kan använda egenskapen UserName för att hämta autentiseringsnamnet på när du ställer in anpassade värden i autentiseringsbiljetten. Normalt anger du den <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>egenskapen för den <xref:System.Web.Security.FormsAuthenticationTicket>objekt till värdet för användarnamn.</xref:System.Web.Security.FormsAuthenticationTicket> </xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A> property is set to the values of the UserName property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_6_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_6_1.asax)]"
  syntax:
    content: public string UserName { get; }
    return:
      type: System.String
      description: "Namnet som angetts av användaren för autentisering."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
