### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig
  id: ClientRemotingConfig
  children:
  - System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  - System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  langs:
  - csharp
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig
  type: Class
  summary: "Definierar en statisk <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>metod som skapar en klient fjärrkommunikation konfigurationsfil för en klient typbiblioteket.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>"
  remarks: "Den <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>metoden används av den <xref:System.EnterpriseServices.Internal.Publish>klassen när ett COM-gränssnitt från en klient typbiblioteket (med filtillägget .tlb).</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> Den <xref:System.EnterpriseServices.Internal.Publish>klassen publicerar COM-gränssnitt i SOAP-aktiverade COM +-programmet.</xref:System.EnterpriseServices.Internal.Publish> En av metodens parametrar är namnet på en sammansättning som innehåller common language runtime (CLR) metadata som <xref:System.EnterpriseServices.Internal.Publish>redan har genererats för klienten typbiblioteket.</xref:System.EnterpriseServices.Internal.Publish>       <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>behöver inte anropas direkt.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> Istället anropa <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>metoden i <xref:System.EnterpriseServices.Internal.Publish>klassen.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       ClientRemotingConfig används internt av .NET Framework. Du behöver inte använda klassen direkt i din kod."
  syntax:
    content: public class ClientRemotingConfig
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Initierar en ny instans av den <xref href=&quot;System.EnterpriseServices.Internal.ClientRemotingConfig&quot;> </xref> klass."
  syntax:
    content: public ClientRemotingConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  id: Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Skapar en klient fjärrkommunikation konfigurationsfil för ett typbibliotek för klienten i SOAP-aktiverade COM +-programmet."
  remarks: "Den statiska Write-metoden anropas av den <xref:System.EnterpriseServices.Internal.Publish>klassen när ett COM-gränssnitt från en klient typbiblioteket (med filtillägget .tlb).</xref:System.EnterpriseServices.Internal.Publish> Den <xref:System.EnterpriseServices.Internal.Publish>klassen publicerar COM-gränssnitt i SOAP-aktiverade COM +-programmet.</xref:System.EnterpriseServices.Internal.Publish>       Skriv behöver inte anropas direkt. Istället anropa <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>metoden i <xref:System.EnterpriseServices.Internal.Publish>klassen.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       Den `BaseUrl` och `VRoot` parametervärden sammanfogas (med en sökväg avgränsare, om det behövs) till formuläret klientelementet `URL` attributvärdet.       Den `AssemblyName` parametern identifierar en sammansättning som innehåller CLR-metadata som <xref:System.EnterpriseServices.Internal.Publish>med hjälp av den <xref:System.EnterpriseServices.Internal.GenerateMetadata>klassen, har redan genererat för klienten typbiblioteket.</xref:System.EnterpriseServices.Internal.GenerateMetadata> </xref:System.EnterpriseServices.Internal.Publish>"
  syntax:
    content: public static bool Write (string DestinationDirectory, string VRoot, string BaseUrl, string AssemblyName, string TypeName, string ProgId, string Mode, string Transport);
    parameters:
    - id: DestinationDirectory
      type: System.String
      description: "Den mapp där du vill skapa konfigurationsfilen."
    - id: VRoot
      type: System.String
      description: "Namnet på den virtuella roten."
    - id: BaseUrl
      type: System.String
      description: "Den grundläggande Webbadressen som innehåller den virtuella roten."
    - id: AssemblyName
      type: System.String
      description: "Visningsnamnet för sammansättningen som innehåller gemensamma metadata för språket CLR (runtime) motsvarar typbiblioteket."
    - id: TypeName
      type: System.String
      description: "Det fullständigt kvalificerade namnet för sammansättningen som innehåller CLR-metadata som motsvarar typbiblioteket."
    - id: ProgId
      type: System.String
      description: "Den programmässiga identifieraren för klassen."
    - id: Mode
      type: System.String
      description: "Aktivering-läge."
    - id: Transport
      type: System.String
      description: "Används inte. Ange <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> för den här parametern."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om klienten fjärrkommunikation konfigurationsfilen skapades; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig.ClientRemotingConfig
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write
  nameWithType: ClientRemotingConfig.Write
