### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  id: AssemblyHashAlgorithm
  children:
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  langs:
  - csharp
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
  type: Enum
  summary: "Anger alla hash-algoritmer som används för hashing filer och för att generera det starkt krypterade namnet."
  remarks: "En `hash function``H` är en transformation som tar ett inkommande `m` och returnerar en sträng med fast storlek, som kallas hash-värdet `h` (det vill säga `h`  =  `H` (`m`)). Hash-funktioner med just den här egenskapen har en mängd allmänna beräkningar använder, men när de används i kryptografiska hash-funktioner väljs vanligtvis att ha några ytterligare egenskaper.       De grundläggande kraven för en kryptografisk hash-funktionen är:-indata kan vara av valfri längd.      -Utdata har en fast längd.      - `H` (`x)` är relativt enkelt att beräkna för alla angivna x.      -   `H` (`x`) is one-way.      - `H` (`x`) är kollision fria.       Hash-värdet representerar koncist längre meddelandet eller dokumentet som beräknades; Det här värdet kallas meddelandesammandraget. Du kan se ett meddelandesammandrag som ett digitalt fingeravtryck av större dokumentet. Exempel på välkända hash-funktioner är MD2 och och SHA."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum AssemblyHashAlgorithm
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  id: MD5
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: MD5
  nameWithType: AssemblyHashAlgorithm.MD5
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Hämtar MD5 message-digest algorithm. MD5 har utvecklats av Rivest 1991. Det i praktiken är MD4 med säkerhetsbälten och det är något långsammare än MD4, ger säkerhet. Algoritmen består av fyra olika Avrundar som har en design som skiljer sig från som MD4. Message digest storlek, samt utfyllnad krav, desamma."
  syntax:
    content: MD5
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  id: None
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: None
  nameWithType: AssemblyHashAlgorithm.None
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "En mask som anger att det finns ingen hashalgoritm. Om du anger <xref uid=&quot;langword_csharp_None&quot; name=&quot;None&quot; href=&quot;&quot;> </xref> för flera modulsammansättningen common language runtime som standard algoritmen SHA1 eftersom flera moduler sammansättningar måste generera ett hash-värde."
  syntax:
    content: None
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  id: SHA1
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA1
  nameWithType: AssemblyHashAlgorithm.SHA1
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "En mask som används för att hämta en version av Secure Hash Algorithm som åtgärdar en opublicerade fel i SHA."
  syntax:
    content: SHA1
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  id: SHA256
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA256
  nameWithType: AssemblyHashAlgorithm.SHA256
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "En mask som används för att hämta en version av Secure Hash Algorithm med en hash-storlek på 256 bitar."
  syntax:
    content: SHA256
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  id: SHA384
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA384
  nameWithType: AssemblyHashAlgorithm.SHA384
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "En mask som används för att hämta en version av Secure Hash Algorithm med en hash-storlek på 384 bitar."
  syntax:
    content: SHA384
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  id: SHA512
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA512
  nameWithType: AssemblyHashAlgorithm.SHA512
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "En mask som används för att hämta en version av Secure Hash Algorithm med en hash-storlek på 512 bitar."
  syntax:
    content: SHA512
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: MD5
  nameWithType: AssemblyHashAlgorithm.MD5
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: None
  nameWithType: AssemblyHashAlgorithm.None
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA1
  nameWithType: AssemblyHashAlgorithm.SHA1
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA256
  nameWithType: AssemblyHashAlgorithm.SHA256
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA384
  nameWithType: AssemblyHashAlgorithm.SHA384
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA512
  nameWithType: AssemblyHashAlgorithm.SHA512
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
