### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  id: SoapEnvelopeProcessingElement
  children:
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement
  nameWithType: SoapEnvelopeProcessingElement
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  type: Class
  summary: "Konfigurerar en tidsgräns som minimeras DOS-attacker genom att avsluta alla förfrågningar som tar längre tid än den <xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*>egenskapsvärde.</xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*>"
  remarks: "Timeout-värdet är markerat på varje anrop till <xref:System.Xml.XmlReader.Read%2A>och <xref:System.Xml.XmlReader.MoveToContent%2A>.</xref:System.Xml.XmlReader.MoveToContent%2A> </xref:System.Xml.XmlReader.Read%2A>"
  syntax:
    content: 'public sealed class SoapEnvelopeProcessingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement()
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Web.Services.Configuration.SoapEnvelopeProcessingElement&quot;> </xref> klass."
  syntax:
    content: public SoapEnvelopeProcessingElement ();
    parameters: []
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement(Int32)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Web.Services.Configuration.SoapEnvelopeProcessingElement&quot;> </xref> klassen med angiven <xref:System.Int32>värde.</xref:System.Int32>"
  syntax:
    content: public SoapEnvelopeProcessingElement (int readTimeout);
    parameters:
    - id: readTimeout
      type: System.Int32
      description: "Värdet för tidsgränsen."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  id: '#ctor(System.Int32,System.Boolean)'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement(Int32,Boolean)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Hämtar eller anger den tillåtna tidsperioden som används för att avgöra om du vill avsluta begäranden skyddar mot DOS-attacker."
  syntax:
    content: public SoapEnvelopeProcessingElement (int readTimeout, bool strict);
    parameters:
    - id: readTimeout
      type: System.Int32
      description: "Väntetiden innan försöket avbryts begäranden till <> </> *> och <> </> *>."
    - id: strict
      type: System.Boolean
      description: "Om du vill utlösa ett undantag om serialiseraren påträffar element eller attribut som fanns inte i det ursprungliga schemat. Mer information finns i <xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*>egenskap.</xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*>"
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  id: IsStrict
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Hämtar eller anger ett värde som anger om du vill utlösa ett undantag om serialiseraren påträffar oväntat element eller attribut."
  remarks: "Ange egenskapen IsStrict till `true` för att bidra till att felsöka interoperation scenarier. Generellt sett om den <xref:System.Xml.Serialization.XmlSerializer>klass som uppfyller ett element eller attribut som den inte förväntar sig den genererar en <xref:System.Xml.Serialization.XmlSerializer.UnknownNode>händelse och fortsätter bearbetningen.</xref:System.Xml.Serialization.XmlSerializer.UnknownNode> </xref:System.Xml.Serialization.XmlSerializer> (Samma sak gäller när den <xref:System.Xml.Serialization.XmlArrayAttribute.Order%2A>, <xref:System.Xml.Serialization.XmlElementAttribute.Order%2A>, eller <xref:System.Xml.Serialization.XmlAnyElementAttribute.Order%2A>Egenskaper används men data skickas i rätt ordning.)</xref:System.Xml.Serialization.XmlAnyElementAttribute.Order%2A> </xref:System.Xml.Serialization.XmlElementAttribute.Order%2A> </xref:System.Xml.Serialization.XmlArrayAttribute.Order%2A> Egenskapen IsStrict `true` instruerar Web-tjänsterna körs tid att hantera händelsen och utlösa en <xref:System.InvalidOperationException>som innehåller en lista över de förväntade element och attribut.</xref:System.InvalidOperationException>      > [!NOTE] > Eftersom undantag inte utlöses för alla oväntade element och attribut, egenskapen IsStrict bör inte förlita sig på utom som felsökningshjälp. Om du exempelvis oväntat `xml:lang` och `xml:space` attribut får inte ge ett undantag."
  syntax:
    content: public bool IsStrict { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om serialiseraren för webbtjänster försöker identifiera oväntat element eller attribut; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standardvärdet är <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  id: ReadTimeout
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Hämtar eller anger den tillåtna tidsperioden som används för att avgöra om du vill avsluta begäranden skyddar mot DOS-attacker."
  syntax:
    content: public int ReadTimeout { get; set; }
    return:
      type: System.Int32
      description: "Väntetiden innan försöket avbryts begäranden till <> </> *> och <> </> *>."
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement()
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement(Int32)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement(Int32,Boolean)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
