### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  id: MessageSecurityOverMsmqElement
  children:
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  type: Class
  summary: "Gör det möjligt att ange på meddelandenivå säkerhetsegenskaper på den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> bindning."
  syntax:
    content: 'public sealed class MessageSecurityOverMsmqElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.MessageSecurityOverMsmqElement&quot;> </xref> klass."
  syntax:
    content: public MessageSecurityOverMsmqElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Anger algoritmsvit som används för säkerhet meddelanden på SOAP-nivå."
  remarks: "<xref:System.ServiceModel.Security.SecurityAlgorithmSuite>definierar en mängd olika algoritmer, till exempel auktorisering, sammanfattad, KeyWrap, signatur, kryptering och KeyDerivation.</xref:System.ServiceModel.Security.SecurityAlgorithmSuite> Den här egenskapen är mest relevant när du arbetar med en plattform som använder en uppsättning algoritmer annat än standardvärdet. Du bör vara medveten om styrkor och svagheter av relevanta algoritmer när du gör ändringar i den här egenskapen."
  syntax:
    content: public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: "Den <xref href=&quot;System.ServiceModel.Security.SecurityAlgorithmSuite&quot;> </xref> för meddelanden som skickas av <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> bindning."
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger den <xref:System.ServiceModel.MessageCredentialType>säkerhetsalternativen för meddelanden som skickas via MSMQ-transport.</xref:System.ServiceModel.MessageCredentialType>"
  remarks: "Den här egenskapen kan anges till ett av följande värden:-ingen: Detta gör att tjänsten samverkar med anonyma klienter. Varken tjänsten eller klienten kräver autentiseringsuppgifter.      -Windows: Detta gör det möjligt för SOAP-utbyte ska vara i en Windows-autentiseringsuppgifter autentiserade kontext. Detta utför alltid Kerberos-autentisering.      -UserName: Detta gör att tjänsten kräver som klienten kan autentiseras med hjälp av autentiseringsuppgifter för ett användarnamn. Dessa autentiseringsuppgifter måste anges med hjälp av <xref:System.ServiceModel.Description.ClientCredentials>klassen.</xref:System.ServiceModel.Description.ClientCredentials>          > [!NOTE]      >   [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] stöder inte skicka ett lösenord sammanfattad eller härledda nycklar med lösenord och använda sådana nycklar för meddelandesäkerhet. Därför [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] tillämpar exchange skyddas när du använder UserName-behörighet. Det här läget kräver att servercertifikatet anges på klientsidan med hjälp av ClientCredential beteende och serviceCertificate.      -Certifikat: Detta gör att tjänsten kräver som klienten kan autentiseras med hjälp av ett certifikat. Autentiseringsuppgifter för klienten i det här fallet måste anges med hjälp av den <xref:System.ServiceModel.Description.ClientCredentials>klass eller ClientCredentials beteende.</xref:System.ServiceModel.Description.ClientCredentials> Tjänsten autentiseringsuppgifter i det här fallet måste anges med hjälp av den <xref:System.ServiceModel.Description.ClientCredentials>klass eller ClientCredentials beteende genom att ange serviceCertificate.</xref:System.ServiceModel.Description.ClientCredentials>      -CardSpace: Detta kan kräva-tjänsten som klienten kan autentiseras med hjälp av en [!INCLUDE[infocard1](~/add/includes/infocard1-md.md)]. ServiceCertiifcate måste tillhandahållas i ClientCredential-beteende.       Certifikat-autentiseringsuppgifter för den `MessageSecurityOverMsmq` gäller endast när säkerhetsläget är inställd på `Both` eller `Message`."
  syntax:
    content: public System.ServiceModel.MessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.MessageCredentialType
      description: "Den <xref:System.ServiceModel.MessageCredentialType>säkerhetsalternativen för meddelanden som skickas via MSMQ-transport.</xref:System.ServiceModel.MessageCredentialType>"
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
- uid: System.ServiceModel.MessageCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: MessageCredentialType
  nameWithType: MessageCredentialType
  fullName: System.ServiceModel.MessageCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
