### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier
  id: IApplicationIdentifier
  children:
  - System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  langs:
  - csharp
  name: IApplicationIdentifier
  nameWithType: IApplicationIdentifier
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier
  type: Interface
  summary: "Definierar en identifierare för programdomäner som en cache-implementering använder för att interagera med en värdmiljö."
  remarks: "En [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] värdmiljö som ASP.NET kan använda gränssnittet IApplicationIdentifier för att definiera strängar som identifierar enskilda programdomäner. Värdmiljön implementerar gränssnittet IApplicationIdentifier. Det här gränssnittet är sedan tillgängliga för <xref:System.Runtime.Caching.ObjectCache>implementeringar via den <xref:System.Runtime.Caching.ObjectCache.Host%2A>egenskapen.</xref:System.Runtime.Caching.ObjectCache.Host%2A> </xref:System.Runtime.Caching.ObjectCache>       En cache-implementering använder den här referensen för att få en identifierare för programdomänen. ASP.NET använda cache-implementeringar program-ID för att konstruera identifierare för cache-prestandaräknare. Detta ger namn för prestanda räknarinstanser som kan särskiljas mellan tillämpningsdomäner när flera programdomäner körs."
  syntax:
    content: public interface IApplicationIdentifier
  implements: []
  platform:
  - net462
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  id: GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  langs:
  - csharp
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
  type: Method
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Hosting
  summary: "Hämtar en identifierare för en tillämpningsdomän."
  remarks: "Metoden GetApplicationId implementeras normalt genom en [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] värdmiljö för att kunna skapa en program-ID för en <xref:System.Runtime.Caching.ObjectCache>implementering.</xref:System.Runtime.Caching.ObjectCache> En <xref:System.Runtime.Caching.ObjectCache>implementeringen använder informationen för att identifiera programdomänen som körs för tillfället.</xref:System.Runtime.Caching.ObjectCache>       ASP.NET använder cachen exempelvis en program-ID för att konstruera identifierare för cache-prestandaräknare. Cachen anropar metoden GetApplicationId som implementeras av värdmiljön och värden returnerar identifieraren. Detta ger namn för prestanda räknarinstanser som kan särskiljas mellan tillämpningsdomäner när flera programdomäner körs."
  syntax:
    content: public string GetApplicationId ();
    parameters: []
    return:
      type: System.String
      description: "En unik identifierare för den aktuella domänen."
  overload: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId
  nameWithType: IApplicationIdentifier.GetApplicationId
