### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.NamedPipeTransportSecurity
  id: NamedPipeTransportSecurity
  children:
  - System.ServiceModel.NamedPipeTransportSecurity.#ctor
  - System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
  langs:
  - csharp
  name: NamedPipeTransportSecurity
  nameWithType: NamedPipeTransportSecurity
  fullName: System.ServiceModel.NamedPipeTransportSecurity
  type: Class
  summary: "Ger egenskaper som styr skyddsnivån för en namngiven pipe."
  remarks: "Den här klassen används av <xref:System.ServiceModel.NetNamedPipeSecurity.Transport%2A>att ställa in transportnivå säkerhetsinställningarna för en bindning.</xref:System.ServiceModel.NetNamedPipeSecurity.Transport%2A>"
  syntax:
    content: public sealed class NamedPipeTransportSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.NamedPipeTransportSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NamedPipeTransportSecurity
  langs:
  - csharp
  name: NamedPipeTransportSecurity()
  nameWithType: NamedPipeTransportSecurity.NamedPipeTransportSecurity()
  fullName: System.ServiceModel.NamedPipeTransportSecurity.NamedPipeTransportSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.NamedPipeTransportSecurity&quot;> </xref> klass."
  syntax:
    content: public NamedPipeTransportSecurity ();
    parameters: []
  overload: System.ServiceModel.NamedPipeTransportSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.NamedPipeTransportSecurity
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurity.ProtectionLevel
  fullName: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Anger skyddet för en namngiven pipe."
  remarks: "Returnerade uppräkningsmedlem anger säkerhetstjänster som krävs för autentiserade dataströmmen.       Giltiga värden är följande:- <xref:System.Net.Security.ProtectionLevel>- <xref:System.Net.Security.ProtectionLevel>- <xref:System.Net.Security.ProtectionLevel></xref:System.Net.Security.ProtectionLevel> </xref:System.Net.Security.ProtectionLevel> </xref:System.Net.Security.ProtectionLevel>"
  syntax:
    content: public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "A <xref href=&quot;System.Net.Security.ProtectionLevel&quot;></xref>. Standardvärdet är <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref>."
  overload: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Värdet är inte ett giltigt <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref>."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.NamedPipeTransportSecurity.#ctor
  parent: System.ServiceModel.NamedPipeTransportSecurity
  isExternal: false
  name: NamedPipeTransportSecurity()
  nameWithType: NamedPipeTransportSecurity.NamedPipeTransportSecurity()
  fullName: System.ServiceModel.NamedPipeTransportSecurity.NamedPipeTransportSecurity()
- uid: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
  parent: System.ServiceModel.NamedPipeTransportSecurity
  isExternal: false
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurity.ProtectionLevel
  fullName: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.NamedPipeTransportSecurity.#ctor*
  parent: System.ServiceModel.NamedPipeTransportSecurity
  isExternal: false
  name: NamedPipeTransportSecurity
  nameWithType: NamedPipeTransportSecurity.NamedPipeTransportSecurity
- uid: System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel*
  parent: System.ServiceModel.NamedPipeTransportSecurity
  isExternal: false
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurity.ProtectionLevel
