### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageability
  id: SettingsManageability
  children:
  - System.Configuration.SettingsManageability.Roaming
  langs:
  - csharp
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
  type: Enum
  summary: "Innehåller värden för att ange vilka tjänster som ska göras tillgängliga till programinställningar."
  remarks: "Ttribute används för att tillämpa inställningar för enskilda program och egenskapsgrupper att visa att speciella, fördefinierade tjänster ska anges för dem. Uppräkningen SettingsManageability Listar de tjänster som är tillgängliga. De flesta av dessa tjänster kommer att tillhandahållas av Windows-operativsystemet."
  syntax:
    content: public enum SettingsManageability
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SettingsManageability.Roaming
  id: Roaming
  parent: System.Configuration.SettingsManageability
  langs:
  - csharp
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gör inställningar för program som ska lagras i centrala användarprofiler. Mer information om centrala användarprofiler finns [isolerad lagring och centrala](http://msdn.microsoft.com/en-us/d3cca593-4521-408d-b323-ea398d226de3)."
  syntax:
    content: Roaming
    return:
      type: System.Configuration.SettingsManageability
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsManageability.Roaming
  parent: System.Configuration.SettingsManageability
  isExternal: false
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
