### YamlMime:ManagedReference
items:
- uid: System.Windows.Input.KeyGestureValueSerializer
  id: KeyGestureValueSerializer
  children:
  - System.Windows.Input.KeyGestureValueSerializer.#ctor
  - System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.KeyGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: KeyGestureValueSerializer
  nameWithType: KeyGestureValueSerializer
  fullName: System.Windows.Input.KeyGestureValueSerializer
  type: Class
  summary: "Konverterar instanser av <xref:System.String>till och från instanser av <xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref>.</xref:System.String>"
  remarks: "Den här klassen används vanligtvis endast genom de <xref:System.Windows.Markup.Primitives.MarkupWriter>för serialisering.</xref:System.Windows.Markup.Primitives.MarkupWriter>      <a name=&quot;xamlTextUsage_KeyGestureValueSerializer&quot;></a>## XAML Text användning"
  syntax:
    content: 'public class KeyGestureValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: KeyGestureValueSerializer()
  nameWithType: KeyGestureValueSerializer.KeyGestureValueSerializer()
  fullName: System.Windows.Input.KeyGestureValueSerializer.KeyGestureValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Initierar en ny instans av den <xref href=&quot;System.Windows.Input.KeyGestureValueSerializer&quot;> </xref> klass."
  syntax:
    content: public KeyGestureValueSerializer ();
    parameters: []
  overload: System.Windows.Input.KeyGestureValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Anger om den angivna <xref:System.String>kan konverteras till en instans av <xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Strängen som ska utvärderas för konvertering."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Kontextinformation som används för konvertering."
    return:
      type: System.Boolean
      description: "Returnerar alltid <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Anger om den angivna <xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref> kan konverteras till ett <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Gest ska utvärderas för konvertering."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Kontextinformation som används för konvertering."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om <code> value </code> kan konverteras till en <xref:System.String>, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Konverterar en <xref:System.String>till en <xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Den sträng som ska konverteras till en <xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref>."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Kontextinformation som används för konvertering."
    return:
      type: System.Object
      description: "En ny instans av <xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref> baserat på den angivna <code> value </code>."
  overload: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Konverterar en instans av <xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref> till <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Gest att konvertera till en sträng."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Kontextinformation som används för konvertering."
    return:
      type: System.String
      description: "En invariant strängrepresentation av det angivna <xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref>."
  overload: System.Windows.Input.KeyGestureValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Input.KeyGestureValueSerializer.#ctor
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: KeyGestureValueSerializer()
  nameWithType: KeyGestureValueSerializer.KeyGestureValueSerializer()
  fullName: System.Windows.Input.KeyGestureValueSerializer.KeyGestureValueSerializer()
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Input.KeyGestureValueSerializer.#ctor*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: KeyGestureValueSerializer
  nameWithType: KeyGestureValueSerializer.KeyGestureValueSerializer
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: KeyGestureValueSerializer.CanConvertFromString
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: KeyGestureValueSerializer.CanConvertToString
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: KeyGestureValueSerializer.ConvertFromString
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertToString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: KeyGestureValueSerializer.ConvertToString
