### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventArgs
  id: SettingChangingEventArgs
  children:
  - System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  - System.Configuration.SettingChangingEventArgs.NewValue
  - System.Configuration.SettingChangingEventArgs.SettingClass
  - System.Configuration.SettingChangingEventArgs.SettingKey
  - System.Configuration.SettingChangingEventArgs.SettingName
  langs:
  - csharp
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs
  fullName: System.Configuration.SettingChangingEventArgs
  type: Class
  summary: "Tillhandahåller data för den <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> händelse."
  remarks: "SettingChangingEventArgs-klassen innehåller data för den <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>händelse som signalerar till att värdet för en egenskap för inställningar av programmet håller på att ändra.</xref:System.Configuration.ApplicationSettingsBase.SettingChanging> De vanligaste källan för den här händelsen är den `get` accessor- <xref:System.Configuration.ApplicationSettingsBase.Item%2A>metoden i <xref:System.Configuration.ApplicationSettingsBase>klassen.</xref:System.Configuration.ApplicationSettingsBase> </xref:System.Configuration.ApplicationSettingsBase.Item%2A>       Eftersom SettingChangingEventArgs är härledd från <xref:System.ComponentModel.CancelEventArgs>, hanteraren har möjlighet att avbryta åtgärden.</xref:System.ComponentModel.CancelEventArgs>"
  syntax:
    content: 'public class SettingChangingEventArgs : System.ComponentModel.CancelEventArgs'
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  id: '#ctor(System.String,System.String,System.String,System.Object,System.Boolean)'
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initierar en instans av den <xref href=&quot;System.Configuration.SettingChangingEventArgs&quot;> </xref> klass."
  remarks: "Konstruktorn SettingChangingEventArgs tilldelar bara värden för parametrar i motsvarande egenskaper i <xref:System.Configuration.SettingChangingEventArgs>klass.</xref:System.Configuration.SettingChangingEventArgs>"
  syntax:
    content: public SettingChangingEventArgs (string settingName, string settingClass, string settingKey, object newValue, bool cancel);
    parameters:
    - id: settingName
      type: System.String
      description: "En <xref:System.String>som innehåller namnet på tillämpningsinställningen.</xref:System.String>"
    - id: settingClass
      type: System.String
      description: "En <xref:System.String>som innehåller en beskrivning av inställning.</xref:System.String> Den här parametern anges ofta till namnet på programgruppen inställningar."
    - id: settingKey
      type: System.String
      description: "En <xref:System.String>som innehåller programmet inställningar nyckel.</xref:System.String>"
    - id: newValue
      type: System.Object
      description: "En <xref:System.Object>som innehåller det nya värdet som ska tilldelas programmet inställningsegenskapen.</xref:System.Object>"
    - id: cancel
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>avbryta händelsen. Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.SettingChangingEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  id: NewValue
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar det nya värdet som tilldelas till inställningsegenskapen program."
  remarks: "Den faktiska typen för egenskapen NewValue ska vara kompatibel med egenskapen settings har angetts. Dessa är tillgängliga via <xref:System.Configuration.SettingsProperty.PropertyType%2A>-egenskapen för <xref:System.Configuration.SettingsProperty>klassen.</xref:System.Configuration.SettingsProperty> </xref:System.Configuration.SettingsProperty.PropertyType%2A>"
  syntax:
    content: public object NewValue { get; }
    return:
      type: System.Object
      description: "En <xref:System.Object>som innehåller det nya värdet som ska tilldelas programmet inställningsegenskapen.</xref:System.Object>"
  overload: System.Configuration.SettingChangingEventArgs.NewValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  id: SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar programkategori inställningar för egenskapen."
  remarks: "Samtliga programinställningar tillhör en grupp för inställningar av programmet. Gruppnamnet kan explicit tillhandahållas av pynta klassen med en <xref:System.Configuration.SettingsGroupNameAttribute>annars en genereras med namnet på inställningar wrapper klass.</xref:System.Configuration.SettingsGroupNameAttribute>"
  syntax:
    content: public string SettingClass { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som innehåller en beskrivning av inställning.</xref:System.String> Den här parametern anges vanligtvis till namnet på programgruppen inställningar."
  overload: System.Configuration.SettingChangingEventArgs.SettingClass*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  id: SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar programmet inställningar nyckeln som associeras med egenskapen."
  remarks: "Varje inställningar wrapper-klass som härletts från <xref:System.Configuration.ApplicationSettingsBase>, har en tillhörande inställningar nyckel, vilken är en sträng som hjälper till att undvika tvetydigheten olika instanser av samma wrapper i ett enda program.</xref:System.Configuration.ApplicationSettingsBase> Eftersom varje vinjettklass definierar en uppsättning egenskaper som representerar programinställningar, hjälper inställningar nyckeln på liknande sätt dig undvika tvetydigheten deras användning."
  syntax:
    content: public string SettingKey { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som innehåller programmet inställningar nyckel.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingKey*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  id: SettingName
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar namnet på inställningen som är associerade med programmet inställningsegenskapen."
  remarks: "Vanligtvis inställningar wrapper klassen härleds från <xref:System.Configuration.ApplicationSettingsBase>, skapas så att namnet på programmet inställningsegenskapen är samma som dess associerade program-inställning.</xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: public string SettingName { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som innehåller namnet på tillämpningsinställningen.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
- uid: System.Configuration.SettingChangingEventArgs.#ctor*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs
- uid: System.Configuration.SettingChangingEventArgs.NewValue*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
