### YamlMime:ManagedReference
items:
- uid: System.Configuration.InfiniteIntConverter
  id: InfiniteIntConverter
  children:
  - System.Configuration.InfiniteIntConverter.#ctor
  - System.Configuration.InfiniteIntConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.InfiniteIntConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: InfiniteIntConverter
  nameWithType: InfiniteIntConverter
  fullName: System.Configuration.InfiniteIntConverter
  type: Class
  summary: "Konverterar mellan en sträng och standard oändlig eller heltalsvärde."
  remarks: "Den här typen, precis som alla andra konverterare konfigurationerna, konverterar strängar påträffades i konfigurationsfilen till och från egenskaperna för relaterade strikt typkontroll.       I synnerhet konverterar klassen InfiniteIntConverter strängvärden som tilldelats en konfigurationsegenskap till heltalsvärden och vice versa. Om egenskapen har ett strängvärde &quot;som&quot;, konverteras det här värdet till <xref:System.Int32>och vice versa.</xref:System.Int32>       Den här konverteraren används med heltal typer. Oändlig värdet sparas som <xref:System.Int32>.</xref:System.Int32>"
  example:
  - "The following code example shows how to use the InfiniteIntConverter when applied to a custom section property.  \n  \n [!code-cs[System.Configuration.ConfigurationConvertersCustomSection#5](~/add/codesnippet/csharp/t-system.configuration.i_7_1.cs)]\n [!code-vb[System.Configuration.ConfigurationConvertersCustomSection#5](~/add/codesnippet/visualbasic/t-system.configuration.i_7_1.vb)]"
  syntax:
    content: 'public sealed class InfiniteIntConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.InfiniteIntConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.InfiniteIntConverter
  langs:
  - csharp
  name: InfiniteIntConverter()
  nameWithType: InfiniteIntConverter.InfiniteIntConverter()
  fullName: System.Configuration.InfiniteIntConverter.InfiniteIntConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.InfiniteIntConverter&quot;> </xref> klass."
  remarks: "Normalt sett kan du använda konverteraren-typer som tillhandahålls av systemet. Den enda gången som du behöver använda konstruktorn InfiniteIntConverter är när du skapar egna konvertering."
  syntax:
    content: public InfiniteIntConverter ();
    parameters: []
  overload: System.Configuration.InfiniteIntConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteIntConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteIntConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteIntConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteIntConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konverterar en <xref:System.String>till <xref:System.Int32>.</xref:System.Int32> </xref:System.String>"
  remarks: "Systemet använder metoden ConvertFrom vid läsning från en konfigurationsfil för att konvertera ett <xref:System.String>värde till <xref:System.Int32>.</xref:System.Int32> </xref:System.String>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Den <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> objekt som används för typkonverteringar."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Den <xref:System.Globalization.CultureInfo>objektet som används under konverteringen.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "Den <xref:System.String>objekt som ska konverteras.</xref:System.String>"
    return:
      type: System.Object
      description: "Den <xref:System.Int32.MaxValue>, om den <code> data </code> parametern är den <xref:System.String>&quot;oändlig&quot;, i annat fall den <xref:System.Int32>som representerar den <code> data </code> heltal för parametern.</xref:System.Int32> </xref:System.String> </xref:System.Int32.MaxValue>"
  overload: System.Configuration.InfiniteIntConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteIntConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteIntConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteIntConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteIntConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konverterar en <xref:System.Int32>Om du vill <xref:System.String>.</xref:System.String> </xref:System.Int32>"
  remarks: "Systemet använder ConvertTo-metoden när du skriver till en konfigurationsfil för att konvertera ett <xref:System.Int32>till <xref:System.String>.</xref:System.String> </xref:System.Int32>"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Den <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> objekt som används för typkonverteringar."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Den <xref:System.Globalization.CultureInfo>objektet som används under konverteringen.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "Värdet som ska konverteras till."
    - id: type
      type: System.Type
      description: "Konvertera till typen."
    return:
      type: System.Object
      description: "Den <xref:System.String>&quot;oändlig&quot; om den <code> value </code> är <xref:System.Int32.MaxValue>, annars den <xref:System.String>som representerar den <code> value </code> parameter.</xref:System.String> </xref:System.Int32.MaxValue> </xref:System.String>"
  overload: System.Configuration.InfiniteIntConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.InfiniteIntConverter.#ctor
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: InfiniteIntConverter()
  nameWithType: InfiniteIntConverter.InfiniteIntConverter()
  fullName: System.Configuration.InfiniteIntConverter.InfiniteIntConverter()
- uid: System.Configuration.InfiniteIntConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteIntConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteIntConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.InfiniteIntConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteIntConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteIntConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.InfiniteIntConverter.#ctor*
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: InfiniteIntConverter
  nameWithType: InfiniteIntConverter.InfiniteIntConverter
- uid: System.Configuration.InfiniteIntConverter.ConvertFrom*
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: InfiniteIntConverter.ConvertFrom
- uid: System.Configuration.InfiniteIntConverter.ConvertTo*
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: ConvertTo
  nameWithType: InfiniteIntConverter.ConvertTo
