### YamlMime:ManagedReference
items:
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  id: PropertyValueSource
  children:
  - System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  langs:
  - csharp
  name: PropertyValueSource
  nameWithType: PropertyValueSource
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  type: Class
  summary: "Representerar ett värde för egenskapen ursprung."
  remarks: "Exempel på egenskapen värdet källor kan innehålla värden, överordnade mallvärden, standardvärden, implicit stil referenser, värdena för utlösare och andra."
  example:
  - '[!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]'
  syntax:
    content: public abstract class PropertyValueSource
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  id: '#ctor'
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  langs:
  - csharp
  name: PropertyValueSource()
  nameWithType: PropertyValueSource.PropertyValueSource()
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource.PropertyValueSource()
  type: Constructor
  assemblies:
  - System.Activities.Presentation
  namespace: System.Activities.Presentation.PropertyEditing
  summary: "Skapar en ny instans av den <xref href=&quot;System.Activities.Presentation.PropertyEditing.PropertyValueSource&quot;> </xref> klass."
  syntax:
    content: protected PropertyValueSource ();
    parameters: []
  overload: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  isExternal: false
  name: PropertyValueSource()
  nameWithType: PropertyValueSource.PropertyValueSource()
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource.PropertyValueSource()
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor*
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  isExternal: false
  name: PropertyValueSource
  nameWithType: PropertyValueSource.PropertyValueSource
