### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlReaderSettings
  id: XamlXmlReaderSettings
  children:
  - System.Xaml.XamlXmlReaderSettings.#ctor
  - System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  - System.Xaml.XamlXmlReaderSettings.CloseInput
  - System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  - System.Xaml.XamlXmlReaderSettings.XmlLang
  - System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  langs:
  - csharp
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
  type: Class
  summary: "Anger bearbetningsregler eller inställningar för den <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> XAML reader implementering."
  syntax:
    content: 'public class XamlXmlReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initierar en ny instans av den <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> klass."
  syntax:
    content: public XamlXmlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  id: '#ctor(System.Xaml.XamlXmlReaderSettings)'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initierar en ny instans av den <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> klassen genom att kopiera inställningar från en befintlig <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> objekt."
  syntax:
    content: public XamlXmlReaderSettings (System.Xaml.XamlXmlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlXmlReaderSettings
      description: "Den befintliga <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> objekt att kopiera."
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  id: CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Hämtar eller anger ett värde som anger om den underliggande dataströmmen eller text läsaren ska stängas när det <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> är stängd."
  syntax:
    content: public bool CloseInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den underliggande dataströmmen eller läsare bör stängas när det <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> är stängd, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standardvärdet är <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlReaderSettings.CloseInput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  id: SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Hämtar eller anger ett värde som avgör om läsaren ska skilja sig från standard <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> beteendet för hur markup kompatibilitet innehåll ska bearbetas."
  remarks: "Standard hantera beteendet för XML-koden kompatibilitet i <xref:System.Xaml.XamlXmlReader>är att den <xref:System.Xaml.XamlXmlReader>enligt initieringen kapslas i en klass som skapats internt helper.</xref:System.Xaml.XamlXmlReader> </xref:System.Xaml.XamlXmlReader> Hjälparklassen läser koden kompatibilitet noder separat och träder noder baserat på markup kompatibilitet för schema-kontexten.       Föreslagna scenarier för att ange SkipXmlCompatibilityProcessing till `true` är:-du vill behålla markup kompatibilitet innehåll i den primära XAML-dataströmmen.      -Du har redan bearbetats markup kompatibilitet eftersom du använder en läsare som kan bearbeta markup kompatibilitet innehåll infogad.      -Du välja att ignorera XML-kompatibilitet konventioner implementeringen XAML-läsaren skäl av prestanda."
  syntax:
    content: public bool SkipXmlCompatibilityProcessing { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den initierande läsaren används direkt, vilket innebär att XML-kod för kompatibilitet behandlas som en del av den huvudsakliga dataströmmen och kompatibilitet anses inte. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Om standardbeteendet används, som bearbetar XML-kompatibilitet separat. Standardvärdet är <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  id: XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Hämtar eller anger det språk som anger värdet för läsaren kan uppgradera till skrivare som skriver <xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;> </xref> attribut i noderna."
  remarks: "Anroparen ansvarar för att kontrollera att strängen som du anger är lämplig för `xml:lang` användning."
  syntax:
    content: public string XmlLang { get; set; }
    return:
      type: System.String
      description: "Strängen som ska användas för möjliga <xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;> </xref> utdata som baseras på läsaren."
  overload: System.Xaml.XamlXmlReaderSettings.XmlLang*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  id: XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Hämtar eller anger ett värde som avgör om XAML-läsaren instruerar en XAML-skrivare för att skriva <xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;> </xref> attribut i noderna. Eventuellt det beteendet skickas informationen via delade XAML-schemat kontext."
  remarks: "Begrepp för XML-blanksteg är inte robust ska gälla för XAML och vanligtvis ignoreras av XAML läsare."
  syntax:
    content: public bool XmlSpacePreserve { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om skrivare som bearbetar XAML-nodström kan skriva `xml:space=&quot;preserve&quot;` i utdata; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> om <xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;> </xref> attribut kan inte skrivas i noderna."
  overload: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
- uid: System.Xaml.XamlXmlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
- uid: System.Xaml.XamlXmlReaderSettings.#ctor*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
