### YamlMime:ManagedReference
items:
- uid: System.Configuration.InfiniteTimeSpanConverter
  id: InfiniteTimeSpanConverter
  children:
  - System.Configuration.InfiniteTimeSpanConverter.#ctor
  - System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: InfiniteTimeSpanConverter
  nameWithType: InfiniteTimeSpanConverter
  fullName: System.Configuration.InfiniteTimeSpanConverter
  type: Class
  summary: "Konverterar mellan en sträng och standard oändlig <xref:System.TimeSpan>värde.</xref:System.TimeSpan>"
  remarks: "Den här typen, precis som alla andra konverterare konfigurationerna, konverterar strängar påträffades i konfigurationsfilen till och från egenskaperna för relaterade strikt typkontroll.       I synnerhet InfiniteTimeSpanConverter konverterar den <xref:System.String>värdet &quot;oändliga&quot; tilldelas en konfigurationsegenskap till standard oändliga <xref:System.TimeSpan>och vice versa.</xref:System.TimeSpan> </xref:System.String> Oändligt <xref:System.TimeSpan>värdet representeras av den <xref:System.TimeSpan>uppräkningsvärdet.</xref:System.TimeSpan> </xref:System.TimeSpan>       Den här konverteraren används med <xref:System.TimeSpan>Egenskaper.</xref:System.TimeSpan> Ett oändligt värde sparas som &quot;oändlig&quot; sträng."
  example:
  - "The following code example shows how to define a custom section property that uses the InfiniteTimeSpanConverter class.  \n  \n For the complete example code that implements the custom section, refer to the <xref:System.Configuration.ConfigurationConverterBase> class.  \n  \n [!code-cs[System.Configuration.ConfigurationConvertersCustomSection#3](~/add/codesnippet/csharp/t-system.configuration.i_6_1.cs)]\n [!code-vb[System.Configuration.ConfigurationConvertersCustomSection#3](~/add/codesnippet/visualbasic/t-system.configuration.i_6_1.vb)]  \n  \n The following example code shows how to access the previous custom section property.  \n  \n [!code-cs[System.Configuration.InfiniteTimeSpanConverter#1](~/add/codesnippet/csharp/t-system.configuration.i_6_2.cs)]\n [!code-vb[System.Configuration.InfiniteTimeSpanConverter#1](~/add/codesnippet/visualbasic/t-system.configuration.i_6_2.vb)]  \n  \n The following is a configuration excerpt as used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n    </configSections>  \n    <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\" timeDelay=\"infinite\"/>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class InfiniteTimeSpanConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: System.Configuration.InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.InfiniteTimeSpanConverter&quot;> </xref> klass."
  remarks: "Normalt sett kan du använda konverteraren-typer som tillhandahålls av systemet. Den enda gången som du behöver använda konstruktorn InfiniteTimeSpanConverter är när du skapar egna konvertering."
  syntax:
    content: public InfiniteTimeSpanConverter ();
    parameters: []
  overload: System.Configuration.InfiniteTimeSpanConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konverterar en <xref:System.String>till <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  remarks: "Systemet använder metoden ConvertFrom vid läsning från en konfigurationsfil för att konvertera ett <xref:System.String>värde eller <xref:System.TimeSpan> <xref:System.String>&quot;oändlig&quot; <xref:System.TimeSpan.MaxValue>.</xref:System.TimeSpan.MaxValue> </xref:System.String> </xref:System.TimeSpan> </xref:System.String>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Den <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> objekt som används för typkonverteringar."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Den <xref:System.Globalization.CultureInfo>objektet som används under konverteringen.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "Den <xref:System.String>objekt som ska konverteras.</xref:System.String>"
    return:
      type: System.Object
      description: "Den <xref:System.TimeSpan.MaxValue>, om den <code> data </code> parametern är den <xref:System.String>oändlig, i annat fall den <xref:System.TimeSpan>som representerar den <code> data </code> parameter i minuter.</xref:System.TimeSpan> </xref:System.String> </xref:System.TimeSpan.MaxValue>"
  overload: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konverterar en <xref:System.TimeSpan>till <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  remarks: "Systemet använder ConvertTo-metoden när du skriver ett attribut till en konfigurationsfil för att konvertera en <xref:System.TimeSpan>objekt-ett <xref:System.String>objekt.</xref:System.String> </xref:System.TimeSpan>       Systemet använder ConvertTo-metoden när du skriver till en konfigurationsfil för att konvertera ett <xref:System.TimeSpan>värde eller <xref:System.TimeSpan.MaxValue>till en <xref:System.String>.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Den <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> objekt som används för typkonverteringar."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Den <xref:System.Globalization.CultureInfo>används under objektet konverteringen.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "Värdet som ska konverteras."
    - id: type
      type: System.Type
      description: "Typen för konvertering."
    return:
      type: System.Object
      description: "Den <xref:System.String>&quot;oändlig&quot;, om den <code> value </code> parametern är <xref:System.TimeSpan.MaxValue>, annars den <xref:System.String>som representerar den <code> value </code> parameter i minuter.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.String>"
  overload: System.Configuration.InfiniteTimeSpanConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: System.Configuration.InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: InfiniteTimeSpanConverter
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertTo
  nameWithType: InfiniteTimeSpanConverter.ConvertTo
