### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  id: NamedPipeConnectionPoolSettingsElement
  children:
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettingsElement
  nameWithType: NamedPipeConnectionPoolSettingsElement
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  type: Class
  summary: "Representerar en konfigurationselement som anger ytterligare inställningar för anslutningspool för en namngiven Pipe-transport. Den här klassen kan inte ärvas."
  syntax:
    content: 'public sealed class NamedPipeConnectionPoolSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettingsElement()
  nameWithType: NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement&quot;> </xref> klass."
  syntax:
    content: public NamedPipeConnectionPoolSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  id: GroupName
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger en sträng som definierar namnet på anslutningspoolen som används för utgående kanaler"
  remarks: "I direktuppspelat läge som anslutningar inte delas, vilket innebär att anslutningspooler är inaktiverad. Standardvärdet är &quot;default&quot; sträng. Du kan ändra det här värdet om du vill isolera anslutningar för en viss klient i separata grupper."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "En sträng som definierar namnet på anslutningspoolen som används för utgående kanaler"
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger den maximala tid som anslutningen kan vara inaktiv innan den avbryts."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Ett positivt <xref:System.TimeSpan>som anger den maximala tid som anslutningen kan vara inaktiv innan den avbryts.</xref:System.TimeSpan> Standardvärdet är 00:02:00."
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger det maximala antalet anslutningar till en fjärrslutpunkten som initieras av tjänsten."
  remarks: "Anslutningar som överskrider gränsen köas tills ett utrymme under gräns blir tillgänglig. Den här egenskapen begränsar varaktigheten där anslutningar som finns kvar i kö innan ett undantag.       Den här egenskapen begränsar antalet samtidiga aktiva anslutningar från klienten till en viss tjänstslutpunkt. Om det här värdet har överskridits genom att mer aktiva klientanslutningar verka tjänsten svarar inte på klienten. I det här fallet bör det här värdet justeras så för att överskrider det maximala antalet förväntade samtidiga anslutningar till en viss slutpunkt."
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "Ett positivt heltal som anger det maximala antalet anslutningar till en fjärrslutpunkten som initieras av tjänsten. Standardvärdet är 10."
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: NamedPipeConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: NamedPipeConnectionPoolSettingsElement()
  nameWithType: NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: NamedPipeConnectionPoolSettingsElement
  nameWithType: NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettingsElement.GroupName
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettingsElement.IdleTimeout
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeConnectionPoolSettingsElement.Properties
