### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigClientHost
  id: IInternalConfigClientHost
  children:
  - System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  - System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  - System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  langs:
  - csharp
  name: IInternalConfigClientHost
  nameWithType: IInternalConfigClientHost
  fullName: System.Configuration.Internal.IInternalConfigClientHost
  type: Interface
  summary: "Definierar gränssnitt som gör att internt .NET Framework-infrastrukturen att anpassa konfigurationen."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigClientHost
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  id: GetExeConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetExeConfigPath()
  nameWithType: IInternalConfigClientHost.GetExeConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar sökvägen till programmets konfigurationsfil."
  syntax:
    content: public string GetExeConfigPath ();
    parameters: []
    return:
      type: System.String
      description: "En sträng som representerar sökvägen till programmets konfigurationsfil."
  overload: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  id: GetLocalUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetLocalUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar en sträng som representerar sökvägen till konfigurationsfilen kända lokal användare."
  syntax:
    content: public string GetLocalUserConfigPath ();
    parameters: []
    return:
      type: System.String
      description: "En sträng som representerar sökvägen till konfigurationsfilen kända lokal användare."
  overload: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  id: GetRoamingUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetRoamingUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar en sträng som representerar sökvägen för kända centrala användarkonfigurationsfiler."
  syntax:
    content: public string GetRoamingUserConfigPath ();
    parameters: []
    return:
      type: System.String
      description: "En sträng som representerar sökvägen för kända centrala användarkonfigurationsfiler."
  overload: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  id: IsExeConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsExeConfig(String)
  nameWithType: IInternalConfigClientHost.IsExeConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar ett värde som anger om en sökväg till konfigurationsfilen är samma som en sökväg till konfigurationsfilen kända program."
  syntax:
    content: public bool IsExeConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "En sträng som representerar sökvägen till programmets konfigurationsfil."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om en sträng som representerar en konfigurationssökvägen är detsamma som en sökväg till programmets konfigurationsfil; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> om en sträng som representerar en sökväg inte är samma som en sökväg till programmets konfigurationsfil."
  overload: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  id: IsLocalUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsLocalUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar ett värde som anger om en sökväg till konfigurationsfilen är densamma som sökvägen för konfigurationsfilen för kända lokala användare."
  syntax:
    content: public bool IsLocalUserConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "En sträng som representerar sökvägen till programmets konfigurationsfil."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om en sträng som representerar en konfigurationssökvägen är detsamma som en sökväg till en känd lokala användarkonfigurationsfiler; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  id: IsRoamingUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsRoamingUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Returnerar ett värde som anger om en sökväg till konfigurationsfilen är densamma som sökvägen för kända centrala konfigurationsfilen."
  syntax:
    content: public bool IsRoamingUserConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "En sträng som representerar sökvägen för en programkonfigurationsfil."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om en sträng som representerar en konfigurationssökvägen är detsamma som en sökväg till en känd centrala användarkonfigurationsfiler; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetExeConfigPath()
  nameWithType: IInternalConfigClientHost.GetExeConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetLocalUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath()
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetRoamingUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath()
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsExeConfig(String)
  nameWithType: IInternalConfigClientHost.IsExeConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsLocalUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(String)
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsRoamingUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(String)
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetExeConfigPath
  nameWithType: IInternalConfigClientHost.GetExeConfigPath
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetLocalUserConfigPath
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetRoamingUserConfigPath
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsExeConfig
  nameWithType: IInternalConfigClientHost.IsExeConfig
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsLocalUserConfig
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsRoamingUserConfig
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig
