### YamlMime:ManagedReference
items:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  id: ITransformerConfigurationControl
  children:
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  langs:
  - csharp
  name: ITransformerConfigurationControl
  nameWithType: ITransformerConfigurationControl
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  type: Interface
  summary: "Definierar kontraktet en kontroll som implementerar för att fungera som en Konfigurationskontroll för en transformator i en webbdelar-anslutning."
  remarks: "En Konfigurationskontroll kan visas när en transformator kräver att en användare att konfigurera den. Konfigurationskontrollen ger ett användargränssnitt (UI) som tillåter användaren att välja vilka värden omvandlas. Den återges i en zon för anslutningar. Den <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>metoden returnerar en Konfigurationskontroll.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>       Du kan åsidosätta den <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A>metoden när dina transformatorn kräver en anpassad UI.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A> Konfigurationskontrollen måste implementera ITransformerConfigurationControl-gränssnittet, som innehåller den <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled>och <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded>händelser.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded> </xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled> Dessa händelser inträffar när en transformator kontroll inte har konfigurerats eller konfigurerats korrekt, respektive."
  syntax:
    content: public interface ITransformerConfigurationControl
  implements: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  id: Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Inträffar när transformatorn konfigurationen inte har slutförts."
  remarks: "Kontrollen webbdelar som implementerar <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>genererar den här händelsen när en transformator konfiguration inte är klar eftersom användaren avbröt konfigurationen eller konfigurationen inte kunde utföras.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Cancelled;
    return:
      type: System.EventHandler
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  id: Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Inträffar när transformatorn konfigurationen har slutförts."
  remarks: "Kontrollen webbdelar som implementerar <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>genererar den här händelsen när en transformator-konfigurationen har slutförts.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Succeeded;
    return:
      type: System.EventHandler
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
- uid: System.EventHandler
  parent: System
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
