### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidator
  id: TimeSpanValidator
  children:
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  - System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  - System.Configuration.TimeSpanValidator.Validate(System.Object)
  langs:
  - csharp
  name: TimeSpanValidator
  nameWithType: TimeSpanValidator
  fullName: System.Configuration.TimeSpanValidator
  type: Class
  summary: "Innehåller validering av en <xref:System.TimeSpan>objektet.</xref:System.TimeSpan>"
  remarks: "Klassen TimeSpanValidator används för att säkerställa att en <xref:System.TimeSpan>objekt som uppfyller specifika villkor.</xref:System.TimeSpan> Den <xref:System.Configuration.TimeSpanValidator.%23ctor%2A>konstruktor med två parametrar säkerställer att både minimi- och maximalt <xref:System.TimeSpan>värdet följs.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator.%23ctor%2A> Den <xref:System.Configuration.TimeSpanValidator.%23ctor%2A>konstruktor med tre parametrar kontrollerar både minimum och maximum <xref:System.TimeSpan>värden, samt om verifiering intervallet är exklusiva.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator.%23ctor%2A> Den <xref:System.Configuration.TimeSpanValidator.%23ctor%2A>konstruktor med fyra parametrar kontrollerar föregående tre parametrar och även kontrollerar om den <xref:System.TimeSpan>värde är lika med ett visst antal sekunder.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator.%23ctor%2A>       Den <xref:System.Configuration.TimeSpanValidator.CanValidate%2A>metoden avgör om objekttypen verifieras matchar den förväntade typen.</xref:System.Configuration.TimeSpanValidator.CanValidate%2A> Det objekt som verifieras skickas som en parameter för den <xref:System.Configuration.TimeSpanValidator.Validate%2A>metoden.</xref:System.Configuration.TimeSpanValidator.Validate%2A>"
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator type.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#1](~/add/codesnippet/csharp/t-system.configuration.t_2_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#1](~/add/codesnippet/visualbasic/t-system.configuration.t_2_1.vb)]"
  syntax:
    content: 'public class TimeSpanValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  id: '#ctor(System.TimeSpan,System.TimeSpan)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> klass, utifrån de angivna parametrarna."
  remarks: "När konstruktorn TimeSpanValidator med två parametrar används den <xref:System.Configuration.TimeSpanValidator>objektet kontrollerar att en <xref:System.TimeSpan>värde som stämmer överens med ett visst intervall.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator>"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "En <xref:System.TimeSpan>objekt som anger den minsta tid kan valideras.</xref:System.TimeSpan>"
    - id: maxValue
      type: System.TimeSpan
      description: "En <xref:System.TimeSpan>objekt som anger den maximala tiden kan valideras.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> klass, utifrån de angivna parametrarna."
  remarks: "Konstruktorn TimeSpanValidator kontrollerar både minimum och maximum <xref:System.TimeSpan>värden, samt om verifiering intervallet är exklusiva.</xref:System.TimeSpan> När den `rangeIsExclusive` parametern anges till `true`, <xref:System.TimeSpan>värdet får inte vara mellan den `minValue` och `maxValue` värden.</xref:System.TimeSpan>"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "En <xref:System.TimeSpan>objekt som anger den minsta tid kan valideras.</xref:System.TimeSpan>"
    - id: maxValue
      type: System.TimeSpan
      description: "En <xref:System.TimeSpan>objekt som anger den maximala tiden kan valideras.</xref:System.TimeSpan>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "En <xref:System.Boolean>värde som anger om validering intervallet är exklusiva.</xref:System.Boolean>"
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> klass, utifrån de angivna parametrarna."
  remarks: "När den `resolutionInSeconds` parameter har angetts i <xref:System.TimeSpan>objekt som verifieras måste vara lika med det här värdet valideras.</xref:System.TimeSpan>"
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#2](~/add/codesnippet/csharp/5fd5fd48-b5cd-41a3-9e7a-_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#2](~/add/codesnippet/visualbasic/5fd5fd48-b5cd-41a3-9e7a-_1.vb)]"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive, long resolutionInSeconds);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "En <xref:System.TimeSpan>objekt som anger den minsta tid kan valideras.</xref:System.TimeSpan>"
    - id: maxValue
      type: System.TimeSpan
      description: "En <xref:System.TimeSpan>objekt som anger den maximala tiden kan valideras.</xref:System.TimeSpan>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "En <xref:System.Boolean>värde som anger om validering intervallet är exklusiva.</xref:System.Boolean>"
    - id: resolutionInSeconds
      type: System.Int64
      description: "Ett <xref:System.Int64>värde som anger ett antal sekunder.</xref:System.Int64>"
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "<code>resolutionInSeconds</code> is less than <xref uid=\"langword_csharp_0\" name=\"0\" href=\"\"></xref>.  \n  \n \\- or -  \n  \n <code>minValue</code> is greater than <code>maxValue</code>."
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Anger typen av objekt kan verifieras."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#3](~/add/codesnippet/csharp/m-system.configuration.t_1_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#3](~/add/codesnippet/visualbasic/m-system.configuration.t_1_1.vb)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Typen av objekt."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <code> type </code> parametern matchar en <xref:System.TimeSpan>värdet; annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Anger om värdet för ett objekt är giltig."
  remarks: "Den <xref:System.Configuration.TimeSpanValidator>objektet innehåller reglerna som är nödvändiga för att validera en <xref:System.TimeSpan>objektet.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator> Reglerna upprättas när en instans av den <xref:System.Configuration.TimeSpanValidator>klassen skapas.</xref:System.Configuration.TimeSpanValidator> Objektet som har skickats som en parameter för Validate-metoden."
  example:
  - "The following code example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#4](~/add/codesnippet/csharp/m-system.configuration.t_2_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#4](~/add/codesnippet/visualbasic/m-system.configuration.t_2_1.vb)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Värdet för ett objekt."
  overload: System.Configuration.TimeSpanValidator.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.TimeSpanValidator.#ctor*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator
  nameWithType: TimeSpanValidator.TimeSpanValidator
- uid: System.Configuration.TimeSpanValidator.CanValidate*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: CanValidate
  nameWithType: TimeSpanValidator.CanValidate
- uid: System.Configuration.TimeSpanValidator.Validate*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: Validate
  nameWithType: TimeSpanValidator.Validate
