### YamlMime:ManagedReference
items:
- uid: System.Configuration.IPersistComponentSettings
  id: IPersistComponentSettings
  children:
  - System.Configuration.IPersistComponentSettings.LoadComponentSettings
  - System.Configuration.IPersistComponentSettings.ResetComponentSettings
  - System.Configuration.IPersistComponentSettings.SaveComponentSettings
  - System.Configuration.IPersistComponentSettings.SaveSettings
  - System.Configuration.IPersistComponentSettings.SettingsKey
  langs:
  - csharp
  name: IPersistComponentSettings
  nameWithType: IPersistComponentSettings
  fullName: System.Configuration.IPersistComponentSettings
  type: Interface
  summary: "Definierar standardfunktionerna för kontroller eller bibliotek som lagrar och hämtar programinställningar."
  remarks: "Normalt, du kan lägga till programstöd för inställningar till ett program genom att skapa en inställningar wrapper klass som härleds från <xref:System.Configuration.ApplicationSettingsBase>, och sedan lägga till särskilda egenskaper i den här klassen</xref:System.Configuration.ApplicationSettingsBase> Men den här metoden inte tillräckligt kapslar in programinställningar för en kontroll så att dess behållare är skärmad från informationen. Gränssnittet IPersistComponentSettings ger ett program med ett standardgränssnitt för att kommunicera programmet inställningar tillstånd ändringsförfrågningar till en kontroll, komponenten eller biblioteket modul. Verktyg för designtid beror också på det här gränssnittet för att korrekt hantera kontroller och komponenter."
  syntax:
    content: public interface IPersistComponentSettings
  implements: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.LoadComponentSettings
  id: LoadComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: LoadComponentSettings()
  nameWithType: IPersistComponentSettings.LoadComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.LoadComponentSettings()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Läser kontrollens programinställningar till sina motsvarande egenskaper och uppdaterar kontrollens status."
  remarks: "I allmänhet LoadComponentSettings metoden utför två grundläggande åtgärder:-instansen för varje program som finns i kontrollen att uppdatera värdena för dess programegenskaper inställningar, vanligtvis genom att anropa medför sina <xref:System.Configuration.ApplicationSettingsBase.Reload%2A>metoder.</xref:System.Configuration.ApplicationSettingsBase.Reload%2A>      – Som krävs uppdateras de allmänna egenskaper som är beroende av inställningarna ladda egenskaper. Om klassen inställningar finns till exempel en `location` inställningsegenskapen LoadComponentSettings bör se till att kontrollens <xref:System.Windows.Forms.Control.Location%2A>egenskapen uppdateras inställningen ladda.</xref:System.Windows.Forms.Control.Location%2A>"
  syntax:
    content: public void LoadComponentSettings ();
    parameters: []
  overload: System.Configuration.IPersistComponentSettings.LoadComponentSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.ResetComponentSettings
  id: ResetComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: ResetComponentSettings()
  nameWithType: IPersistComponentSettings.ResetComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.ResetComponentSettings()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Återställer kontrollens egenskaper för program-inställningar till standardvärdena."
  remarks: "Implementeringen av metoden ResetComponentSettings kräver normalt den <xref:System.Configuration.ApplicationSettingsBase.Reset%2A>metoden på varje instans av en klass för inställningar av program som den innehåller.</xref:System.Configuration.ApplicationSettingsBase.Reset%2A>"
  syntax:
    content: public void ResetComponentSettings ();
    parameters: []
  overload: System.Configuration.IPersistComponentSettings.ResetComponentSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.SaveComponentSettings
  id: SaveComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: SaveComponentSettings()
  nameWithType: IPersistComponentSettings.SaveComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.SaveComponentSettings()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Sparar inställningarna för kontrollens programegenskaperna."
  remarks: "Metoden SaveComponentSettings skriver värdena för kontrollens egenskaper för inställningar av programmet till den associera databasen. Den store och serialisering teknik som använder metoden bestäms av inställningsprovidern som är associerade med varje klassen via <xref:System.Configuration.SettingsProviderAttribute>.</xref:System.Configuration.SettingsProviderAttribute> Du kan åsidosätta valet av inställningsprovidern med hjälp av den <xref:System.Configuration.ISettingsProviderService>gränssnitt.</xref:System.Configuration.ISettingsProviderService>      > [!NOTE] > Om den <xref:System.Configuration.IPersistComponentSettings.SaveSettings%2A>egenskapen är `true`, kontrollen ska anropa SaveComponentSettings sin egen <xref:System.Windows.Forms.Control.Dispose%2A>metoden så att kontrollens konfigurationsdata lagras automatiskt innan programmet avslutas.</xref:System.Windows.Forms.Control.Dispose%2A> </xref:System.Configuration.IPersistComponentSettings.SaveSettings%2A>"
  syntax:
    content: public void SaveComponentSettings ();
    parameters: []
  overload: System.Configuration.IPersistComponentSettings.SaveComponentSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.SaveSettings
  id: SaveSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: SaveSettings
  nameWithType: IPersistComponentSettings.SaveSettings
  fullName: System.Configuration.IPersistComponentSettings.SaveSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar eller anger ett värde som anger om kontrollen automatiskt ska spara dess egenskaper för inställningar av programmet."
  remarks: "Om en kontroll innehåller konfigurationsdata, behålls det vanligtvis informationen som svar på ett explicit anrop till den <xref:System.Configuration.IPersistComponentSettings.SaveComponentSettings%2A>metoden eller ibland implicit när kontrollens <xref:System.Windows.Forms.Control.Dispose%2A>-metoden har anropats.</xref:System.Windows.Forms.Control.Dispose%2A> </xref:System.Configuration.IPersistComponentSettings.SaveComponentSettings%2A> Egenskapen Window bestämmer om en kontroll automatiskt kvarstår konfigurationsdata när den har tagits bort.       Standardvärdet för Window beror på implementering av kontrollen. I dokumentationen för kontrollen ska ange om den använder programinställningar, vilka data sparas och standardvärdet för egenskapen Window är."
  example:
  - "The following code example shows the proper way for a control to check the value of the SaveSettings property before it attempts to automatically persist its configuration data.  \n  \n `protected override void Dispose( bool disposing ) {`  \n  \n `if(disposing) {`  \n  \n `try {`  \n  \n `if (SaveSettings) {`  \n  \n `SaveComponentSettings();`  \n  \n `}`  \n  \n `}`  \n  \n `finally {`  \n  \n `//...`  \n  \n `}`  \n  \n `}`"
  syntax:
    content: public bool SaveSettings { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om kontrollen automatiskt ska spara sitt tillstånd; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.IPersistComponentSettings.SaveSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.SettingsKey
  id: SettingsKey
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: SettingsKey
  nameWithType: IPersistComponentSettings.SettingsKey
  fullName: System.Configuration.IPersistComponentSettings.SettingsKey
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar eller anger värdet för nyckeln för programmet-inställningarna för den aktuella instansen av kontrollen."
  remarks: "Använd egenskapen SettingsKey för att undvika tvetydigheten grupper av inställningar för programmet när det finns flera instanser av samma wrapper-klass. Till exempel om en kontroll innehåller en associerad wrapper-klass, resulterar placera sedan flera instanser av samma kontroll i samma program vanligtvis i flera instanser av klassen omslutning. Inställningar för nyckel krävs bara när konfigurationsdata skiljer sig på grundval av per instans; till exempel plats dynamiskt positionerade kontroller.       Följande allmänna regler gäller för användning av SettingsKey:-en kontroll som alla klasser kan innehålla noll eller flera program inställningar klasser som härleds från <xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase> Varje klassen innehåller sin egen <xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName>egenskap, vilket hjälper till att undvika tvetydigheten flera instanser av klass.</xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName>      -Kontroll ska dela per instans data och delade data i inställningarna för olika klasser.      – För en kontroll med några konfigurationsdata per instans, den `get` accessorn för egenskapen SettingsKey får som standard den <xref:System.Windows.Forms.Control.Name%2A>för kontrollen.</xref:System.Windows.Forms.Control.Name%2A> Namnet på kontrollen ska vara unika inom ett program i de flesta fall. Om kontrollen innehåller endast delade konfigurationsdata, `get` ska som standard `null`.      - `set` Accessor för den här egenskapen bör implementeras för att skilja mellan inställningar klasser som innehåller per instans och delad konfigurationsdata. För varje inställningar klass som innehåller data per instans, `set` bör bara direkt i <xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName>egenskapen för klassen inställningar.</xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName> För inställningar för klasser som innehåller delade data `set` ska utföra någon åtgärd för den klassen."
  syntax:
    content: public string SettingsKey { get; set; }
    return:
      type: System.String
      description: "En <xref:System.String>som innehåller inställningar för nyckeln för den aktuella instansen av kontrollen.</xref:System.String>"
  overload: System.Configuration.IPersistComponentSettings.SettingsKey*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.IPersistComponentSettings.LoadComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: LoadComponentSettings()
  nameWithType: IPersistComponentSettings.LoadComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.LoadComponentSettings()
- uid: System.Configuration.IPersistComponentSettings.ResetComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: ResetComponentSettings()
  nameWithType: IPersistComponentSettings.ResetComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.ResetComponentSettings()
- uid: System.Configuration.IPersistComponentSettings.SaveComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveComponentSettings()
  nameWithType: IPersistComponentSettings.SaveComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.SaveComponentSettings()
- uid: System.Configuration.IPersistComponentSettings.SaveSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveSettings
  nameWithType: IPersistComponentSettings.SaveSettings
  fullName: System.Configuration.IPersistComponentSettings.SaveSettings
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IPersistComponentSettings.SettingsKey
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SettingsKey
  nameWithType: IPersistComponentSettings.SettingsKey
  fullName: System.Configuration.IPersistComponentSettings.SettingsKey
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.IPersistComponentSettings.LoadComponentSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: LoadComponentSettings
  nameWithType: IPersistComponentSettings.LoadComponentSettings
- uid: System.Configuration.IPersistComponentSettings.ResetComponentSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: ResetComponentSettings
  nameWithType: IPersistComponentSettings.ResetComponentSettings
- uid: System.Configuration.IPersistComponentSettings.SaveComponentSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveComponentSettings
  nameWithType: IPersistComponentSettings.SaveComponentSettings
- uid: System.Configuration.IPersistComponentSettings.SaveSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveSettings
  nameWithType: IPersistComponentSettings.SaveSettings
- uid: System.Configuration.IPersistComponentSettings.SettingsKey*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SettingsKey
  nameWithType: IPersistComponentSettings.SettingsKey
