### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfigurationProviderCollection
  id: ProtectedConfigurationProviderCollection
  children:
  - System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  - System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  - System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  langs:
  - csharp
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection
  fullName: System.Configuration.ProtectedConfigurationProviderCollection
  type: Class
  summary: "Innehåller en mängd <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objekt."
  remarks: "Den <xref:System.Configuration.ProtectedConfiguration.Providers%2A>egenskapen för den <xref:System.Configuration.ProtectedConfiguration>klassen är en samling ProtectedConfigurationProviderCollection alla skyddade configuration leverantörer som är tillgängliga för ditt program.</xref:System.Configuration.ProtectedConfiguration> </xref:System.Configuration.ProtectedConfiguration.Providers%2A>       Du kan kryptera avsnitt i en konfigurationsfil för att skydda känslig information som används av ditt program. Detta förbättrar säkerheten genom att göra obehörig åtkomst svårt, även om en angripare får åtkomst till konfigurationsfilen.       .NET Framework innehåller två skyddade konfigurationstjänst som kan användas för att kryptera avsnitt i en konfigurationsfil: den <xref:System.Configuration.RsaProtectedConfigurationProvider>class, som använder den <xref:System.Security.Cryptography.RSACryptoServiceProvider>klassen för att kryptera konfigurationsavsnitt, och <xref:System.Configuration.DpapiProtectedConfigurationProvider>-klassen, som använder Windows Data Protection API (DPAPI) för att kryptera konfigurationsavsnitt.</xref:System.Configuration.DpapiProtectedConfigurationProvider> </xref:System.Security.Cryptography.RSACryptoServiceProvider> </xref:System.Configuration.RsaProtectedConfigurationProvider>       Du kanske har ett krav för att kryptera känsliga information med en algoritm än RSA eller DPAPI-providers. I det här fallet kan du skapa egna anpassade skyddade configuration-providern. Den <xref:System.Configuration.ProtectedConfigurationProvider>klassen är en abstrakt basklass som du måste ärva från att skapa en egen skyddad konfigurationstjänst.</xref:System.Configuration.ProtectedConfigurationProvider>       Mer information om skyddade konfiguration finns [kryptera Information med hjälp av skyddade konfiguration](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: 'public class ProtectedConfigurationProviderCollection : System.Configuration.Provider.ProviderCollection'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderCollection
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderCollection.Clear
  - System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  - System.Configuration.Provider.ProviderCollection.Count
  - System.Configuration.Provider.ProviderCollection.GetEnumerator
  - System.Configuration.Provider.ProviderCollection.IsSynchronized
  - System.Configuration.Provider.ProviderCollection.Remove(System.String)
  - System.Configuration.Provider.ProviderCollection.SetReadOnly
  - System.Configuration.Provider.ProviderCollection.SyncRoot
  - System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: ProtectedConfigurationProviderCollection()
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Configuration.ProtectedConfigurationProviderCollection&quot;> </xref> klassen med standardinställningar."
  remarks: "ProtectedConfigurationProviderCollection-konstruktorn är inte avsedd att användas direkt från din kod. Den anropas av ASP.NET-konfigurationssystemet. Du har fått en instans av <xref:System.Configuration.ProtectedConfigurationProviderCollection>klassen med hjälp av <xref:System.Configuration.ProtectedConfiguration.Providers%2A>egenskapen för <xref:System.Configuration.ProtectedConfiguration>klassen.</xref:System.Configuration.ProtectedConfiguration> </xref:System.Configuration.ProtectedConfiguration.Providers%2A> </xref:System.Configuration.ProtectedConfigurationProviderCollection>"
  syntax:
    content: public ProtectedConfigurationProviderCollection ();
    parameters: []
  overload: System.Configuration.ProtectedConfigurationProviderCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  id: Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: Add(ProviderBase)
  nameWithType: ProtectedConfigurationProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add(ProviderBase)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lägger till en <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objekt i samlingen."
  syntax:
    content: public override void Add (System.Configuration.Provider.ProviderBase provider);
    parameters:
    - id: provider
      type: System.Configuration.Provider.ProviderBase
      description: "En <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objekt att lägga till i samlingen."
  overload: System.Configuration.ProtectedConfigurationProviderCollection.Add*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>provider</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>provider</code>är inte en <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objekt."
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "The <xref href=\"System.Configuration.ProtectedConfigurationProvider\"></xref> object to add already exists in the collection.  \n  \n \\- or -  \n  \n The collection is read-only."
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: ProtectedConfigurationProviderCollection.Item(String)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item(String)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hämtar en <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objekt i samlingen med det angivna namnet."
  syntax:
    content: public System.Configuration.ProtectedConfigurationProvider this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "Namnet på en <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objekt i samlingen."
    return:
      type: System.Configuration.ProtectedConfigurationProvider
      description: "Den <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objektet med det angivna namnet eller <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> om det finns inget objekt med det namnet."
  overload: System.Configuration.ProtectedConfigurationProviderCollection.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: System.Configuration.Provider.ProviderCollection
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.ConfigurationException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationException
  nameWithType: ConfigurationException
  fullName: System.Configuration.ConfigurationException
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: ProtectedConfigurationProviderCollection()
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Add(ProviderBase)
  nameWithType: ProtectedConfigurationProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add(ProviderBase)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Item(String)
  nameWithType: ProtectedConfigurationProviderCollection.Item(String)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item(String)
- uid: System.Configuration.ProtectedConfigurationProvider
  parent: System.Configuration
  isExternal: false
  name: ProtectedConfigurationProvider
  nameWithType: ProtectedConfigurationProvider
  fullName: System.Configuration.ProtectedConfigurationProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Add
  nameWithType: ProtectedConfigurationProviderCollection.Add
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Item
  nameWithType: ProtectedConfigurationProviderCollection.Item
