### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IConfigMapPath
  id: IConfigMapPath
  children:
  - System.Web.Configuration.IConfigMapPath.GetAppPathForPath(System.String,System.String)
  - System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  - System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename
  - System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  - System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename
  - System.Web.Configuration.IConfigMapPath.MapPath(System.String,System.String)
  - System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  langs:
  - csharp
  name: IConfigMapPath
  nameWithType: IConfigMapPath
  fullName: System.Web.Configuration.IConfigMapPath
  type: Interface
  summary: "Tillhandahåller åtkomst till mappningen mellan konfigurationsfilen virtuella och fysiska sökvägar."
  remarks: "IConfigMapPath introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public interface IConfigMapPath
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(System.String,System.String)
  id: GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetAppPathForPath(String,String)
  nameWithType: IConfigMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar virtuell katalog namnet som associeras med en viss plats."
  remarks: "GetAppPathForPath introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetAppPathForPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "En unik identifierare för platsen."
    - id: path
      type: System.String
      description: "Webbadressen för webbplatsen."
    return:
      type: System.String
      description: "Den <code> siteID </code> måste vara unika. Inga två platser dela samma id. Den <code> siteID </code> särskiljer platser som har samma namn."
  overload: System.Web.Configuration.IConfigMapPath.GetAppPathForPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  id: GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: IConfigMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Fyller platsnamn och plats-ID."
  remarks: "GetDefaultSiteNameAndID introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void GetDefaultSiteNameAndID (out string siteName, out string siteID);
    parameters:
    - id: siteName
      type: System.String
      description: "Standard-platsnamn."
    - id: siteID
      type: System.String
      description: "En unik identifierare för platsen."
  overload: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename
  id: GetMachineConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetMachineConfigFilename()
  nameWithType: IConfigMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar namnet på konfigurationen av datorn."
  remarks: "GetMachineConfigFilename introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetMachineConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "Konfigurationen av datorn filnamnet."
  overload: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  id: GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: IConfigMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(String,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Fyller katalogen och namnet på konfigurationsfilen baserat på webbplats-ID och sökväg."
  remarks: "GetPathConfigFilename introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void GetPathConfigFilename (string siteID, string path, out string directory, out string baseName);
    parameters:
    - id: siteID
      type: System.String
      description: "En unik identifierare för platsen."
    - id: path
      type: System.String
      description: "Webbadressen för webbplatsen."
    - id: directory
      type: System.String
      description: "Den fysiska katalogen konfigurationssökvägen."
    - id: baseName
      type: System.String
      description: "Namnet på konfigurationsfilen."
  overload: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename
  id: GetRootWebConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: GetRootWebConfigFilename()
  nameWithType: IConfigMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar namnet på konfigurationsfilen Web rot."
  remarks: "GetRootWebConfigFilename introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string GetRootWebConfigFilename ();
    parameters: []
    return:
      type: System.String
      description: "Namnet på konfigurationsfilen Web rot."
  overload: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.MapPath(System.String,System.String)
  id: MapPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: MapPath(String,String)
  nameWithType: IConfigMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.MapPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar fysiska sökvägen till baserat på webbplats-ID och Webbadressen för webbplatsen."
  remarks: "MapPath introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string MapPath (string siteID, string path);
    parameters:
    - id: siteID
      type: System.String
      description: "En unik identifierare för platsen."
    - id: path
      type: System.String
      description: "Webbadressen för webbplatsen."
    return:
      type: System.String
      description: "Den fysiska sökvägen."
  overload: System.Web.Configuration.IConfigMapPath.MapPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  id: ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  langs:
  - csharp
  name: ResolveSiteArgument(String,String,String)
  nameWithType: IConfigMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Fyller namn och plats-ID som baseras på ett värde för argumentet plats."
  remarks: "Om `siteArgument` är `null`, är lika med namn för plats eller är lika med webbplatsidentifierare standard den `siteName` och `siteID` fylls i med standardvärden för platsen.       ResolveSiteArgument introducerades i .NET Framework version 3.5.  Mer information finns i [versioner och beroenden](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public void ResolveSiteArgument (string siteArgument, out string siteName, out string siteID);
    parameters:
    - id: siteArgument
      type: System.String
      description: "Namn eller identifierare för webbplatsen."
    - id: siteName
      type: System.String
      description: "Standard-platsnamn."
    - id: siteID
      type: System.String
      description: "En unik identifierare för platsen."
  overload: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetAppPathForPath(String,String)
  nameWithType: IConfigMapPath.GetAppPathForPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetAppPathForPath(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID(String,String)
  nameWithType: IConfigMapPath.GetDefaultSiteNameAndID(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID(String,String)
- uid: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetMachineConfigFilename()
  nameWithType: IConfigMapPath.GetMachineConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename()
- uid: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(System.String,System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetPathConfigFilename(String,String,String,String)
  nameWithType: IConfigMapPath.GetPathConfigFilename(String,String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename(String,String,String,String)
- uid: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetRootWebConfigFilename()
  nameWithType: IConfigMapPath.GetRootWebConfigFilename()
  fullName: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename()
- uid: System.Web.Configuration.IConfigMapPath.MapPath(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: MapPath(String,String)
  nameWithType: IConfigMapPath.MapPath(String,String)
  fullName: System.Web.Configuration.IConfigMapPath.MapPath(String,String)
- uid: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: ResolveSiteArgument(String,String,String)
  nameWithType: IConfigMapPath.ResolveSiteArgument(String,String,String)
  fullName: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument(String,String,String)
- uid: System.Web.Configuration.IConfigMapPath.GetAppPathForPath*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetAppPathForPath
  nameWithType: IConfigMapPath.GetAppPathForPath
- uid: System.Web.Configuration.IConfigMapPath.GetDefaultSiteNameAndID*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetDefaultSiteNameAndID
  nameWithType: IConfigMapPath.GetDefaultSiteNameAndID
- uid: System.Web.Configuration.IConfigMapPath.GetMachineConfigFilename*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetMachineConfigFilename
  nameWithType: IConfigMapPath.GetMachineConfigFilename
- uid: System.Web.Configuration.IConfigMapPath.GetPathConfigFilename*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetPathConfigFilename
  nameWithType: IConfigMapPath.GetPathConfigFilename
- uid: System.Web.Configuration.IConfigMapPath.GetRootWebConfigFilename*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: GetRootWebConfigFilename
  nameWithType: IConfigMapPath.GetRootWebConfigFilename
- uid: System.Web.Configuration.IConfigMapPath.MapPath*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: MapPath
  nameWithType: IConfigMapPath.MapPath
- uid: System.Web.Configuration.IConfigMapPath.ResolveSiteArgument*
  parent: System.Web.Configuration.IConfigMapPath
  isExternal: false
  name: ResolveSiteArgument
  nameWithType: IConfigMapPath.ResolveSiteArgument
