### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer
  id: RemoteWebConfigurationHostServer
  children:
  - System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor
  - System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  - System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  - System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  - System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  - System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  langs:
  - csharp
  name: RemoteWebConfigurationHostServer
  nameWithType: RemoteWebConfigurationHostServer
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer
  type: Class
  summary: "Används internt vid körning som stöder inte att komma åt konfigurationsdata via fjärranslutning."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.AutoDual)]

      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Runtime.InteropServices.Guid("9FDB6D2C-90EA-4e42-99E6-38B96E28698E")]

      [System.Runtime.InteropServices.ProgId("System.Web.Configuration.RemoteWebConfigurationHostServerV4_32")]

      public class RemoteWebConfigurationHostServer : System.Web.Configuration.IRemoteWebConfigurationHostServer
  inheritance:
  - System.Object
  implements:
  - System.Web.Configuration.IRemoteWebConfigurationHostServer
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: RemoteWebConfigurationHostServer()
  nameWithType: RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer()
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Används internt vid körning för att skapa en ny instans av <xref href=&quot;System.Web.Configuration.RemoteWebConfigurationHostServer&quot;> </xref>."
  syntax:
    content: public RemoteWebConfigurationHostServer ();
    parameters: []
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  id: DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Villkorligt krypterar eller dekrypterar värdet för strängen som refererar till den <code> xmlString </code> parameter."
  syntax:
    content: public string DoEncryptOrDecrypt (bool doEncrypt, string xmlString, string protectionProviderName, string protectionProviderType, string[] paramKeys, string[] paramValues);
    parameters:
    - id: doEncrypt
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>att kryptera; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> att dekryptera."
    - id: xmlString
      type: System.String
      description: "XML-filen ska krypteras och dekrypteras."
    - id: protectionProviderName
      type: System.String
      description: "Providern som används för att skydda konfigurationsdata."
    - id: protectionProviderType
      type: System.String
      description: "Den <xref:System.Type>av skydd providern.</xref:System.Type>"
    - id: paramKeys
      type: System.String[]
      description: "Nycklar för valfria parametrar för providern skydd."
    - id: paramValues
      type: System.String[]
      description: "Värden för valfria parametrar för providern skydd."
    return:
      type: System.String
      description: "En sträng som innehåller antingen det krypterade eller dekrypterade värdet av <code> xmlString </code>."
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  exceptions:
  - type: System.Exception
    commentId: T:System.Exception
    description: "<code>protectionProviderType</code>är inte härledd från <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref>."
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  id: GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetData(String,Boolean,Int64)
  nameWithType: RemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Används internt för att stödja fjärråtkomst till konfigurationsdata."
  syntax:
    content: public byte[] GetData (string fileName, bool getReadTimeOnly, out long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Sökvägen till den fjärranslutna konfigurationsfilen som kan nås."
    - id: getReadTimeOnly
      type: System.Boolean
      description: "Ett booleskt värde som anger om bara den `readTime` returneras."
    - id: readTime
      type: System.Int64
      description: "Den tid då filen senast användes."
    return:
      type: System.Byte[]
      description: "En <xref uid=&quot;langword_csharp_array&quot; name=&quot;array&quot; href=&quot;&quot;> </xref> av 8-bitars heltal utan tecken (byte) som innehåller konfigurationsdata."
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData*
  exceptions:
  - type: System.Exception
    commentId: T:System.Exception
    description: "<code>fileName</code>pekar inte till en fil med filnamnstillägget .config."
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  id: GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: RemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar information om konfigurationsfilen."
  syntax:
    content: public void GetFileDetails (string name, out bool exists, out long size, out long createDate, out long lastWriteDate);
    parameters:
    - id: name
      type: System.String
      description: "Namnet på filen."
    - id: exists
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om filen finns; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: size
      type: System.Int64
      description: "Storleken på filen."
    - id: createDate
      type: System.Int64
      description: "Det datum då filen skapades."
    - id: lastWriteDate
      type: System.Int64
      description: "Det datum då filen senast skrevs."
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails*
  exceptions:
  - type: System.Exception
    commentId: T:System.Exception
    description: "<code>name</code>pekar inte till en fil med filnamnstillägget .config."
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  id: GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: RemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Används internt för att stödja fjärråtkomst till konfigurationsdata."
  syntax:
    content: public string GetFilePaths (int webLevelAsInt, string path, string site, string locationSubPath);
    parameters:
    - id: webLevelAsInt
      type: System.Int32
      description: "Nivån i konfigurationsfilen."
    - id: path
      type: System.String
      description: "Sökvägen till den fjärranslutna konfigurationsfilen som kan nås."
    - id: site
      type: System.String
      description: "Sökvägen till fjärrdatorn."
    - id: locationSubPath
      type: System.String
      description: "Undersökvägen för platsen för konfigurationsfilen."
    return:
      type: System.String
      description: "En sammanfogad sträng som representerar sökvägen till filen i konfigurationsfilen."
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  id: WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: RemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Används internt för att stödja fjärråtkomst till konfigurationsdata."
  syntax:
    content: public void WriteData (string fileName, string templateFileName, byte[] data, ref long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "Sökvägen till den fjärranslutna konfigurationsfilen som kan nås."
    - id: templateFileName
      type: System.String
      description: "Duplicera attribut från filen."
    - id: data
      type: System.Byte[]
      description: "Data som ska skrivas."
    - id: readTime
      type: System.Int64
      description: "Den tid då filen senast användes."
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData*
  exceptions:
  - type: System.Exception
    commentId: T:System.Exception
    description: "<code>fileName</code> does not point to a file with the .config extension.  \n  \n \\- or -  \n  \n The file has changed since it was read.  \n  \n \\- or -  \n  \n The file is hidden or read-only.  \n  \n \\- or -  \n  \n The method fails to generate a temp file.  \n  \n \\- or -  \n  \n The method fails to create a <xref href=\"System.IO.FileStream\"></xref>.  \n  \n \\- or -  \n  \n The temp file fails to overwrite the target file."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Exception
  isExternal: true
  name: System.Exception
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: RemoteWebConfigurationHostServer()
  nameWithType: RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer()
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer()
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetData(String,Boolean,Int64)
  nameWithType: RemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: RemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: RemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: RemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: RemoteWebConfigurationHostServer
  nameWithType: RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt
  nameWithType: RemoteWebConfigurationHostServer.DoEncryptOrDecrypt
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetData
  nameWithType: RemoteWebConfigurationHostServer.GetData
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails
  nameWithType: RemoteWebConfigurationHostServer.GetFileDetails
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths
  nameWithType: RemoteWebConfigurationHostServer.GetFilePaths
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData
  nameWithType: RemoteWebConfigurationHostServer.WriteData
