### YamlMime:ManagedReference
items:
- uid: System.Data.Common.DbProviderConfigurationHandler
  id: DbProviderConfigurationHandler
  children:
  - System.Data.Common.DbProviderConfigurationHandler.#ctor
  - System.Data.Common.DbProviderConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: DbProviderConfigurationHandler
  nameWithType: DbProviderConfigurationHandler
  fullName: System.Data.Common.DbProviderConfigurationHandler
  type: Class
  summary: "Den här klassen kan användas av valfri provider som stöd för en provider-specifik konfigurationsavsnittet."
  syntax:
    content: 'public class DbProviderConfigurationHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Common.DbProviderConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Data.Common.DbProviderConfigurationHandler
  langs:
  - csharp
  name: DbProviderConfigurationHandler()
  nameWithType: DbProviderConfigurationHandler.DbProviderConfigurationHandler()
  fullName: System.Data.Common.DbProviderConfigurationHandler.DbProviderConfigurationHandler()
  type: Constructor
  assemblies:
  - System.Data
  namespace: System.Data.Common
  summary: "Den här klassen kan användas av valfri provider som stöd för en provider-specifik konfigurationsavsnittet."
  syntax:
    content: public DbProviderConfigurationHandler ();
    parameters: []
  overload: System.Data.Common.DbProviderConfigurationHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Common.DbProviderConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DbProviderConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Data.Common.DbProviderConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Data
  namespace: System.Data.Common
  summary: "Skapar en ny [System.Collections.Specialized.NameValueCollection](~/add/includes/ajax-current-ext-md.md) uttryck."
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Den här typen har stöd för .NET Framework-infrastrukturen och är inte avsedd att användas direkt från din kod."
    - id: configContext
      type: System.Object
      description: "Den här typen har stöd för .NET Framework-infrastrukturen och är inte avsedd att användas direkt från din kod."
    - id: section
      type: System.Xml.XmlNode
      description: "Den här typen har stöd för .NET Framework-infrastrukturen och är inte avsedd att användas direkt från din kod."
    return:
      type: System.Object
      description: "Det nya uttrycket."
  overload: System.Data.Common.DbProviderConfigurationHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Data.Common.DbProviderConfigurationHandler.#ctor
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: DbProviderConfigurationHandler()
  nameWithType: DbProviderConfigurationHandler.DbProviderConfigurationHandler()
  fullName: System.Data.Common.DbProviderConfigurationHandler.DbProviderConfigurationHandler()
- uid: System.Data.Common.DbProviderConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DbProviderConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Data.Common.DbProviderConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Data.Common.DbProviderConfigurationHandler.#ctor*
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: DbProviderConfigurationHandler
  nameWithType: DbProviderConfigurationHandler.DbProviderConfigurationHandler
- uid: System.Data.Common.DbProviderConfigurationHandler.Create*
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DbProviderConfigurationHandler.Create
