### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationActivationAttribute
  id: ApplicationActivationAttribute
  children:
  - System.EnterpriseServices.ApplicationActivationAttribute.#ctor(System.EnterpriseServices.ActivationOption)
  - System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
  - System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
  - System.EnterpriseServices.ApplicationActivationAttribute.Value
  langs:
  - csharp
  name: ApplicationActivationAttribute
  nameWithType: ApplicationActivationAttribute
  fullName: System.EnterpriseServices.ApplicationActivationAttribute
  type: Class
  summary: "Anger om komponenterna i sammansättningen köras i processen för den person som skapade eller i en systemprocess."
  remarks: ''
  example:
  - "The following code example demonstrates the use of `ApplicationActivationAttribute` to mark a <xref:System.EnterpriseServices.ServicedComponent>.  \n  \n [!code-cpp[EnterpriseServices_Basic#1](~/add/codesnippet/cpp/t-system.enterpriseservi_13_1.cpp)]\n [!code-cs[EnterpriseServices_Basic#1](~/add/codesnippet/csharp/t-system.enterpriseservi_13_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationActivationAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationActivationAttribute.#ctor(System.EnterpriseServices.ActivationOption)
  id: '#ctor(System.EnterpriseServices.ActivationOption)'
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  langs:
  - csharp
  name: ApplicationActivationAttribute(ActivationOption)
  nameWithType: ApplicationActivationAttribute.ApplicationActivationAttribute(ActivationOption)
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.ApplicationActivationAttribute(ActivationOption)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Initierar en ny instans av den <xref href=&quot;System.EnterpriseServices.ApplicationActivationAttribute&quot;> </xref> klass, ställa in den angivna <xref href=&quot;System.EnterpriseServices.ActivationOption&quot;> </xref> värde."
  syntax:
    content: public ApplicationActivationAttribute (System.EnterpriseServices.ActivationOption opt);
    parameters:
    - id: opt
      type: System.EnterpriseServices.ActivationOption
      description: "En av de <xref href=&quot;System.EnterpriseServices.ActivationOption&quot;> </xref> värden."
  overload: System.EnterpriseServices.ApplicationActivationAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
  id: SoapMailbox
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  langs:
  - csharp
  name: SoapMailbox
  nameWithType: ApplicationActivationAttribute.SoapMailbox
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Den här egenskapen stöds inte i den aktuella versionen."
  syntax:
    content: public string SoapMailbox { get; set; }
    return:
      type: System.String
      description: "Den här egenskapen stöds inte i den aktuella versionen."
  overload: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
  id: SoapVRoot
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  langs:
  - csharp
  name: SoapVRoot
  nameWithType: ApplicationActivationAttribute.SoapVRoot
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Hämtar eller anger ett värde som representerar en virtuell rot på webben för COM +-programmet."
  remarks: "När den används, uppstår allt arbete som krävs för att ställa in eller går sönder ned SOAP för programmet. Om den här egenskapen har angetts för ett program som körs på en dator där den [!INCLUDE[winsdklong](~/add/includes/winsdklong-md.md)] inte är installerad kan ett fel uppstår."
  syntax:
    content: public string SoapVRoot { get; set; }
    return:
      type: System.String
      description: "Den virtuella roten på webben för COM +-programmet."
  overload: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationActivationAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationActivationAttribute.Value
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Hämtar den angivna <xref href=&quot;System.EnterpriseServices.ActivationOption&quot;> </xref> värde."
  syntax:
    content: public System.EnterpriseServices.ActivationOption Value { get; }
    return:
      type: System.EnterpriseServices.ActivationOption
      description: "One of the <xref href=&quot;System.EnterpriseServices.ActivationOption&quot;></xref> values, either <xref uid=&quot;langword_csharp_Library&quot; name=&quot;Library&quot; href=&quot;&quot;></xref> or <xref uid=&quot;langword_csharp_Server&quot; name=&quot;Server&quot; href=&quot;&quot;></xref>."
  overload: System.EnterpriseServices.ApplicationActivationAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationActivationAttribute.#ctor(System.EnterpriseServices.ActivationOption)
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: ApplicationActivationAttribute(ActivationOption)
  nameWithType: ApplicationActivationAttribute.ApplicationActivationAttribute(ActivationOption)
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.ApplicationActivationAttribute(ActivationOption)
- uid: System.EnterpriseServices.ActivationOption
  parent: System.EnterpriseServices
  isExternal: false
  name: ActivationOption
  nameWithType: ActivationOption
  fullName: System.EnterpriseServices.ActivationOption
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: SoapMailbox
  nameWithType: ApplicationActivationAttribute.SoapMailbox
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: SoapVRoot
  nameWithType: ApplicationActivationAttribute.SoapVRoot
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
- uid: System.EnterpriseServices.ApplicationActivationAttribute.Value
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationActivationAttribute.Value
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.Value
- uid: System.EnterpriseServices.ApplicationActivationAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: ApplicationActivationAttribute
  nameWithType: ApplicationActivationAttribute.ApplicationActivationAttribute
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox*
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: SoapMailbox
  nameWithType: ApplicationActivationAttribute.SoapMailbox
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot*
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: SoapVRoot
  nameWithType: ApplicationActivationAttribute.SoapVRoot
- uid: System.EnterpriseServices.ApplicationActivationAttribute.Value*
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationActivationAttribute.Value
