### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler
  id: HttpCapabilitiesSectionHandler
  children:
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler
  type: Class
  summary: "Hjälper till att läsa i den <xref uid=&quot;langword_csharp_&lt;browserCaps&gt;&quot; name=&quot;&lt;browserCaps&gt;&quot; href=&quot;&quot;> </xref> avsnitt i en konfigurationsfil och skapa en instans av den <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> klass som innehåller information om funktioner för klientens webbläsare."
  remarks: "Klassen HttpCapabilitiesSectionHandler och motsvarande `<browserCaps>` konfigurationsavsnittet har inaktuell i .NET Framework version 2.0. Den bästa metoden för att hantera webbläsarfunktioner är via webbläsaren definitionsfiler som kompileras för användning av <xref:System.Web.Configuration.BrowserCapabilitiesFactory>klass.</xref:System.Web.Configuration.BrowserCapabilitiesFactory> Målet med både configuration-metoder är att skapa en instans av <xref:System.Web.HttpBrowserCapabilities>klassen som kan nås från <xref:System.Web.HttpRequest.Browser%2A>egenskapen för <xref:System.Web.HttpRequest>klassen.</xref:System.Web.HttpRequest> </xref:System.Web.HttpRequest.Browser%2A> </xref:System.Web.HttpBrowserCapabilities>       Använder webbläsaren definitionsfiler för att lagra webbläsarfunktioner ger fördelar jämfört med andra. Den erbjuder bättre prestanda eftersom webbläsaren definitionsinformation parsats från XML-konfigurationsfilen och kompileras till en klass i förväg. Webbläsaren definitionsfiler är också enklare att underhålla:-definitioner är hierarkiska och därmed använder mindre på reguljära uttryck för att avgöra webbläsarfunktioner.      -Definitionerna kan ordnas i flera filer, vilket gör dem lättare att hantera.      -Definitionerna kan definieras på alla nivåer, antingen på Machine.config-nivå eller ett visst program. Detta eliminerar behovet av att kopiera hela uppsättningen av definitioner för att åsidosätta funktioner för en viss webbläsare."
  syntax:
    content: 'public class HttpCapabilitiesSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Web.Configuration.HttpCapabilitiesSectionHandler&quot;> </xref> klass."
  syntax:
    content: public HttpCapabilitiesSectionHandler ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Skapar en instans av den <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> klass som innehåller information om funktioner för klientens webbläsare."
  remarks: "Den här klassen härleds webbläsare definition data från den `<browserCaps>` konfigurationsavsnittet. Det här avsnittet är inaktuell i .NET Framework version 2.0."
  syntax:
    content: public object Create (object parent, object configurationContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Den överordnade noden för konfigurationen."
    - id: configurationContext
      type: System.Object
      description: "Konfigurationskontexten för den aktuella konfigurationsfilen."
    - id: section
      type: System.Xml.XmlNode
      description: "Avsnittet i konfigurationsfilen som innehåller information."
    return:
      type: System.Object
      description: "En instans av <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> som innehåller information om funktioner för klientens webbläsare."
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create
  nameWithType: HttpCapabilitiesSectionHandler.Create
