### YamlMime:ManagedReference
items:
- uid: System.Drawing.Printing.QueryPageSettingsEventHandler
  id: QueryPageSettingsEventHandler
  langs:
  - csharp
  name: QueryPageSettingsEventHandler
  nameWithType: QueryPageSettingsEventHandler
  fullName: System.Drawing.Printing.QueryPageSettingsEventHandler
  type: Delegate
  summary: "Representerar den metod som hanterar den <xref href=&quot;System.Drawing.Printing.PrintDocument.QueryPageSettings&quot;> </xref> händelsen för en <xref href=&quot;System.Drawing.Printing.PrintDocument&quot;> </xref>."
  remarks: "När du skapar en QueryPageSettingsEventHandler delegat kan identifiera den metod som hanterar händelsen. Lägga till en instans av delegaten händelsen om du vill associera händelsen med din händelsehanterare. Händelsehanteraren anropas när händelsen inträffar, om du tar bort delegaten. Läs mer om händelsehanteraren delegater [händelser](~/add/includes/ajax-current-ext-md.md).       Mer information om utskrift finns i <xref:System.Drawing.Printing>namnområde Översikt.</xref:System.Drawing.Printing>"
  syntax:
    content: public delegate void QueryPageSettingsEventHandler(object sender, QueryPageSettingsEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
