### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationUnloadedException
  id: WorkflowApplicationUnloadedException
  children:
  - System.Activities.WorkflowApplicationUnloadedException.#ctor
  - System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String)
  - System.Activities.WorkflowApplicationUnloadedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String,System.Guid,System.Exception)
  langs:
  - csharp
  name: WorkflowApplicationUnloadedException
  nameWithType: WorkflowApplicationUnloadedException
  fullName: System.Activities.WorkflowApplicationUnloadedException
  type: Class
  summary: "Ett undantag som utlöses när en åtgärd på en arbetsflödesinstans är ogiltig eftersom instansen har inaktiverats."
  syntax:
    content: 'public class WorkflowApplicationUnloadedException : System.Activities.WorkflowApplicationException'
  inheritance:
  - System.Exception
  - System.Activities.WorkflowApplicationException
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationUnloadedException
  langs:
  - csharp
  name: WorkflowApplicationUnloadedException()
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException()
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Skapar en ny instans av den <xref href=&quot;System.Activities.WorkflowApplicationUnloadedException&quot;> </xref> klass."
  syntax:
    content: public WorkflowApplicationUnloadedException ();
    parameters: []
  overload: System.Activities.WorkflowApplicationUnloadedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationUnloadedException
  langs:
  - csharp
  name: WorkflowApplicationUnloadedException(String)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Skapar en ny instans av den <xref href=&quot;System.Activities.WorkflowApplicationUnloadedException&quot;> </xref> klass med angivna beskrivning sträng för undantaget."
  syntax:
    content: public WorkflowApplicationUnloadedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Beskrivning av programmet inaktiverade undantag."
  overload: System.Activities.WorkflowApplicationUnloadedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationUnloadedException
  langs:
  - csharp
  name: WorkflowApplicationUnloadedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Skapar en ny instans av den <xref href=&quot;System.Activities.WorkflowApplicationUnloadedException&quot;> </xref> klass med kontexten och serialisering informationen som krävs för att hämta data om det här undantaget från en serialiserad dataström."
  syntax:
    content: protected WorkflowApplicationUnloadedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "All information som krävs serialiseras eller deserialiseras inaktiverats undantag programobjektet."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Källa och mål för en given serialiserad dataström och en ytterligare kontext som definieras av anroparen."
  overload: System.Activities.WorkflowApplicationUnloadedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationUnloadedException
  langs:
  - csharp
  name: WorkflowApplicationUnloadedException(String,Exception)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Skapar en ny instans av den <xref href=&quot;System.Activities.WorkflowApplicationUnloadedException&quot;> </xref> klassen med den angivna text strängbeskrivningen för undantaget och med ett angivet undantag som har ett orsakssamband till den <xref href=&quot;System.Activities.WorkflowApplicationUnloadedException&quot;> </xref>."
  syntax:
    content: public WorkflowApplicationUnloadedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "En beskrivning av programmet inaktiverade undantag."
    - id: innerException
      type: System.Exception
      description: "Ett undantag som har ett orsakssamband till programmet inaktiverade undantag. Programundantag minnet utlöses som svar på det inre undantaget och kan använda information från det interna undantaget för att hantera felet mer korrekt."
  overload: System.Activities.WorkflowApplicationUnloadedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationUnloadedException
  langs:
  - csharp
  name: WorkflowApplicationUnloadedException(String,Guid)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Skapar en ny instans av den <xref href=&quot;System.Activities.WorkflowApplicationUnloadedException&quot;> </xref> klass med den angivna strängbeskrivningen av undantaget och den angivna unika identifieraren för den."
  syntax:
    content: public WorkflowApplicationUnloadedException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: "En beskrivning av programmet inaktiverade undantag."
    - id: instanceId
      type: System.Guid
      description: "En globalt unik identifierare."
  overload: System.Activities.WorkflowApplicationUnloadedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationUnloadedException
  langs:
  - csharp
  name: WorkflowApplicationUnloadedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Guid,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Skapar en ny instans av den <xref href=&quot;System.Activities.WorkflowApplicationUnloadedException&quot;> </xref> klassen med den angivna strängbeskrivningen för undantaget och unik identifierare för det undantag som orsakas av den <xref href=&quot;System.Activities.WorkflowApplicationUnloadedException&quot;> </xref>."
  syntax:
    content: public WorkflowApplicationUnloadedException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "En beskrivning av programmet inaktiverade undantag."
    - id: instanceId
      type: System.Guid
      description: "En globalt unik identifierare."
    - id: innerException
      type: System.Exception
      description: "Ett undantag som har ett orsakssamband till programmet inaktiverade undantag. Programundantag minnet utlöses som svar på det inre undantaget och kan använda information från undantaget för att hantera felet mer lämpligt."
  overload: System.Activities.WorkflowApplicationUnloadedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.WorkflowApplicationException
  isExternal: false
  name: System.Activities.WorkflowApplicationException
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor
  parent: System.Activities.WorkflowApplicationUnloadedException
  isExternal: false
  name: WorkflowApplicationUnloadedException()
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException()
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException()
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationUnloadedException
  isExternal: false
  name: WorkflowApplicationUnloadedException(String)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationUnloadedException
  isExternal: false
  name: WorkflowApplicationUnloadedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationUnloadedException
  isExternal: false
  name: WorkflowApplicationUnloadedException(String,Exception)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationUnloadedException
  isExternal: false
  name: WorkflowApplicationUnloadedException(String,Guid)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Guid)
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationUnloadedException
  isExternal: false
  name: WorkflowApplicationUnloadedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException(String,Guid,Exception)
- uid: System.Activities.WorkflowApplicationUnloadedException.#ctor*
  parent: System.Activities.WorkflowApplicationUnloadedException
  isExternal: false
  name: WorkflowApplicationUnloadedException
  nameWithType: WorkflowApplicationUnloadedException.WorkflowApplicationUnloadedException
