### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  id: AssemblyVersionCompatibility
  children:
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  langs:
  - csharp
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
  type: Enum
  summary: "Definierar de olika typerna av sammansättningen versionskompatibiliteten. Den här funktionen är inte tillgängliga i version 1.0 av .NET Framework."
  remarks: "`AssemblyVersionCompatibility`definierar en sammansättning är kompatibel med andra versioner av samma sammansättning, som anger om det går inte att köra sida vid sida med andra versioner (t.ex, på grund av konflikter via en drivrutin).       Om inga kompatibilitet har angetts är en sammansättning sida-vid-sida-kompatibel i alla scope.       En sammansättning får inte vara mer specifika avseende exakt vilka tidigare versioner av det inte är kompatibel med sida vid sida med. Därför, om den `AssemblyVersionCompatibility` har angetts innebär det att sammansättningen finns inte sida-vid-sida med alla vet versioner. Om inget annat anges, betyder det att den är sida-vid-sida med alla kända versioner."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum AssemblyVersionCompatibility
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  id: SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Sammansättningen kan inte utföra med andra versioner om de körs i samma programdomän."
  syntax:
    content: SameDomain
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  id: SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Sammansättningen kan inte utföra med andra versioner om de körs på samma dator."
  syntax:
    content: SameMachine
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  id: SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Sammansättningen kan inte utföra med andra versioner om de körs i samma process."
  syntax:
    content: SameProcess
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
