### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  id: ConfigurationElementInterceptor
  children:
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: ConfigurationElementInterceptor
  nameWithType: ConfigurationElementInterceptor
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  type: Class
  summary: "Delar av Windows Identity Foundation (WIF) Konfigurationsschemat där användare kan ange valfri element och attribut; till exempel när du anger en anpassad hanterare för token. Klassen ConfigurationElementInterceptor implementeras för att hantera dessa fall."
  syntax:
    content: 'public class ConfigurationElementInterceptor : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: ConfigurationElementInterceptor()
  nameWithType: ConfigurationElementInterceptor.ConfigurationElementInterceptor()
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ConfigurationElementInterceptor()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.IdentityModel.Configuration.ConfigurationElementInterceptor&quot;> </xref> klass."
  syntax:
    content: public ConfigurationElementInterceptor ();
    parameters: []
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  id: ChildNodes
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: ChildNodes
  nameWithType: ConfigurationElementInterceptor.ChildNodes
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Hämtar underordnat noder i det här elementet."
  syntax:
    content: public System.Xml.XmlNodeList ChildNodes { get; }
    return:
      type: System.Xml.XmlNodeList
      description: "Mängden med underordnade noder. <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>Om det här elementet har inga underordnade noder."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Läser XML i konfigurationsfilen."
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "Den <xref:System.Xml.XmlReader>som läser från konfigurationsfilen.</xref:System.Xml.XmlReader>"
    - id: serializeCollectionKey
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>att serialisera endast samling nyckelegenskaper; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  id: ElementAsXml
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: ElementAsXml
  nameWithType: ConfigurationElementInterceptor.ElementAsXml
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Hämtar XML-elementet som representeras av den här instansen."
  syntax:
    content: public System.Xml.XmlElement ElementAsXml { get; }
    return:
      type: System.Xml.XmlElement
      description: "XML-element."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  id: OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Hämtar ett värde som anger om ett okänt attribut påträffades under deserialisering. Returnerar alltid <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  remarks: "Den <xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor>klass implementeras specifikt för att hantera godtyckliga, användardefinierade attribut och element.</xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor> Därför kan den här metoden returnerar `true` när .NET Framework identifierar ett okänt element eller attribut för att hålla parsern körs."
  syntax:
    content: protected override bool OnDeserializeUnrecognizedAttribute (string name, string value);
    parameters:
    - id: name
      type: System.String
      description: "Namnet på det okända attributet."
    - id: value
      type: System.String
      description: "Värdet för det okända attributet."
    return:
      type: System.Boolean
      description: "Returnerar alltid <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>, vilket anger att ett okänt attribut har påträffats."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  id: OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: OnDeserializeUnrecognizedElement(String,XmlReader)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Hämtar ett värde som anger om ett okänt element påträffades under deserialisering. Returnerar alltid <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  remarks: "Den <xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor>klass implementeras specifikt för att hantera godtyckliga, användardefinierade attribut och element.</xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor> Därför kan den här metoden returnerar `true` när .NET Framework identifierar ett okänt element eller attribut för att hålla parsern körs."
  syntax:
    content: protected override bool OnDeserializeUnrecognizedElement (string elementName, System.Xml.XmlReader reader);
    parameters:
    - id: elementName
      type: System.String
      description: "Namnet på den okända underelement."
    - id: reader
      type: System.Xml.XmlReader
      description: "XML-läsaren som används för deserialisering."
    return:
      type: System.Boolean
      description: "Returnerar alltid <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>, vilket anger att ett okänt element har påträffats."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: ConfigurationElementInterceptor.Reset(ConfigurationElement)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Återställer det interna tillståndet för den <xref href=&quot;System.IdentityModel.Configuration.ConfigurationElementInterceptor&quot;> </xref> objektet, inklusive Lås och egenskaper för samlingar."
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "Den överordnade noden för konfigurationselementet."
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ConfigurationElementInterceptor()
  nameWithType: ConfigurationElementInterceptor.ConfigurationElementInterceptor()
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ConfigurationElementInterceptor()
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ChildNodes
  nameWithType: ConfigurationElementInterceptor.ChildNodes
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ElementAsXml
  nameWithType: ConfigurationElementInterceptor.ElementAsXml
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
- uid: System.Xml.XmlElement
  parent: System.Xml
  isExternal: false
  name: XmlElement
  nameWithType: XmlElement
  fullName: System.Xml.XmlElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedElement(String,XmlReader)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: ConfigurationElementInterceptor.Reset(ConfigurationElement)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(ConfigurationElement)
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ConfigurationElementInterceptor
  nameWithType: ConfigurationElementInterceptor.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ChildNodes
  nameWithType: ConfigurationElementInterceptor.ChildNodes
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: DeserializeElement
  nameWithType: ConfigurationElementInterceptor.DeserializeElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ElementAsXml
  nameWithType: ConfigurationElementInterceptor.ElementAsXml
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedElement
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: Reset
  nameWithType: ConfigurationElementInterceptor.Reset
