### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.MsmqTransportSecurity
  id: MsmqTransportSecurity
  children:
  - System.ServiceModel.MsmqTransportSecurity.#ctor
  - System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  - System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  - System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  - System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  - System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  langs:
  - csharp
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
  type: Class
  summary: "Klassen MsmqTransportSecurity kapslar in transport säkerhetsinställningarna för köade transporter."
  syntax:
    content: public sealed class MsmqTransportSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqTransportSecurity()
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity()
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass."
  syntax:
    content: public MsmqTransportSecurity ();
    parameters: []
  overload: System.ServiceModel.MsmqTransportSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  id: '#ctor(System.ServiceModel.MsmqTransportSecurity)'
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqTransportSecurity(MsmqTransportSecurity)
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> class, använder en befintlig instans."
  syntax:
    content: public MsmqTransportSecurity (System.ServiceModel.MsmqTransportSecurity other);
    parameters:
    - id: other
      type: System.ServiceModel.MsmqTransportSecurity
      description: "Den befintliga instansen av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass som ska användas i vid initiering av den nya instansen."
  overload: System.ServiceModel.MsmqTransportSecurity.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>other</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  id: MsmqAuthenticationMode
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Hämtar eller anger den <xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;> </xref> som är associerad med den här instansen av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass."
  remarks: "MSMQ kan autentisera meddelanden som skickas till Meddelandeköer som kräver autentisering eller meddelanden kan uttryckligen begära autentisering. Standardläget för autentisering är <xref:System.ServiceModel.MsmqAuthenticationMode>.</xref:System.ServiceModel.MsmqAuthenticationMode>"
  syntax:
    content: public System.ServiceModel.MsmqAuthenticationMode MsmqAuthenticationMode { get; set; }
    return:
      type: System.ServiceModel.MsmqAuthenticationMode
      description: "Den <xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;> </xref> som är associerad med den här instansen av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Värdet är inte en av <xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;> </xref> värden."
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  id: MsmqEncryptionAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Hämtar eller anger den <xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;> </xref> som är associerad med den här instansen av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass."
  remarks: "MSMQ kan kryptera meddelanden på kabeln vid överföring av meddelanden mellan message queue chefer. Standardkrypteringsalgoritmen är <xref:System.ServiceModel.MsmqEncryptionAlgorithm>.</xref:System.ServiceModel.MsmqEncryptionAlgorithm>"
  syntax:
    content: public System.ServiceModel.MsmqEncryptionAlgorithm MsmqEncryptionAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqEncryptionAlgorithm
      description: "Den <xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;> </xref> som är associerad med den här instansen av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Värdet är inte en av <xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;> </xref> värden."
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  id: MsmqProtectionLevel
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Hämtar eller anger den <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> som är associerad med den här instansen av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass."
  remarks: "Standardskyddsnivån är <xref:System.Net.Security.ProtectionLevel>.</xref:System.Net.Security.ProtectionLevel>"
  syntax:
    content: public System.Net.Security.ProtectionLevel MsmqProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "Den <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> som är associerad med den här instansen av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Värdet är inte en av de <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> värden."
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  id: MsmqSecureHashAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Hämtar eller anger den <xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;> </xref> som är associerad med den här instansen av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass."
  remarks: "Standard-hash-algoritmen är <xref:System.ServiceModel.MsmqSecureHashAlgorithm.SHA1>.</xref:System.ServiceModel.MsmqSecureHashAlgorithm.SHA1>"
  syntax:
    content: public System.ServiceModel.MsmqSecureHashAlgorithm MsmqSecureHashAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqSecureHashAlgorithm
      description: "Den <xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;> </xref> som är associerad med den här instansen av den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> klass."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Värdet är inte en av <xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;> </xref> värden."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity()
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity()
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity()
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity(MsmqTransportSecurity)
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqAuthenticationMode
  parent: System.ServiceModel
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqEncryptionAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.MsmqSecureHashAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
