### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebApplicationLevel
  id: WebApplicationLevel
  children:
  - System.Web.Configuration.WebApplicationLevel.AboveApplication
  - System.Web.Configuration.WebApplicationLevel.AtApplication
  - System.Web.Configuration.WebApplicationLevel.BelowApplication
  langs:
  - csharp
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
  type: Enum
  summary: "Anger sökvägen till en konfigurationsfil för webbprogram."
  remarks: "WebApplicationLevel-klassen innehåller tre nivåer som används för att särskilja där en konfigurationsfil är i förhållande till rotnivå på en ASP.NET-webbprogram. De tre typerna för sökvägen nivå är AboveApplication, AtApplication och BelowApplication."
  syntax:
    content: public enum WebApplicationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  id: AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att konfigurationsfilen är i en global katalog i förhållande till det aktuella ASP.NET-webbprogrammet."
  syntax:
    content: AboveApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  id: AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att konfigurationsfilen är i rotkatalogen för det aktuella ASP.NET-webbprogrammet."
  syntax:
    content: AtApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  id: BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att konfigurationsfilen är i en underkatalog för det aktuella ASP.NET-webbprogrammet."
  syntax:
    content: BelowApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
- uid: System.Web.Configuration.WebApplicationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
