### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  id: MachineKeyCompatibilityMode
  children:
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  langs:
  - csharp
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
  type: Enum
  summary: "Anger vilken krypteringsmetod kan användas."
  remarks: "Du använder MachineKeyCompatibilityMode värden när du ställer in den <xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>egenskapen.</xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>"
  syntax:
    content: public enum MachineKeyCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  id: Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Använd krypteringsmetod som implementerats i .NET Framework-versioner tidigare än version 2.0 Service Pack 2. Initieringen angreppsmetoderna (IV: N) används för alla krypteringsåtgärder förutom lagra krypterade lösenord i databasen för ASP.NET-medlemskap."
  syntax:
    content: Framework20SP1
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  id: Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Använda starkare krypteringsmetoder som är tillgängliga i .NET Framework version 2.0 SP2 och senare versioner. Initieringen angreppsmetoderna (IV: N) används för alla krypteringsåtgärder för."
  syntax:
    content: Framework20SP2
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  id: Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Använd kryptering som är tillgängliga i .NET Framework version 4.5 eller senare versioner. Jämfört med krypteringsmetod som används för Framework20SP1 och Framework20SP2 ciphertext som genereras av standard kryptografimetoder är något mindre och mer robust mot vissa typer av teoretisk attacker. De också integreras med [!INCLUDE[win8](~/add/includes/ajax-current-ext-md.md)] directory nyckelhantering för att få nödvändiga kryptografiska nycklar. Det här alternativet kan du ange anpassade kryptografimetoder genom att skriva en klass som härleds från <xref href=&quot;System.Security.Cryptography.DataProtector&quot;> </xref> och ange namnet i den &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; egenskapen.       Följande konfigurationskrav som gäller för det här alternativet: 1. Om den &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; egenskap har ett värde i &lt;xref:System.Web.Configuration.MachineKeySection.ApplicationName%2A?displayProperty=fullName&gt; egenskapen måste också ha ett värde.       2. Den &lt;xref:System.Web.Configuration.MachineKeySection.Validation%2A?displayProperty=fullName&gt; attributet måste ange en systemdefinierade verifieringsalgoritm (till exempel MD5, SHA1, HMACSHA256, HMACSHA384 eller HMACSHA512) eller en algoritm för anpassad verifiering i en klass som härleds från den <xref href=&quot;System.Security.Cryptography.KeyedHashAlgorithm&quot;> </xref> klass. Värdena AES och 3DES är inte verifieringen algoritmer.       När du anger det här alternativet biljetter för formulärautentisering är alltid både krypterad och signerad, oavsett värde för den &lt;xref:System.Web.Configuration.FormsAuthenticationConfiguration.Protection%2A?displayProperty=fullName&gt; egenskapen. Visa tillstånd är också både krypterad och signerad om en sida <> </> *> egenskapen är <code> true </code> eller <> </> *> egenskapen är <xref:System.Web.UI.ViewStateEncryptionMode.Always>.</xref:System.Web.UI.ViewStateEncryptionMode.Always>"
  syntax:
    content: Framework45
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
