### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.IApplicationTrustManager
  id: IApplicationTrustManager
  children:
  - System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  langs:
  - csharp
  name: IApplicationTrustManager
  nameWithType: IApplicationTrustManager
  fullName: System.Security.Policy.IApplicationTrustManager
  type: Interface
  summary: "Avgör om ett program ska köras och vilken uppsättning behörigheter ska beviljas."
  remarks: "Förtroende chefer måste implementera gränssnittet IApplicationTrustManager. Värd-anrop i <xref:System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust%2A?displayProperty=fullName>metod för att fastställa om ett program ska köras och vilka behörigheter ska beviljas åtkomst till programmet.</xref:System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust%2A?displayProperty=fullName>       I den [!INCLUDE[net_v40_long](~/add/includes/net-v40-long-md.md)] och senare, det finns endast en trust manager, som kan vara en anpassad implementering av gränssnittet IApplicationTrustManager. Trust manager standardimplementering frågar användaren om behörighet att installera programmet och för att höja behörigheterna för programmet. Andra trust manager-implementeringar kan innehålla olika användarupplevelser. En implementering kan till exempel kontrollera en enterprise-lista för betrodda program i stället för att fråga användaren för den informationen."
  example:
  - "The following example shows a simple implementation of IApplicationTrustManager.  \n  \n [!code-cs[System.Security.Policy.IApplicationTrustManager#1](~/add/codesnippet/csharp/t-system.security.policy_3_1.cs)]\n [!code-vb[System.Security.Policy.IApplicationTrustManager#1](~/add/codesnippet/visualbasic/t-system.security.policy_3_1.vb)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public interface IApplicationTrustManager : System.Security.ISecurityEncodable
  implements:
  - System.Security.ISecurityEncodable
  platform:
  - net462
- uid: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  id: DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  parent: System.Security.Policy.IApplicationTrustManager
  langs:
  - csharp
  name: DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  nameWithType: IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  fullName: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Avgör om ett program ska köras och vilken uppsättning behörigheter ska beviljas."
  remarks: "DetermineApplicationTrust-metoden anropas av värden för att avgöra om ett program ska köras och som angetts av behörigheter beviljas. DetermineApplicationTrust returnerar ett <xref:System.Security.Policy.ApplicationTrust>objekt med en <xref:System.Security.Policy.ApplicationTrust.DefaultGrantSet%2A>som innehåller en behörighet egenskapsuppsättning som representerar behörigheterna som ska tilldelas varje sammansättning som körs inom kontexten för programmet.</xref:System.Security.Policy.ApplicationTrust.DefaultGrantSet%2A> </xref:System.Security.Policy.ApplicationTrust> Beviljad behörigheterna gäller inte för sammansättningar i den globala sammansättningscachen. Den <xref:System.Security.Policy.ApplicationTrust>-objekt har också en <xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A>egenskap som hanteraren förtroende anger för att ange om programmet ska vara betrodd.</xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A> </xref:System.Security.Policy.ApplicationTrust> Om trust manager indikerar att programmet är betrodd, värden aktiverar programmet och beviljar dess sammansättningar uppsättning behörigheter som finns i den <xref:System.Security.Policy.ApplicationTrust>samling.</xref:System.Security.Policy.ApplicationTrust>"
  example:
  - "The following example shows an implementation of the DetermineApplicationTrust method for a custom trust manager. This code example is part of a larger example provided for the <xref:System.Security.Policy.IApplicationTrustManager> interface.  \n  \n [!code-cs[System.Security.Policy.IApplicationTrustManager#2](~/add/codesnippet/csharp/24b6db65-f82b-47e4-ac93-_1.cs)]\n [!code-vb[System.Security.Policy.IApplicationTrustManager#2](~/add/codesnippet/visualbasic/24b6db65-f82b-47e4-ac93-_1.vb)]"
  syntax:
    content: public System.Security.Policy.ApplicationTrust DetermineApplicationTrust (ActivationContext activationContext, System.Security.Policy.TrustManagerContext context);
    parameters:
    - id: activationContext
      type: System.ActivationContext
      description: "Aktiveringskontexten för programmet."
    - id: context
      type: System.Security.Policy.TrustManagerContext
      description: "Trust manager kontext för programmet."
    return:
      type: System.Security.Policy.ApplicationTrust
      description: "Ett objekt som innehåller säkerhet beslut om programmet."
  overload: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  parent: System.Security.Policy.IApplicationTrustManager
  isExternal: false
  name: DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  nameWithType: IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  fullName: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
- uid: System.Security.Policy.ApplicationTrust
  parent: System.Security.Policy
  isExternal: false
  name: ApplicationTrust
  nameWithType: ApplicationTrust
  fullName: System.Security.Policy.ApplicationTrust
- uid: System.ActivationContext
  parent: System
  isExternal: false
  name: ActivationContext
  nameWithType: ActivationContext
  fullName: System.ActivationContext
- uid: System.Security.Policy.TrustManagerContext
  parent: System.Security.Policy
  isExternal: false
  name: TrustManagerContext
  nameWithType: TrustManagerContext
  fullName: System.Security.Policy.TrustManagerContext
- uid: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust*
  parent: System.Security.Policy.IApplicationTrustManager
  isExternal: false
  name: DetermineApplicationTrust
  nameWithType: IApplicationTrustManager.DetermineApplicationTrust
