### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement
  id: NetMsmqSecurityElement
  children:
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  langs:
  - csharp
  name: NetMsmqSecurityElement
  nameWithType: NetMsmqSecurityElement
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement
  type: Class
  summary: "Klassen NetMsmqSecurityElement kapslar in MSMQ säkerhetsfunktioner när du använder den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> bindning."
  remarks: "Objekt av den här typen har skapats genom att skapa en instans av den <xref:System.ServiceModel.NetMsmqBinding>bindning.</xref:System.ServiceModel.NetMsmqBinding> Du kan sedan använda det här objektet för att referera till alla de olika säkerhetsinställningarna som rör den <xref:System.ServiceModel.NetMsmqBinding>bindning.</xref:System.ServiceModel.NetMsmqBinding>"
  syntax:
    content: 'public sealed class NetMsmqSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: NetMsmqSecurityElement()
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement()
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.NetMsmqSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.NetMsmqSecurityElement&quot;> </xref> klass."
  syntax:
    content: public NetMsmqSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  id: Message
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar den <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> -instans som är associerad med den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> bindning."
  remarks: "Den <xref:System.ServiceModel.MessageSecurityOverMsmq>instans kapslar in säkerhetsinställningar för SOAP-meddelande.</xref:System.ServiceModel.MessageSecurityOverMsmq>"
  syntax:
    content: public System.ServiceModel.Configuration.MessageSecurityOverMsmqElement Message { get; }
    return:
      type: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
      description: "Den <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> -instans som är associerad med den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> bindning."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger den <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> -instans som är associerad med den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> bindning."
  remarks: "Den här egenskapen anger typ av säkerhet som används av den associerade `NetMsmqBinding`. I följande lista beskrivs godkända värden:- `None` -ingen säkerhet kommer att användas.      - `Transport` -Transportsäkerhet kommer att användas.      - `Message` -Meddelandebaserad säkerhet kommer att användas.      - `Both` -Kommer att användas både meddelandebaserad säkerhets- och säkerhet."
  syntax:
    content: public System.ServiceModel.NetMsmqSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetMsmqSecurityMode
      description: "Den <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> -instans som är associerad med den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> bindning."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar den <xref href=&quot;System.ServiceModel.Configuration.MsmqTransportSecurityElement&quot;> </xref> element som är associerad med den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> bindning."
  remarks: "Den här egenskapen ger åtkomst till Msmq-Transportsäkerhetsinställningar."
  syntax:
    content: public System.ServiceModel.Configuration.MsmqTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.MsmqTransportSecurityElement
      description: "Den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> -instans som är associerad med den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> bindning."
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: NetMsmqSecurityElement()
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement()
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.NetMsmqSecurityElement()
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
- uid: System.ServiceModel.NetMsmqSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetMsmqSecurityMode
  nameWithType: NetMsmqSecurityMode
  fullName: System.ServiceModel.NetMsmqSecurityMode
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MsmqTransportSecurityElement
  nameWithType: MsmqTransportSecurityElement
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: NetMsmqSecurityElement
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
