### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AsyncPreloadModeFlags
  id: AsyncPreloadModeFlags
  children:
  - System.Web.Configuration.AsyncPreloadModeFlags.All
  - System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
  - System.Web.Configuration.AsyncPreloadModeFlags.Form
  - System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
  - System.Web.Configuration.AsyncPreloadModeFlags.None
  - System.Web.Configuration.AsyncPreloadModeFlags.NonForm
  langs:
  - csharp
  name: AsyncPreloadModeFlags
  nameWithType: AsyncPreloadModeFlags
  fullName: System.Web.Configuration.AsyncPreloadModeFlags
  type: Enum
  summary: "Anger läget för en asynkron begäran."
  syntax:
    content: >-
      [System.Flags]

      public enum AsyncPreloadModeFlags
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.AsyncPreloadModeFlags.All
  id: All
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: All
  nameWithType: AsyncPreloadModeFlags.All
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynkron överföringar av entiteten begärandetexten sker för alla poster."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
  id: AllFormTypes
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: AllFormTypes
  nameWithType: AsyncPreloadModeFlags.AllFormTypes
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynkron överföringar av entiteten begärandetexten sker endast för formuläret meddelandena."
  syntax:
    content: AllFormTypes
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AsyncPreloadModeFlags.Form
  id: Form
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: Form
  nameWithType: AsyncPreloadModeFlags.Form
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.Form
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynkron överföringar av entiteten begärandetexten sker endast för formuläret meddelandena. Den här flaggan gör asynkron förinläsning för MIME-typer som har angetts till `application/x-www-form-urlencoded`."
  syntax:
    content: Form
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
  id: FormMultiPart
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: FormMultiPart
  nameWithType: AsyncPreloadModeFlags.FormMultiPart
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynkron överföringar av entiteten begärandetexten sker endast för flera delar formulärdata. Den här flaggan gör asynkron förinläsning för MIME-typer som har angetts till `multipart/form-data`."
  syntax:
    content: FormMultiPart
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AsyncPreloadModeFlags.None
  id: None
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: None
  nameWithType: AsyncPreloadModeFlags.None
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Inga asynkron överföring av entiteten begärandetexten sker."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AsyncPreloadModeFlags.NonForm
  id: NonForm
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: NonForm
  nameWithType: AsyncPreloadModeFlags.NonForm
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.NonForm
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynkron överföringar av entiteten begärandetexten sker endast för icke-formuläret meddelandena."
  syntax:
    content: NonForm
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.AsyncPreloadModeFlags.All
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: All
  nameWithType: AsyncPreloadModeFlags.All
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.All
- uid: System.Web.Configuration.AsyncPreloadModeFlags
  parent: System.Web.Configuration
  isExternal: false
  name: AsyncPreloadModeFlags
  nameWithType: AsyncPreloadModeFlags
  fullName: System.Web.Configuration.AsyncPreloadModeFlags
- uid: System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: AllFormTypes
  nameWithType: AsyncPreloadModeFlags.AllFormTypes
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
- uid: System.Web.Configuration.AsyncPreloadModeFlags.Form
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: Form
  nameWithType: AsyncPreloadModeFlags.Form
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.Form
- uid: System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: FormMultiPart
  nameWithType: AsyncPreloadModeFlags.FormMultiPart
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
- uid: System.Web.Configuration.AsyncPreloadModeFlags.None
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: None
  nameWithType: AsyncPreloadModeFlags.None
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.None
- uid: System.Web.Configuration.AsyncPreloadModeFlags.NonForm
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: NonForm
  nameWithType: AsyncPreloadModeFlags.NonForm
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.NonForm
