### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.AppSettingsExpressionEditor
  id: AppSettingsExpressionEditor
  children:
  - System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  - System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  - System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  langs:
  - csharp
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor
  type: Class
  summary: "Ger egenskaper och metoder för att utvärdera och redigera ett program inställningen uttryck i en fil vid designtillfället."
  remarks: "AppSettingsExpressionEditor klassen härleds från den <xref:System.Web.UI.Design.ExpressionEditor>klassen och tillhandahåller en implementering för utvärdering och associera en referens för inställning av program med en kontrollegenskap i designläge.</xref:System.Web.UI.Design.ExpressionEditor> T.ex, du kan binda värdet för en egenskapskontroll till programmet inställningen uttrycket `AppSettings:mySettingKeyName`, vilket anger att kontrollen egenskapens värde har angetts med hjälp av den `mySettingKeyName` värde i den `appSettings` avsnitt i Webbkonfigurationsfilen.       En visuell designer värd som [!INCLUDE[vsprvslong](~/add/includes/ajax-current-ext-md.md)], använder du klassen AppSettingsExpressionEditor för att välja en tillämpningsinställning från den `appSettings` konfigurationsavsnittet, och sedan utvärderar det valda uttrycket för designtid återgivning.       När du bläddrar till den <xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A>egenskapen för en kontroll i rutnätet designegenskaperna den visuella designern visas en dialogruta för set-uttryck som ger en egenskapskontroll körning-värde.</xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A> Du kan välja uttryckstypen baserat på en lista över uttryck prefix. När du väljer den **AppSettings** uttrycksprefixet listan visuell designer värden använder den associerade <xref:System.Web.UI.Design.ExpressionEditorSheet>objekt att tillhandahålla designläge redigera funktioner för `appSettings` uttryck och använder AppSettingsExpressionEditor metoder för att utvärdera och konvertera Uttryckssträngen baserat på syntaxen för ett uttryck för inställning av programmet.</xref:System.Web.UI.Design.ExpressionEditorSheet> Den visuella designern värden använder utvärderade uttryckresultatet för att tilldela kontrollen egenskapsvärden som renderas i designvyn.       Den <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>objektets AppSettingsExpressionEditor returnerar strängen `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> Den <xref:System.Web.Compilation.AppSettingsExpressionBuilder>klass är associerad med uttrycksprefixet `AppSettings` och AppSettingsExpressionEditor genomförandet.</xref:System.Web.Compilation.AppSettingsExpressionBuilder>       Den <xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A>metoden utvärderar en indataappen inställningen uttryckssträng.</xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A> Den <xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>metoden returnerar den <xref:System.Web.UI.Design.ExpressionEditorSheet>-implementering som används för att ange och redigera program inställningen uttryck.</xref:System.Web.UI.Design.ExpressionEditorSheet> </xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>"
  example:
  - "The following code example demonstrates how to bind the <xref:System.Web.UI.WebControls.HyperLink.NavigateUrl%2A> property of a <xref:System.Web.UI.WebControls.HyperLink> control to an application setting expression using the AppSettingsExpressionEditor object.  \n  \n1.  In a Web Forms project, add `MyHyperLinkSetting` to the `<appSettings>` section of the web.config file.  \n  \n     [!code-xml[ControlsUsingExpressions#5](~/add/codesnippet/xml/t-system.web.ui.design.a_1.xml)]  \n  \n2.  On a Web Forms page, add a <xref:System.Web.UI.WebControls.HyperLink> control.  \n  \n3.  For the `Hyperlink` control, in Properties, click **Expressions**, and then click the ellipsis button (**...**).  \n  \n     The `<Hyperlinkname>`**Expression** dialog box appears.  \n  \n4.  Under **Bindable properties**, click **NavigateUrl**, in the **Expression type** list, click **AppSettings**, and then under **Expression properties**, in the **AppSetting** box, type **MyHyperLinkSetting**.  \n  \n The visual designer uses the AppSettingsExpressionEditor to assign the expression for the `NavigateUrl` property.  \n  \n The following aspx source shows an example of a property value set using an application setting expression.  \n  \n [!code-vb[ControlsUsingExpressions#2](~/add/codesnippet/visualbasic/t-system.web.ui.design.a_2.aspx)]\n [!code-cs[ControlsUsingExpressions#2](~/add/codesnippet/csharp/t-system.web.ui.design.a_2.aspx)]\n [!code-xml[ControlsUsingExpressions#2](~/add/codesnippet/xml/t-system.web.ui.design.a_2.xml)]"
  syntax:
    content: 'public class AppSettingsExpressionEditor : System.Web.UI.Design.ExpressionEditor'
  inheritance:
  - System.Object
  - System.Web.UI.Design.ExpressionEditor
  implements: []
  inheritedMembers:
  - System.Web.UI.Design.ExpressionEditor.ExpressionPrefix
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.String,System.IServiceProvider)
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.Type,System.IServiceProvider)
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  id: '#ctor'
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  type: Constructor
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Initierar en ny instans av den <xref href=&quot;System.Web.UI.Design.AppSettingsExpressionEditor&quot;> </xref> klass."
  remarks: "En instans av den <xref:System.Web.UI.Design.AppSettingsExpressionEditor>klass har konfigurerats av basklassen tillsammans med den <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>egenskapen `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> </xref:System.Web.UI.Design.AppSettingsExpressionEditor>"
  syntax:
    content: public AppSettingsExpressionEditor ();
    parameters: []
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  id: EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Utvärderar ett program inställningen uttryckssträng samt design-time-värde för egenskap för en kontroll."
  remarks: "Metoden EvaluateExpression letar upp inställningen som anges av `expression`, och returnerar sedan värdet för inställningen.       Den visuella frågedesignern används metoden EvaluateExpression för att utvärdera ett uttryck för inställning av program och ger en associerad kontrollegenskap designläge-värde. Den visuella designern anropar metoden EvaluateExpression med Uttryckssträngen och använder utvärderade uttryckresultatet för att tilldela behörighet egenskapsvärden som renderas i designvyn.       Vid körning, sidan parsern använder den <xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>och <xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A>metoder för motsvarande <xref:System.Web.Compilation.AppSettingsExpressionBuilder>implementeringen för att utvärdera uttryck och ange värdet för körning för en associerad kontrollegenskap.</xref:System.Web.Compilation.AppSettingsExpressionBuilder> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>"
  syntax:
    content: public override object EvaluateExpression (string expression, object parseTimeData, Type propertyType, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "Ett program inställningen uttryckssträng att utvärdera. `expression`innehåller inte den <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> uttrycksprefixet."
    - id: parseTimeData
      type: System.Object
      description: "Ett objekt som innehåller ytterligare tolkning information för att utvärdera `expression`."
    - id: propertyType
      type: System.Type
      description: "Egenskapen kontrolltypen."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "En service provider implementering tillhandahålls av designer värden för att hämta ytterligare tjänster i designläge."
    return:
      type: System.Object
      description: "Objektet som refereras av <code> expression </code>om utvärdering av uttryck lyckades annars <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  id: GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Returnerar ett uttryck editor blad för ett uttryck för inställning av programmet."
  remarks: "Metoden GetExpressionEditorSheet returnerar en vanlig redigerare blad-implementering som använder en enda Indatasträngen för att bilda uttrycket."
  syntax:
    content: public override System.Web.UI.Design.ExpressionEditorSheet GetExpressionEditorSheet (string expression, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "Uttryckssträngen som anges för en kontrollegenskap som används för att initiera uttryck editor blad. `expression`innehåller inte den <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> uttrycksprefixet."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "En service provider implementering tillhandahålls av designer värden för att hämta ytterligare tjänster i designläge."
    return:
      type: System.Web.UI.Design.ExpressionEditorSheet
      description: "En <xref href=&quot;System.Web.UI.Design.ExpressionEditorSheet&quot;> </xref> implementering som definierar programegenskaper inställningen uttryck."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.Design.ExpressionEditor
  isExternal: false
  name: System.Web.UI.Design.ExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.IServiceProvider
  parent: System
  isExternal: true
  name: IServiceProvider
  nameWithType: IServiceProvider
  fullName: System.IServiceProvider
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
- uid: System.Web.UI.Design.ExpressionEditorSheet
  parent: System.Web.UI.Design
  isExternal: false
  name: ExpressionEditorSheet
  nameWithType: ExpressionEditorSheet
  fullName: System.Web.UI.Design.ExpressionEditorSheet
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet
