### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyValidation
  id: MachineKeyValidation
  children:
  - System.Web.Configuration.MachineKeyValidation.AES
  - System.Web.Configuration.MachineKeyValidation.Custom
  - System.Web.Configuration.MachineKeyValidation.HMACSHA256
  - System.Web.Configuration.MachineKeyValidation.HMACSHA384
  - System.Web.Configuration.MachineKeyValidation.HMACSHA512
  - System.Web.Configuration.MachineKeyValidation.MD5
  - System.Web.Configuration.MachineKeyValidation.SHA1
  - System.Web.Configuration.MachineKeyValidation.TripleDES
  langs:
  - csharp
  name: MachineKeyValidation
  nameWithType: MachineKeyValidation
  fullName: System.Web.Configuration.MachineKeyValidation
  type: Enum
  summary: "Anger hash-algoritm som används av ASP.NET för formulär för autentisering och för att validera data med visningsstatus och för identifiering av processexternt sessionstillstånd."
  remarks: "ASP.NET använder en hashbaserad meddelandeautentiseringskod (HMAC) för att identifiera om data som används för formulär autentisering eller visa tillstånd har ändrats med. HMAC genereras när Visa tillstånd innehåll skapas och HMAC är markerat på efterföljande förfrågningar. HMAC hjälper ASP.NET avgöra om någon har ändrat data som skickas mellan servern och klienten, men data kan läsas av alla medan de överförs via Internet, om den är krypterad. Som standard är visningsstatus valideras men inte krypterade. Mer information finns i <xref:System.Web.UI.Page.ViewStateEncryptionMode%2A>och <xref:System.Web.UI.Page.RegisterRequiresViewStateEncryption%2A>.</xref:System.Web.UI.Page.RegisterRequiresViewStateEncryption%2A> </xref:System.Web.UI.Page.ViewStateEncryptionMode%2A>       Uppräkningen MachineKeyValidation kan du ange en algoritm som används för att skapa HMAC av ASP.NET. Standardvärdet är HMACSHA256. ASP.NET använder värdet för den <xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>egenskapen med den valda algoritmen för att generera HMAC.</xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>"
  example:
  - "The following code example shows how to use the MachineKeyValidation enumeration. In the example, `configSection` is an instance of <xref:System.Web.Configuration.MachineKeySection>.This code example is part of a larger example provided for the <xref:System.Web.Configuration.MachineKeySection> class.  \n  \n [!code-vb[System.Web.Configuration.MachineKeySection#5](~/add/codesnippet/visualbasic/t-system.web.configurati_93_1.vb)]\n [!code-cs[System.Web.Configuration.MachineKeySection#5](~/add/codesnippet/csharp/t-system.web.configurati_93_1.cs)]"
  syntax:
    content: public enum MachineKeyValidation
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.AES
  id: AES
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: AES
  nameWithType: MachineKeyValidation.AES
  fullName: System.Web.Configuration.MachineKeyValidation.AES
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att ASP.NET använder den <xref uid=&quot;langword_csharp_AES&quot; name=&quot;AES&quot; href=&quot;&quot;> </xref> (Rijndael) krypteringsalgoritm."
  remarks: "Välj det här alternativet om du vill kryptera visningsstatus i ditt webbprogram. Om du väljer det här alternativet den <xref:System.Web.Configuration.MachineKeySection.DecryptionKey%2A>egenskapen ska användas för kryptering och dekryptering, och `HMACSHA1` hash-algoritm som ska användas med den <xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A>egenskapen för verifiering.</xref:System.Web.Configuration.MachineKeySection.ValidationKey%2A> </xref:System.Web.Configuration.MachineKeySection.DecryptionKey%2A>"
  syntax:
    content: AES
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.Custom
  id: Custom
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: Custom
  nameWithType: MachineKeyValidation.Custom
  fullName: System.Web.Configuration.MachineKeyValidation.Custom
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att ASP.NET använder en anpassad hash-algoritm."
  remarks: "Anpassade hash-algoritm kan implementeras i en klass som härleds från <xref:System.Security.Cryptography.KeyedHashAlgorithm>.</xref:System.Security.Cryptography.KeyedHashAlgorithm>       Anpassade algoritmen anges normalt deklarativt i attributet validering av element i formatet `alg:` *algorithm_name*. Information om hur du anger en anpassad algoritm i koden finns i <xref:System.Web.Configuration.MachineKeySection.ValidationAlgorithm%2A?displayProperty=fullName>egenskap.</xref:System.Web.Configuration.MachineKeySection.ValidationAlgorithm%2A?displayProperty=fullName>"
  syntax:
    content: Custom
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  id: HMACSHA256
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA256
  nameWithType: MachineKeyValidation.HMACSHA256
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att ASP.NET använder den <xref uid=&quot;langword_csharp_HMACSHA256&quot; name=&quot;HMACSHA256&quot; href=&quot;&quot;> </xref> hash-algoritm.  Detta är standardvärdet."
  remarks: '`HMACSHA256`är en SHA2 hash-algoritm som genererar en 256-bitars Hashkod.'
  syntax:
    content: HMACSHA256
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  id: HMACSHA384
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA384
  nameWithType: MachineKeyValidation.HMACSHA384
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att ASP.NET använder den <xref uid=&quot;langword_csharp_HMACSHA384&quot; name=&quot;HMACSHA384&quot; href=&quot;&quot;> </xref> hash-algoritm."
  remarks: '`HMACSHA384`är en SHA2 hash-algoritm som genererar en 384-bitars hash-kod. Det här alternativet är tillgängligt för program som kräver högre säkerhet än tillhandahålls av den `HMACSHA256`algoritmen.'
  syntax:
    content: HMACSHA384
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  id: HMACSHA512
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: HMACSHA512
  nameWithType: MachineKeyValidation.HMACSHA512
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att ASP.NET använder den <xref uid=&quot;langword_csharp_HMACSHA512&quot; name=&quot;HMACSHA512&quot; href=&quot;&quot;> </xref> hash-algoritm."
  remarks: '`HMACSHA512`är en SHA2 hash-algoritm som genererar en 512-bitars hash-kod. Det här alternativet är tillgängligt för program som kräver högre säkerhet än tillhandahålls av den `HMACSHA384` algoritmen.'
  syntax:
    content: HMACSHA512
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.MD5
  id: MD5
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: MD5
  nameWithType: MachineKeyValidation.MD5
  fullName: System.Web.Configuration.MachineKeyValidation.MD5
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att ASP.NET använder Message Digest 5 (<xref uid=&quot;langword_csharp_MD5&quot; name=&quot;MD5&quot; href=&quot;&quot;></xref>) hash-algoritm."
  remarks: '`MD5`är en hash-algoritm som genererar ett 128-bitars hash-värde. Det här alternativet ingår i äldre syfte och bör endast välja om kompatibilitet med tidigare versioner av ASP.NET krävs.'
  syntax:
    content: MD5
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.SHA1
  id: SHA1
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: SHA1
  nameWithType: MachineKeyValidation.SHA1
  fullName: System.Web.Configuration.MachineKeyValidation.SHA1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att ASP.NET använder den <xref uid=&quot;langword_csharp_HMACSHA1&quot; name=&quot;HMACSHA1&quot; href=&quot;&quot;> </xref> hash-algoritm."
  remarks: '`HMACSHA1`är en hash-algoritm som genererar ett 160-bitars hash-värde. Det här alternativet ingår i äldre syfte och bör endast välja om kompatibilitet med tidigare versioner av ASP.NET krävs.'
  syntax:
    content: SHA1
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyValidation.TripleDES
  id: TripleDES
  parent: System.Web.Configuration.MachineKeyValidation
  langs:
  - csharp
  name: TripleDES
  nameWithType: MachineKeyValidation.TripleDES
  fullName: System.Web.Configuration.MachineKeyValidation.TripleDES
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att ASP.NET använder TripleDES (<xref uid=&quot;langword_csharp_3DES&quot; name=&quot;3DES&quot; href=&quot;&quot;></xref>) krypteringsalgoritm."
  remarks: "TripleDES är en krypteringsalgoritm som används bara om du anger att visa status är krypterad. Det här alternativet ingår i äldre syfte och bör endast välja om kompatibilitet med tidigare versioner av ASP.NET krävs."
  syntax:
    content: TripleDES
    return:
      type: System.Web.Configuration.MachineKeyValidation
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyValidation.AES
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: AES
  nameWithType: MachineKeyValidation.AES
  fullName: System.Web.Configuration.MachineKeyValidation.AES
- uid: System.Web.Configuration.MachineKeyValidation
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyValidation
  nameWithType: MachineKeyValidation
  fullName: System.Web.Configuration.MachineKeyValidation
- uid: System.Web.Configuration.MachineKeyValidation.Custom
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: Custom
  nameWithType: MachineKeyValidation.Custom
  fullName: System.Web.Configuration.MachineKeyValidation.Custom
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA256
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA256
  nameWithType: MachineKeyValidation.HMACSHA256
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA256
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA384
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA384
  nameWithType: MachineKeyValidation.HMACSHA384
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA384
- uid: System.Web.Configuration.MachineKeyValidation.HMACSHA512
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: HMACSHA512
  nameWithType: MachineKeyValidation.HMACSHA512
  fullName: System.Web.Configuration.MachineKeyValidation.HMACSHA512
- uid: System.Web.Configuration.MachineKeyValidation.MD5
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: MD5
  nameWithType: MachineKeyValidation.MD5
  fullName: System.Web.Configuration.MachineKeyValidation.MD5
- uid: System.Web.Configuration.MachineKeyValidation.SHA1
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: SHA1
  nameWithType: MachineKeyValidation.SHA1
  fullName: System.Web.Configuration.MachineKeyValidation.SHA1
- uid: System.Web.Configuration.MachineKeyValidation.TripleDES
  parent: System.Web.Configuration.MachineKeyValidation
  isExternal: false
  name: TripleDES
  nameWithType: MachineKeyValidation.TripleDES
  fullName: System.Web.Configuration.MachineKeyValidation.TripleDES
