### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProvider
  id: SettingsProvider
  children:
  - System.Configuration.SettingsProvider.#ctor
  - System.Configuration.SettingsProvider.ApplicationName
  - System.Configuration.SettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  - System.Configuration.SettingsProvider.SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  langs:
  - csharp
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
  type: Class
  summary: "Fungerar som en basklass för härledda inställningar för anpassade providrar på programarkitektur för inställningar."
  remarks: "En inställningar leverantör definierar mekanismen för att lagra konfigurationsdata som används i programarkitektur för inställningar. .NET Framework innehåller en enda inställningar standardprovider, <xref:System.Configuration.LocalFileSettingsProvider>, som lagrar konfigurationsdata till det lokala filsystemet.</xref:System.Configuration.LocalFileSettingsProvider> Du kan dock skapa alternativa lagringsgruppen mekanismer som härleds från en abstrakt klass SettingsProvider. Den provider som använder en adapterklass bestäms av pynta vinjettklass med <xref:System.Configuration.SettingsProviderAttribute>.</xref:System.Configuration.SettingsProviderAttribute> Om det här attributet inte anges, standard, <xref:System.Configuration.LocalFileSettingsProvider>, används.</xref:System.Configuration.LocalFileSettingsProvider>       När du skapar en provider för anpassade inställningar, åtminstone, måste du ange implementeringar för de tre metoderna för den här klassen: <xref:System.Configuration.SettingsProvider.GetPropertyValues%2A>och <xref:System.Configuration.SettingsProvider.SetPropertyValues%2A> <xref:System.Configuration.SettingsProvider.ApplicationName%2A>.</xref:System.Configuration.SettingsProvider.ApplicationName%2A> </xref:System.Configuration.SettingsProvider.SetPropertyValues%2A> </xref:System.Configuration.SettingsProvider.GetPropertyValues%2A>       För program, du kan lägga till mer standardiserad funktionalitet en anpassad provider genom att implementera även de <xref:System.Configuration.IApplicationSettingsProvider>gränssnitt.</xref:System.Configuration.IApplicationSettingsProvider> Det här gränssnittet speglar metoder som finns i den <xref:System.Configuration.ApplicationSettingsBase>-klassen, som främst aktiverar stöd för versionshantering.</xref:System.Configuration.ApplicationSettingsBase>       Normalt bör du utforma inställningar leverantörer att vara en instanced att undvika resurskonflikter för lagring. Leverantörer bör också vara trådsäkra eftersom de kan anropas samtidigt från flera wrapper-instanser i en enda domän eller från flera program i olika domäner.       Minst en inställningsprovider måste identifiera tre attribut –<xref:System.Configuration.ApplicationScopedSettingAttribute>, <xref:System.Configuration.UserScopedSettingAttribute>, och <xref:System.Configuration.DefaultSettingValueAttribute>.</xref:System.Configuration.DefaultSettingValueAttribute> </xref:System.Configuration.UserScopedSettingAttribute> </xref:System.Configuration.ApplicationScopedSettingAttribute> En fullständig lista över attribut som kan tillämpas på programinställningar finns [inställningar Programattribut](~/add/includes/ajax-current-ext-md.md). En anpassad inställning provider ska matcha attribut som tillämpas på Egenskaper på följande sätt: 1.  Om providern kan uppfylla begäran underförstås av attributet, bör naturligtvis den göra detta.      2.  Om providern inte kan uppfylla begäran, bör det ignorerar den tyst.      3.  Om två eller flera egenskaper i konflikt; till exempel en egenskap som dekorerad med båda <xref:System.Configuration.ApplicationScopedSettingAttribute>och <xref:System.Configuration.UserScopedSettingAttribute>; providern utlösa <xref:System.Configuration.ConfigurationException>.</xref:System.Configuration.ConfigurationException> </xref:System.Configuration.UserScopedSettingAttribute> </xref:System.Configuration.ApplicationScopedSettingAttribute>"
  syntax:
    content: 'public abstract class SettingsProvider : System.Configuration.Provider.ProviderBase'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.Provider.ProviderBase.Name
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: SettingsProvider()
  nameWithType: SettingsProvider.SettingsProvider()
  fullName: System.Configuration.SettingsProvider.SettingsProvider()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initierar en instans av den <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> klass."
  remarks: "Det här är den här skyddade standardkonstruktor för den här abstrakta klassen. Anpassade inställningar för härledda providers behöver inte ange en explicit konstruktor eftersom den <xref:System.Configuration.Provider.ProviderBase.Initialize%2A>metoden utför vanligtvis alla initiering.</xref:System.Configuration.Provider.ProviderBase.Initialize%2A>       Klientkod vanligtvis inte direkt skapa en instans av en leverantör av inställningar. i stället du använder följande procedur för att hitta en inställningsprovider för en viss inställningsegenskapen: 1.  Anropa <xref:System.ComponentModel.Component.GetService%2A>metoden i det aktuella <xref:System.ComponentModel.Component>eller för <xref:System.ComponentModel.ISite>att returnera en referens till aktuellt <xref:System.Configuration.ISettingsProviderService>.</xref:System.Configuration.ISettingsProviderService> </xref:System.ComponentModel.ISite> </xref:System.ComponentModel.Component> </xref:System.ComponentModel.Component.GetService%2A>      2.  Anropa den <xref:System.Configuration.ISettingsProviderService.GetSettingsProvider%2A>metod för den <xref:System.Configuration.ISettingsProviderService>hämtas i det första steget att returnera inställningsprovidern.</xref:System.Configuration.ISettingsProviderService> </xref:System.Configuration.ISettingsProviderService.GetSettingsProvider%2A>"
  syntax:
    content: protected SettingsProvider ();
    parameters: []
  overload: System.Configuration.SettingsProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.ApplicationName
  id: ApplicationName
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: ApplicationName
  nameWithType: SettingsProvider.ApplicationName
  fullName: System.Configuration.SettingsProvider.ApplicationName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Hämtar eller anger namnet på programmet som körs."
  remarks: "ApplicationName och <xref:System.Configuration.Provider.ProviderBase.Name%2A>Egenskaper för att undvika tvetydigheten på samma sätt namngivna egenskaper i olika program.</xref:System.Configuration.Provider.ProviderBase.Name%2A>"
  syntax:
    content: public abstract string ApplicationName { get; set; }
    return:
      type: System.String
      description: "En <xref:System.String>som innehåller programmets förkortade namn, som inte innehåller en fullständig sökväg eller tillägg, till exempel, `SimpleAppSettings`.</xref:System.String>"
  overload: System.Configuration.SettingsProvider.ApplicationName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  id: GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  nameWithType: SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  fullName: System.Configuration.SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Returnerar mängden inställningar egenskapsvärden för den angivna instans och inställningar för egenskapen programgruppen."
  remarks: "Metoden GetPropertyValues måste införas för att hantera särskilda inställningar, de som markerats med <xref:System.Configuration.SpecialSettingAttribute>, samt stämma av program-och användarinställningar.</xref:System.Configuration.SpecialSettingAttribute>"
  syntax:
    content: public abstract System.Configuration.SettingsPropertyValueCollection GetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyCollection collection);
    parameters:
    - id: context
      type: System.Configuration.SettingsContext
      description: "En <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> som beskriver den nuvarande användningen av programmet."
    - id: collection
      type: System.Configuration.SettingsPropertyCollection
      description: "En <xref href=&quot;System.Configuration.SettingsPropertyCollection&quot;> </xref> som innehåller gruppen inställningar egenskap vars värden som ska hämtas."
    return:
      type: System.Configuration.SettingsPropertyValueCollection
      description: "En <xref href=&quot;System.Configuration.SettingsPropertyValueCollection&quot;> </xref> som innehåller värdena för egenskapsgrupp angivna inställningar."
  overload: System.Configuration.SettingsProvider.GetPropertyValues*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  id: SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  nameWithType: SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  fullName: System.Configuration.SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Anger värdena för den angivna gruppen på inställningar för egenskapen."
  remarks: "<xref:System.Configuration.ApplicationSettingsBase>innehåller den <xref:System.Configuration.ApplicationSettingsBase.Save%2A>metod som anropas för att bevara värdena för alla inställningar egenskaper.</xref:System.Configuration.ApplicationSettingsBase.Save%2A></xref:System.Configuration.ApplicationSettingsBase> Den här metoden räknar igenom alla inställningar leverantörer som är associerade med dess egenskaper för inställningar och anropar metoden SetPropertyValues för varje <xref:System.Configuration.SettingsProvider>utföras faktiska serialisering.</xref:System.Configuration.SettingsProvider>       Metoden SetPropertyValues bör genomföras med säkerhet i åtanke: – endast fullständigt betrodd kod ska tillåtas att uppdatera inställningarna för programmet. Delvis betrodd kod ska tillåtas att uppdatera endast programmet användarinställningar. Icke betrodd kod tillåts inte normalt att uppdatera inställningarna för programmet.      -Användning kvoter bör betraktas som skyddar mot attacker resurs av delvis betrodd program."
  syntax:
    content: public abstract void SetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyValueCollection collection);
    parameters:
    - id: context
      type: System.Configuration.SettingsContext
      description: "En <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> som beskriver den nuvarande användningen av programmet."
    - id: collection
      type: System.Configuration.SettingsPropertyValueCollection
      description: "En <xref href=&quot;System.Configuration.SettingsPropertyValueCollection&quot;> </xref> som representerar gruppen med inställningar för att ställa in."
  overload: System.Configuration.SettingsProvider.SetPropertyValues*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.SettingsProvider.#ctor
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SettingsProvider()
  nameWithType: SettingsProvider.SettingsProvider()
  fullName: System.Configuration.SettingsProvider.SettingsProvider()
- uid: System.Configuration.SettingsProvider.ApplicationName
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: ApplicationName
  nameWithType: SettingsProvider.ApplicationName
  fullName: System.Configuration.SettingsProvider.ApplicationName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  nameWithType: SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  fullName: System.Configuration.SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
- uid: System.Configuration.SettingsPropertyValueCollection
  parent: System.Configuration
  isExternal: false
  name: SettingsPropertyValueCollection
  nameWithType: SettingsPropertyValueCollection
  fullName: System.Configuration.SettingsPropertyValueCollection
- uid: System.Configuration.SettingsContext
  parent: System.Configuration
  isExternal: false
  name: SettingsContext
  nameWithType: SettingsContext
  fullName: System.Configuration.SettingsContext
- uid: System.Configuration.SettingsPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: SettingsPropertyCollection
  nameWithType: SettingsPropertyCollection
  fullName: System.Configuration.SettingsPropertyCollection
- uid: System.Configuration.SettingsProvider.SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  nameWithType: SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  fullName: System.Configuration.SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
- uid: System.Configuration.SettingsProvider.#ctor*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider.SettingsProvider
- uid: System.Configuration.SettingsProvider.ApplicationName*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: ApplicationName
  nameWithType: SettingsProvider.ApplicationName
- uid: System.Configuration.SettingsProvider.GetPropertyValues*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: GetPropertyValues
  nameWithType: SettingsProvider.GetPropertyValues
- uid: System.Configuration.SettingsProvider.SetPropertyValues*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SetPropertyValues
  nameWithType: SettingsProvider.SetPropertyValues
