### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  id: PeerApplicationLaunchInfo
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  langs:
  - csharp
  name: PeerApplicationLaunchInfo
  nameWithType: PeerApplicationLaunchInfo
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  type: Class
  summary: "Representerar starta information som krävs av en <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> som har initierat som svar på en inbjudan till peer-samarbete."
  remarks: "Ett program kan inspektera den <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data%2A>och <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message%2A>Egenskaper i den här klassen för att hämta information om specifika för inbjudan som initierade programmet startas.</xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message%2A> </xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data%2A>       Åtkomst till den här klassen kräver en <xref:System.Security.Permissions.PermissionState>av <xref:System.Security.Permissions.PermissionState>.</xref:System.Security.Permissions.PermissionState> </xref:System.Security.Permissions.PermissionState> Det här tillståndet skapas när den <xref:System.Net.PeerToPeer.Collaboration.Peer>samarbetssession börjar.</xref:System.Net.PeerToPeer.Collaboration.Peer>"
  syntax:
    content: public class PeerApplicationLaunchInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  id: Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Hämtar eller anger programdefinierade binära data som är associerade med den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> inbjudan."
  remarks: "Den här data-blob har angetts av anroparen är Friform.  Maximal mängd data som kan anges är 4 096 byte.       Data kan inte vara `null`."
  syntax:
    content: public byte[] Data { get; }
    return:
      type: System.Byte[]
      description: "En matris med byte som innehåller data som är associerade med den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> inbjudan."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  id: Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Hämta eller ange ett meddelande som är kopplade till svaret på den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> inbjudan."
  remarks: "Den maximala längden för meddelandet är 255 Unicode-tecken. Om du inte uttryckligen anges är standardvärdet för alla egenskaper `null` för referenstyper."
  syntax:
    content: public string Message { get; }
    return:
      type: System.String
      description: "Ett textmeddelande som är associerade med den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerInvitationResponse&quot;> </xref> till den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> inbjudan."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Hämtar eller anger den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> för inbjudan har skickats."
  remarks: "Om du inte uttryckligen anges är standardvärdet för alla egenskaper `null` för referenstyper."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "Den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> som den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> inbjudan har skickats."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Hämtar eller anger den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> som skickade inbjudan."
  remarks: "Om du inte uttryckligen anges är standardvärdet för alla egenskaper `null` för referenstyper."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: "Den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> som skickade inbjudan."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Hämtar eller anger den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> som den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> inbjudan har skickats."
  remarks: "Om du inte uttryckligen anges är standardvärdet för alla egenskaper `null` för referenstyper."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: "Den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> från inbjudan har skickats."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
