### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.WebHttpSecurity
  id: WebHttpSecurity
  children:
  - System.ServiceModel.WebHttpSecurity.#ctor
  - System.ServiceModel.WebHttpSecurity.Mode
  - System.ServiceModel.WebHttpSecurity.ShouldSerializeMode
  - System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport
  - System.ServiceModel.WebHttpSecurity.Transport
  langs:
  - csharp
  name: WebHttpSecurity
  nameWithType: WebHttpSecurity
  fullName: System.ServiceModel.WebHttpSecurity
  type: Class
  summary: "Anger vilka typer av säkerhet som är tillgängliga för en tjänstslutpunkt som konfigurerats för att ta emot HTTP-begäranden."
  remarks: "WebHttpSecurity ger säkerhetskraven för en slutpunkt som konfigurerats med en <xref:System.ServiceModel.WebHttpBinding>.</xref:System.ServiceModel.WebHttpBinding>       Om den <xref:System.ServiceModel.WebHttpSecurityMode>värdet anges av den <xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>metoden och sedan de inställningar som den <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>egenskapen börjar gälla för tjänstslutpunkten.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A> </xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29> </xref:System.ServiceModel.WebHttpSecurityMode> Värdet för <xref:System.ServiceModel.WebHttpSecurityMode>kan bara anges i den <xref:System.ServiceModel.WebHttpBinding>konstruktor som tar det som en explicit parameter och dess värde inte kan anges igen när bindningsinstans har skapats.</xref:System.ServiceModel.WebHttpBinding> </xref:System.ServiceModel.WebHttpSecurityMode>"
  syntax:
    content: public sealed class WebHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: WebHttpSecurity()
  nameWithType: WebHttpSecurity.WebHttpSecurity()
  fullName: System.ServiceModel.WebHttpSecurity.WebHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "Skapar en ny instans av den <xref href=&quot;System.ServiceModel.WebHttpSecurity&quot;> </xref> klass."
  syntax:
    content: public WebHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.WebHttpSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: WebHttpSecurity.Mode
  fullName: System.ServiceModel.WebHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "Hämtar eller anger läget för säkerhet som används av en slutpunkt som konfigurerats för att ta emot HTTP-begäranden med en <xref href=&quot;System.ServiceModel.WebHttpBinding&quot;> </xref>."
  remarks: "Den här egenskapen anger om inställningarna från den <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>egenskapen börjar gälla.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A>"
  syntax:
    content: public System.ServiceModel.WebHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WebHttpSecurityMode
      description: "Ett värde för den <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref> som anger om säkerhet på transportnivå eller ingen säkerhet används av en slutpunkt. Standardvärdet är <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.WebHttpSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Värdet är inte ett giltigt <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: WebHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "Anger om den <xref:System.ServiceModel.WebHttpSecurity.Mode*>egenskap har ändrats från standard och ska serialiseras.</xref:System.ServiceModel.WebHttpSecurity.Mode*> Det här används för XAML-integrering."
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <xref:System.ServiceModel.WebHttpSecurity.Mode*>egenskapsvärdet måste vara serialiserade, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WebHttpSecurity.Mode*>"
  overload: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: WebHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "Returnerar ett värde som indikerar om egenskapen Transport har ändrats från sitt standardvärde och ska serialiseras. Detta används av WCF för XAML-integrering."
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <xref:System.ServiceModel.WebHttpSecurity.Transport*>egenskapsvärdet måste vara serialiserade, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WebHttpSecurity.Transport*>"
  overload: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.Transport
  id: Transport
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: WebHttpSecurity.Transport
  fullName: System.ServiceModel.WebHttpSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "Hämtar ett objekt som innehåller transportnivå säkerhetsinställningarna för den här bindningen."
  remarks: "Använda <xref:System.ServiceModel.HttpTransportSecurity>objektet som returnerades av den här egenskapen för att ange parametrar för transport-säkerhet för <xref:System.ServiceModel.WebHttpBinding>.</xref:System.ServiceModel.WebHttpBinding> </xref:System.ServiceModel.HttpTransportSecurity>       Om den <xref:System.ServiceModel.WebHttpSecurityMode>eller <xref:System.ServiceModel.WebHttpSecurityMode>värdet anges av den <xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>metoden och inställningarna som anges av egenskapen Transport börjar gälla för tjänstslutpunkten.</xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29> </xref:System.ServiceModel.WebHttpSecurityMode> </xref:System.ServiceModel.WebHttpSecurityMode>       Om den <xref:System.ServiceModel.WebHttpSecurityMode>värdet anges av den <xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>metoden och inställningarna som anges av egenskapen Transport börjar gälla för tjänstslutpunkten.</xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29> </xref:System.ServiceModel.WebHttpSecurityMode> Värdet för <xref:System.ServiceModel.WebHttpSecurityMode>kan bara anges i den <xref:System.ServiceModel.WebHttpBinding>konstruktor som tar det som en explicit parameter och dess värde inte kan anges igen när bindningsinstans har skapats.</xref:System.ServiceModel.WebHttpBinding> </xref:System.ServiceModel.WebHttpSecurityMode>"
  syntax:
    content: public System.ServiceModel.HttpTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.HttpTransportSecurity
      description: "Den <xref:System.ServiceModel.HttpTransportSecurity>för den här bindningen.</xref:System.ServiceModel.HttpTransportSecurity>       En standarduppsättning värden är en <> </> *> av <xref:System.ServiceModel.HttpClientCredentialType>, <> </> *> av <xref href=&quot;System.ServiceModel.HttpProxyCredentialType&quot;> </xref>, och <xref:System.ServiceModel.HttpTransportSecurity.Realm*>= &quot;&quot;.</xref:System.ServiceModel.HttpTransportSecurity.Realm*> </xref:System.ServiceModel.HttpClientCredentialType>"
  overload: System.ServiceModel.WebHttpSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.WebHttpSecurity.#ctor
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: WebHttpSecurity()
  nameWithType: WebHttpSecurity.WebHttpSecurity()
  fullName: System.ServiceModel.WebHttpSecurity.WebHttpSecurity()
- uid: System.ServiceModel.WebHttpSecurity.Mode
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurity.Mode
  fullName: System.ServiceModel.WebHttpSecurity.Mode
- uid: System.ServiceModel.WebHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WebHttpSecurityMode
  nameWithType: WebHttpSecurityMode
  fullName: System.ServiceModel.WebHttpSecurityMode
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: WebHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: WebHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport()
- uid: System.ServiceModel.WebHttpSecurity.Transport
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurity.Transport
  fullName: System.ServiceModel.WebHttpSecurity.Transport
- uid: System.ServiceModel.HttpTransportSecurity
  parent: System.ServiceModel
  isExternal: true
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: System.ServiceModel.HttpTransportSecurity
- uid: System.ServiceModel.WebHttpSecurity.#ctor*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: WebHttpSecurity
  nameWithType: WebHttpSecurity.WebHttpSecurity
- uid: System.ServiceModel.WebHttpSecurity.Mode*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurity.Mode
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: WebHttpSecurity.ShouldSerializeMode
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: WebHttpSecurity.ShouldSerializeTransport
- uid: System.ServiceModel.WebHttpSecurity.Transport*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurity.Transport
