### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlWriterSettings
  id: XamlWriterSettings
  children:
  - System.Xaml.XamlWriterSettings.#ctor
  - System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  langs:
  - csharp
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings
  fullName: System.Xaml.XamlWriterSettings
  type: Class
  summary: "Ger initieringsinställningar för en <xref href=&quot;System.Xaml.XamlWriter&quot;> </xref> implementering."
  remarks: "XamlWriterSettings är en klass för inställningar som används av en <xref:System.Xaml.XamlWriter>, men XamlWriterSettings inte innehåller några särskilda inställningar.</xref:System.Xaml.XamlWriter> En <xref:System.Xaml.XamlWriter>konstruktor använder inte den här klassen som ett argument, inte heller några andra <xref:System.Xaml.XamlWriter>medlem använda det.</xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlWriter> I stället de <xref:System.Xaml.XamlXmlWriter>och <xref:System.Xaml.XamlObjectWriter>klasser innehåller sina egna inställningar klasser som konstruktionen argument; båda klasserna lägga till faktiska inställningar och baseras på XamlWriterSettings.</xref:System.Xaml.XamlObjectWriter> </xref:System.Xaml.XamlXmlWriter>"
  syntax:
    content: public class XamlWriterSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlWriterSettings
  langs:
  - csharp
  name: XamlWriterSettings()
  nameWithType: XamlWriterSettings.XamlWriterSettings()
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initierar en ny instans av den <xref href=&quot;System.Xaml.XamlWriterSettings&quot;> </xref> klass."
  syntax:
    content: public XamlWriterSettings ();
    parameters: []
  overload: System.Xaml.XamlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  id: '#ctor(System.Xaml.XamlWriterSettings)'
  parent: System.Xaml.XamlWriterSettings
  langs:
  - csharp
  name: XamlWriterSettings(XamlWriterSettings)
  nameWithType: XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initierar en ny instans av den <xref href=&quot;System.Xaml.XamlWriterSettings&quot;> </xref> klassen med hjälp av en annan instans för befintliga inställningar."
  remarks: "Den här konstruktorn stöder sammanslagning av inställningar, där fler inställningar kan komma från andra deltagarna i skrivprocessen eller inställningar klasser för särskilda skrivare som åsidosätter <xref:System.Xaml.XamlWriterSettings>.</xref:System.Xaml.XamlWriterSettings>"
  syntax:
    content: public XamlWriterSettings (System.Xaml.XamlWriterSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlWriterSettings
      description: "En befintlig <xref href=&quot;System.Xaml.XamlWriterSettings&quot;> </xref> objekt."
  overload: System.Xaml.XamlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlWriterSettings.#ctor
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings()
  nameWithType: XamlWriterSettings.XamlWriterSettings()
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings()
- uid: System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings(XamlWriterSettings)
  nameWithType: XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
- uid: System.Xaml.XamlWriterSettings
  parent: System.Xaml
  isExternal: false
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings
  fullName: System.Xaml.XamlWriterSettings
- uid: System.Xaml.XamlWriterSettings.#ctor*
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings.XamlWriterSettings
