### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  id: ProcessModelComImpersonationLevel
  children:
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  langs:
  - csharp
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
  type: Enum
  summary: "Anger autentiseringsnivån för COM-säkerhet."
  remarks: "Klassen ProcessModelComImpersonationLevel räknar upp värdena som ska användas när du ställer in den <xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A>egenskapen.</xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A>       Standardvärdet är personifiera."
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/csharp/t-system.web.configurati_52_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/visualbasic/t-system.web.configurati_52_1.vb)]"
  syntax:
    content: public enum ProcessModelComImpersonationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  id: Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att klienten är anonym för servern. Det här fältet är konstant."
  remarks: "Servern kan personifiera klienten, men token innehåller inte någon information."
  syntax:
    content: Anonymous
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  id: Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att personifieringsnivån bestäms av DCOM. Det här fältet är konstant."
  remarks: "DCOM anger personifieringsnivån, med dess normala säkerhetsförhandlingen algoritm."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  id: Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att serverprocessen kan personifiera klientens säkerhetskontext agerade för klientens räkning. Det här fältet är konstant."
  remarks: "Serverprocessen kan göra utgående anrop till andra servrar klienten med svepa in. Servern kan använda klientens säkerhetskontext på andra datorer för åtkomst till lokala och fjärranslutna resurser som klienten. När processen är personifiering av klienten på den här nivån, kan token för personifiering skickas till alla datorgränser."
  syntax:
    content: Delegate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  id: Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att servern kan hämta klientens identitet. Det här fältet är konstant."
  remarks: "Servern kan personifiera klienten för kontroll av åtkomstkontrollistan (ACL), men det går inte att komma åt systemobjekt som klienten."
  syntax:
    content: Identify
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  id: Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Anger att serverprocessen kan personifiera klientens säkerhetskontext agerade för klientens räkning. Det här fältet är konstant."
  remarks: "Den här nivån för personifiering kan användas för åtkomst till lokala resurser, till exempel filer. När processen personifierar klient på den här nivån, kan token för personifiering överföras till endast en dator gräns."
  syntax:
    content: Impersonate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "Som ska läggas till."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
