### YamlMime:ManagedReference
items:
- uid: System.Configuration.IConfigurationSectionHandler
  id: IConfigurationSectionHandler
  children:
  - System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: IConfigurationSectionHandler
  nameWithType: IConfigurationSectionHandler
  fullName: System.Configuration.IConfigurationSectionHandler
  type: Interface
  summary: "Hanterar åtkomst till vissa konfigurationsavsnitt."
  remarks: "**Viktiga** IConfigurationSectionHandler är inaktuell i .NET Framework 2.0 och senare. Men har behållits eftersom det används internt. Du hittar ett exempel på [så här: Skapa anpassad konfiguration avsnitt med IConfigurationSectionHandler](~/add/includes/ajax-current-ext-md.md). Om du använder föregående exempel kan du skapa den med .NET Framework version 1.0 eller 1.1.       I .NET Framework version 2.0 och senare, du måste i stället vara härledd från den <xref:System.Configuration.ConfigurationSection>klassen för att implementera relaterade avsnittshanteraren.</xref:System.Configuration.ConfigurationSection> Du hittar ett exempel på [så här: Skapa anpassad konfiguration avsnitt med ConfigurationSection](~/add/includes/ajax-current-ext-md.md).       Instanser av klassen IConfigurationSectionHandler måste vara tråd säkert och tillståndslösa. Den <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>metoden måste vara anropas från flera trådar samtidigt.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A>       Dessutom konfigurationsobjektet genereras av den <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>metoden måste vara tråd säkert och oföränderliga.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A> Eftersom configuration-objekt cachelagras av konfigurationssystemet är det viktigt inte att ändra argumentet överordnad till den <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>metoden.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A> Till exempel om returvärdet för <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>är bara en liten ändring av överordnat faktiska ändringar måste göras på en klon av överordnat inte originalet.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A>"
  syntax:
    content: public interface IConfigurationSectionHandler
  implements: []
  platform:
  - net462
- uid: System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IConfigurationSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Skapar ett konfigurationsavsnitt."
  remarks: "Instanser av den <xref:System.Configuration.IConfigurationSectionHandler>klassen måste vara tråd säkert och tillståndslösa.</xref:System.Configuration.IConfigurationSectionHandler> Create-metoden måste vara anropas från flera trådar samtidigt.       Konfigurationsobjekt som genererats av Create-metoden måste dessutom vara tråd säkert och ändras. Eftersom configuration-objekt cachelagras av konfigurationssystemet är det viktigt att inte ändra argumentet överordnad till skapa. Om det returnera värdet för Create är endast en liten ändring av överordnat, måste faktiska ändringar göras på en klon av överordnat inte originalet."
  syntax:
    content: public object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Överordnat objekt."
    - id: configContext
      type: System.Object
      description: "Konfigurationen context-objektet."
    - id: section
      type: System.Xml.XmlNode
      description: "Avsnittet XML-nod."
    return:
      type: System.Object
      description: "Objektet skapade avsnittet hanterare."
  overload: System.Configuration.IConfigurationSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IConfigurationSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IConfigurationSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.IConfigurationSectionHandler.Create*
  parent: System.Configuration.IConfigurationSectionHandler
  isExternal: false
  name: Create
  nameWithType: IConfigurationSectionHandler.Create
