### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.ApplicationInfo
  id: ApplicationInfo
  children:
  - System.Web.Hosting.ApplicationInfo.ID
  - System.Web.Hosting.ApplicationInfo.PhysicalPath
  - System.Web.Hosting.ApplicationInfo.VirtualPath
  langs:
  - csharp
  name: ApplicationInfo
  nameWithType: ApplicationInfo
  fullName: System.Web.Hosting.ApplicationInfo
  type: Class
  summary: "Innehåller information om ett program som körs. Den här klassen kan inte ärvas."
  remarks: "Objektet ApplicationInfo används av den <xref:System.Web.Hosting.ApplicationManager>klass för information om program som körs.</xref:System.Web.Hosting.ApplicationManager>"
  example:
  - "The following code example gets an array of ApplicationInfo objects from the <xref:System.Web.Hosting.ApplicationManager> object associated with the current process.  \n  \n [!code-vb[System.Web.Hosting.ApplicationInfo#1](~/add/codesnippet/visualbasic/t-system.web.hosting.app_1.aspx)]\n [!code-cs[System.Web.Hosting.ApplicationInfo#1](~/add/codesnippet/csharp/t-system.web.hosting.app_1.aspx)]"
  syntax:
    content: public sealed class ApplicationInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationInfo.ID
  id: ID
  parent: System.Web.Hosting.ApplicationInfo
  langs:
  - csharp
  name: ID
  nameWithType: ApplicationInfo.ID
  fullName: System.Web.Hosting.ApplicationInfo.ID
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Hämtar den unika identifieraren för programmet."
  remarks: "För program som körs under Microsoft Internet Information Services (IIS), är det program-ID metabassökväg rot-program, till exempel /LM/W3SVC/1/Root/application."
  syntax:
    content: public string ID { get; }
    return:
      type: System.String
      description: "Unik identifierare för programmet som anges när programmet skapades med hjälp av den <xref:System.Web.Hosting.ApplicationManager.CreateObject*>metoden.</xref:System.Web.Hosting.ApplicationManager.CreateObject*>"
  overload: System.Web.Hosting.ApplicationInfo.ID*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationInfo.PhysicalPath
  id: PhysicalPath
  parent: System.Web.Hosting.ApplicationInfo
  langs:
  - csharp
  name: PhysicalPath
  nameWithType: ApplicationInfo.PhysicalPath
  fullName: System.Web.Hosting.ApplicationInfo.PhysicalPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Hämtar den fysiska sökvägen som motsvarar den tillämpningsprogrammets rot."
  remarks: "Egenskapen PhysicalPath är den sökväg som skickades till den <xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>metoden när programmet skapades.</xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>"
  syntax:
    content: public string PhysicalPath { get; }
    return:
      type: System.String
      description: "Den fysiska sökvägen som motsvarar den tillämpningsprogrammets rot."
  overload: System.Web.Hosting.ApplicationInfo.PhysicalPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationInfo.VirtualPath
  id: VirtualPath
  parent: System.Web.Hosting.ApplicationInfo
  langs:
  - csharp
  name: VirtualPath
  nameWithType: ApplicationInfo.VirtualPath
  fullName: System.Web.Hosting.ApplicationInfo.VirtualPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Hämtar den virtuella sökvägen som motsvarar den tillämpningsprogrammets rot."
  remarks: "Egenskapen VirtualPath är den virtuella sökvägen som skickades till den <xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>metoden när programmet skapades.</xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>"
  syntax:
    content: public string VirtualPath { get; }
    return:
      type: System.String
      description: "Den virtuella sökvägen som motsvarar den tillämpningsprogrammets rot."
  overload: System.Web.Hosting.ApplicationInfo.VirtualPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Hosting.ApplicationInfo.ID
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: ID
  nameWithType: ApplicationInfo.ID
  fullName: System.Web.Hosting.ApplicationInfo.ID
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Hosting.ApplicationInfo.PhysicalPath
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: PhysicalPath
  nameWithType: ApplicationInfo.PhysicalPath
  fullName: System.Web.Hosting.ApplicationInfo.PhysicalPath
- uid: System.Web.Hosting.ApplicationInfo.VirtualPath
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: VirtualPath
  nameWithType: ApplicationInfo.VirtualPath
  fullName: System.Web.Hosting.ApplicationInfo.VirtualPath
- uid: System.Web.Hosting.ApplicationInfo.ID*
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: ID
  nameWithType: ApplicationInfo.ID
- uid: System.Web.Hosting.ApplicationInfo.PhysicalPath*
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: PhysicalPath
  nameWithType: ApplicationInfo.PhysicalPath
- uid: System.Web.Hosting.ApplicationInfo.VirtualPath*
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: VirtualPath
  nameWithType: ApplicationInfo.VirtualPath
