### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FolderLevelBuildProvider
  id: FolderLevelBuildProvider
  children:
  - System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  - System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  - System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  - System.Web.Configuration.FolderLevelBuildProvider.Name
  - System.Web.Configuration.FolderLevelBuildProvider.Properties
  - System.Web.Configuration.FolderLevelBuildProvider.Type
  langs:
  - csharp
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider
  fullName: System.Web.Configuration.FolderLevelBuildProvider
  type: Class
  summary: "Representerar konfigurationsinställningar som möjliggör användning av den <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> klass för specifika mappar."
  remarks: "ASP.NET-kompileringsmiljö använder FolderLevelBuildProvider objekt för att generera källkoden för typer av filer och undermappar i ett program. Klasser som härleds från klassen FolderLevelBuildProvider generera källkoden för mappar, till exempel Bin, App_GlobalResources, App_LocalResources, App_WebReferences, App_Browsers, tema och andra anpassade mappar. Normalt skapar du inte en instans av klassen FolderLevelBuildProvider direkt. I stället kan du implementera en klass som härleds från <xref:System.Web.Compilation.BuildProvider>och tillämpa den <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>klassen till den och sedan konfigurera den härledda klassen för användning i ASP.NET-kompileringsmiljö.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute> </xref:System.Web.Compilation.BuildProvider> Den <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>klassen riktar sig till mappar i stället för filer.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>       Du använder instanser av klassen FolderLevelBuildProvider tillsammans med <xref:System.Web.Compilation.AssemblyBuilder>objekt för att skapa en eller flera filer i en kompilerad sammansättning.</xref:System.Web.Compilation.AssemblyBuilder> FolderLevelBuildProvider instans genererar källkoden i det aktuella språket för enskilda filer och <xref:System.Web.Compilation.AssemblyBuilder>objektet bygger källkoden från varje FolderLevelBuildProvider-instans till en enda sammansättning.</xref:System.Web.Compilation.AssemblyBuilder>       Klassen FolderLevelBuildProvider har angetts i den `configuration` avsnitt i Web.config-filen."
  example:
  - "The following example shows how to add a build provider named `BuildProvider1` to the Web.config file.  \n  \n```  \n<compilation>  \n  <folderLevelBuildProviders>  \n    <add type=\"BuildProvider1, Assembly1,Version=1.0.0.0,    \n        PublicKeyToken=xxxxx\"/>  \n  </folderLevelBuildProviders>  \n</compilation>  \n```"
  syntax:
    content: 'public sealed class FolderLevelBuildProvider : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> klass med en identifierare och det fullständigt kvalificerade namnet."
  syntax:
    content: public FolderLevelBuildProvider (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "Identifieraren för den <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> ska användas."
    - id: type
      type: System.String
      description: "Det fullständigt kvalificerade namnet på den <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> ska användas."
  overload: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Returnerar ett värde som anger om ett angivet-objekt är lika med aktuellt <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> objekt."
  syntax:
    content: public override bool Equals (object provider);
    parameters:
    - id: provider
      type: System.Object
      description: "Build-Providerobjektet som ska jämföras."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den angivna mappnivån skapar objektet är lika med det aktuella objektet. Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Genererar en Hashkod för den <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> objekt."
  remarks: "Den här metoden genererar ett heltal som kan användas för att identifiera objektet som mappen nivån build-provider. Den här metoden ärver från den <xref:System.Object.GetHashCode%2A>metoden.</xref:System.Object.GetHashCode%2A> Den <xref:System.Object.GetHashCode%2A>metoden lämpar sig för hash-algoritmer och datastrukturer som en hash-tabell.</xref:System.Object.GetHashCode%2A>"
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Hash-koden för den <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> objekt."
  overload: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  id: Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar eller anger namnet på den <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> objekt."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Namnet på objektet build-provider."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  id: Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  id: Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar eller anger det fullständiga namnet för klassen build-provider."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Det fullständigt kvalificerade namnet för klassen build-provider."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals
  nameWithType: FolderLevelBuildProvider.Equals
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode
  nameWithType: FolderLevelBuildProvider.GetHashCode
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
