### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationValidatorBase
  id: ConfigurationValidatorBase
  children:
  - System.Configuration.ConfigurationValidatorBase.#ctor
  - System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  - System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  langs:
  - csharp
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
  type: Class
  summary: "Fungerar som en basklass för att få fram en valideringsklassen så att ett värde för ett objekt som kan verifieras."
  remarks: "Klassen ConfigurationValidatorBase används för att skapa en anpassad verifieraren. En anpassad verifieraren kan användas för att verifiera objektets värden."
  syntax:
    content: public abstract class ConfigurationValidatorBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initierar en instans av den <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> klass."
  syntax:
    content: protected ConfigurationValidatorBase ();
    parameters: []
  overload: System.Configuration.ConfigurationValidatorBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Anger om ett objekt kan verifieras baserat på typen."
  syntax:
    content: public virtual bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Objekttyp."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den <code> type </code> parametervärdet matchar den förväntade <xref uid=&quot;langword_csharp_type&quot; name=&quot;type&quot; href=&quot;&quot;> </xref>, annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationValidatorBase.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Anger om värdet för ett objekt är giltig."
  remarks: "Ett objekt som har härletts från den <xref:System.Configuration.ConfigurationValidatorBase>klassen innehåller kriterierna som behövs för att validera ett objekt.</xref:System.Configuration.ConfigurationValidatorBase> Kriterierna som fastställs när den härledda klassen instansieras. Objektet som har skickats som en parameter för Validate-metoden."
  syntax:
    content: public abstract void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Värdet för objektet."
  overload: System.Configuration.ConfigurationValidatorBase.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
- uid: System.Configuration.ConfigurationValidatorBase.#ctor*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: CanValidate
  nameWithType: ConfigurationValidatorBase.CanValidate
- uid: System.Configuration.ConfigurationValidatorBase.Validate*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: Validate
  nameWithType: ConfigurationValidatorBase.Validate
