### YamlMime:ManagedReference
items:
- uid: System.Printing.PrintJobSettings
  id: PrintJobSettings
  children:
  - System.Printing.PrintJobSettings.CurrentPrintTicket
  - System.Printing.PrintJobSettings.Description
  langs:
  - csharp
  name: PrintJobSettings
  nameWithType: PrintJobSettings
  fullName: System.Printing.PrintJobSettings
  type: Class
  summary: "Beskriver ett utskriftsjobb."
  remarks: "Den <xref:System.Printing.PrintTicket>-objektet, vilket är värdet för den <xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A>-egenskapen innehåller detaljerade inställningar för ett utskriftsjobb.</xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A> </xref:System.Printing.PrintTicket> Överordnat PrintJobSettings, lägger till endast en beskrivning.      > [!CAUTION] > Klasserna i den <xref:System.Printing>namnområde stöds inte för användning i en Windows-tjänst eller ASP.NET-program eller tjänst.</xref:System.Printing> Försök att använda dessa klasser från inom någon av följande programtyper kan ge oväntade problem, så som minskat tjänsten prestanda- och undantag.       Om du vill skriva ut från en Windows Forms-program finns i <xref:System.Drawing.Printing>namnområde.</xref:System.Drawing.Printing>"
  syntax:
    content: public class PrintJobSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  id: CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Hämtar eller anger en <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> objekt som innehåller detaljerade inställningar för utskriftsjobbet."
  remarks: "Den här egenskapen CurrentPrintTicket inte verifiera eller ändra den angivna <xref:System.Printing.PrintTicket>för en viss <xref:System.Printing.PrintQueue>.</xref:System.Printing.PrintQueue> </xref:System.Printing.PrintTicket>  Om det behövs kan du använda den <xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>metoden för att skapa en <xref:System.Printing.PrintQueue>-specifika <xref:System.Printing.PrintTicket>som är giltig för en viss skrivare.</xref:System.Printing.PrintTicket> </xref:System.Printing.PrintQueue> </xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>"
  syntax:
    content: public System.Printing.PrintTicket CurrentPrintTicket { get; set; }
    return:
      type: System.Printing.PrintTicket
      description: "En <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> objekt som innehåller alla uppgifter om utskriftsjobbet, till exempel antalet kopior som ska skrivas ut, och om häftning eller dubbelsidig utskrift används."
  overload: System.Printing.PrintJobSettings.CurrentPrintTicket*
  exceptions: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.Description
  id: Description
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Hämtar eller anger en beskrivning av ett utskriftsjobb."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "En <xref:System.String>som beskriver utskriften, till exempel &quot;rapport varje kvartal.&quot;</xref:System.String>"
  overload: System.Printing.PrintJobSettings.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintTicket
  parent: System.Printing
  isExternal: false
  name: PrintTicket
  nameWithType: PrintTicket
  fullName: System.Printing.PrintTicket
- uid: System.Printing.PrintJobSettings.Description
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintJobSettings.Description*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
