### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement
  id: IssuerNameRegistryElement
  children:
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  langs:
  - csharp
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement
  type: Class
  summary: "Representerar en <xref uid=&quot;langword_csharp_&lt;issuerNameRegistry&gt;&quot; name=&quot;&lt;issuerNameRegistry&gt;&quot; href=&quot;&quot;> </xref> element i en konfigurationsfil. Den här klassen kan inte ärvas."
  remarks: "Den `<issuerNameRegistry>` element konfigurerar Utfärdarens namn registret. Utfärdarens namn registret mappar utfärdaren token till en sträng. Den <xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A>egenskapen (vilket motsvarar den `type` attribut för elementet) kan anges för att registrera en anpassad typ.</xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A> Som standard en typ av <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>antas.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>       Den `<issuerNameRegistry>` element kan anges på tjänstnivå under den `<identityConfiguration>` element eller på en säkerhet token hanterare samling under de `<securityTokenHandlerConfiguration>` element. Den `IssuerNameRegistry` -egenskapen för den <xref:System.IdentityModel.Configuration.IdentityConfigurationElement>klass och det <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement>klassen är en instans av IssuerNameRegistryElement.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement> </xref:System.IdentityModel.Configuration.IdentityConfigurationElement>"
  syntax:
    content: 'public sealed class IssuerNameRegistryElement : System.IdentityModel.Configuration.ConfigurationElementInterceptor'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.IdentityModel.Configuration.IssuerNameRegistryElement&quot;> </xref> klass."
  syntax:
    content: public IssuerNameRegistryElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  id: Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Hämtar eller anger en strängrepresentation av den <xref:System.Type>av Utfärdarens namn registret.</xref:System.Type>"
  remarks: "Den här egenskapen är valfri. Det motsvarar den `type` attribut för den `<issuerNameRegistry>` element. Om det inte anges egenskapen är `null`, en typ av <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>antas.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Den sträng som innehåller den <xref:System.Type>av Utfärdarens namn registret.</xref:System.Type> Typen måste härledas från den <xref href=&quot;System.IdentityModel.Tokens.IssuerNameRegistry&quot;> </xref> klass."
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: System.IdentityModel.Configuration.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
