### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComUdtElement
  id: ComUdtElement
  children:
  - System.ServiceModel.Configuration.ComUdtElement.#ctor
  - System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ComUdtElement.Name
  - System.ServiceModel.Configuration.ComUdtElement.Properties
  - System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  langs:
  - csharp
  name: ComUdtElement
  nameWithType: ComUdtElement
  fullName: System.ServiceModel.Configuration.ComUdtElement
  type: Class
  summary: "Representerar en användare definierade typen (UDT) som ska tas med i tjänstkontraktet. Den här klassen kan inte ärvas."
  remarks: "COM +-integration runtime skapar tjänster genom att inspektera typbiblioteket. När en COM +-komponent innehåller metoder som skickar ett `VARIANT`, det går inte att avgöra de faktiska typerna som ska skickas före körning. Därför när du försöker skicka en användare definierade typen (UDT) inom en `VARIANT`, misslyckas eftersom den inte är en känd typ för serialisering.       Om du vill kringgå det här problemet, du kan lägga till de användardefinierade typer som konfigurationsfilen så att de inkluderas som kända typer på lämplig tjänstkontraktet. För att kunna göra det, måste du identifiera UDT och kontraktet, det vill säga den ursprungliga COM gränssnitt som används för.       Exemplet nedan visar att lägga till två specifika UDT-typer till den `userDefinedTypes`> avsnittet i konfigurationsfilen för detta ändamål.       [!code-cs[XpsCreate #XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent) ] attributen för den `userDefinedType`> element definieras enligt följande:- `typeName`: ett valfritt attribut som innehåller namnet på läsbar. Detta används inte av körningsmiljön men hjälper en läsare att skilja typerna.      - `typeLibID`: en GUID-sträng som anger det registrerade typbiblioteket som definierar typen.      - `typeLibVersion`: en sträng som anger vilken version av typen bibliotek som definierar typen.      - `typeDefID`: en GUID-sträng som anger den specifika UDT-typen i registrerade typbiblioteket.       När tjänsten har initierats COM +-integration runtime söker efter de angivna typerna och lägger till dem i en samling med kända typer för de angivna kontrakt."
  example:
  - "The following example demonstrates adding two specific UDTs to the <`userDefinedTypes`> section of the configuration file for this purpose.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: 'public sealed class ComUdtElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref> klass."
  syntax:
    content: public ComUdtElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initierar en ny instans av den <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref> klass med den angivna GUID-strängen."
  syntax:
    content: public ComUdtElement (string typeDefID);
    parameters:
    - id: typeDefID
      type: System.String
      description: "En GUID-sträng som identifierar den specifika UDT-typ i registrerade typbiblioteket."
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger namnet på läsbar."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Läsbar typnamn."
  overload: System.ServiceModel.Configuration.ComUdtElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som ska läggas till."
  overload: System.ServiceModel.Configuration.ComUdtElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  id: TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger en GUID-sträng som identifierar den specifika UDT-typen i registrerade typbiblioteket."
  syntax:
    content: public string TypeDefID { get; set; }
    return:
      type: System.String
      description: "Den speciella typ UDT inom registrerade typbiblioteket."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  id: TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger en GUID-sträng som identifierar registrerade typbiblioteket som definierar typen."
  syntax:
    content: public string TypeLibID { get; set; }
    return:
      type: System.String
      description: "Registrerade typbiblioteket som definierar typen."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  id: TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hämtar eller anger en sträng som identifierar den typ av biblioteksversionen som definierar typen."
  syntax:
    content: public string TypeLibVersion { get; set; }
    return:
      type: System.String
      description: "Typversion som definierar typen för biblioteket."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement
  nameWithType: ComUdtElement.ComUdtElement
- uid: System.ServiceModel.Configuration.ComUdtElement.Name*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
