### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SystemWebCachingSectionGroup
  id: SystemWebCachingSectionGroup
  children:
  - System.Web.Configuration.SystemWebCachingSectionGroup.#ctor
  - System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  - System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  - System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  - System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  langs:
  - csharp
  name: SystemWebCachingSectionGroup
  nameWithType: SystemWebCachingSectionGroup
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup
  type: Class
  summary: "Konfigurerar den <xref uid=&quot;langword_csharp_caching&quot; name=&quot;caching&quot; href=&quot;&quot;> </xref> gruppen i en konfigurationsfil. Den här klassen kan inte ärvas."
  remarks: "Klassen SystemWebCachingSectionGroup ger ett sätt att genom programmering komma åt och ändra den `caching` i en konfigurationsfil.       Klassen SystemWebCachingSectionGroup och `caching` avsnitt ge centraliserad kontroll av cachelagringsmekanism för en webbplats eller program. Detta gör det möjligt för cachelagring för att distribuera, ändras och inaktiveras utan att ändra enskilda sidor i programmet.       ASP.NET-cachelagringen implementeras av <xref:System.Web.Caching.Cache>klass.</xref:System.Web.Caching.Cache> Mer information finns i [översikt över cachelagring ASP.NET](~/add/includes/ajax-current-ext-md.md) i följande lista beskrivs de två typerna av cachelagring ASP.NET tillhandahåller.      – Först kallas för cachelagring av utdata, där du kan lagra dynamisk sida och användarens kontroll svar. Sidan eller användare kontrollkoden körs inte på efterföljande förfrågningar; cachelagrade utdata används för att uppfylla begäran. Du kan komma åt utdata cachelagring inställningar med hjälp av den <xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache%2A>och <xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings%2A>Egenskaper.</xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings%2A> </xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache%2A>      -Den andra typen av cachelagring är traditionella programdata cachelagring, som du kan använda för att lagra godtyckliga objekt till server-minnet så att programmet kan spara tid och resurser som det tar för att återskapa dem. Du kan komma åt cacheinställningarna med hjälp av den <xref:System.Web.Configuration.SystemWebCachingSectionGroup.Cache%2A>egenskapen.</xref:System.Web.Configuration.SystemWebCachingSectionGroup.Cache%2A>"
  example:
  - "The following code example shows how to obtain the SystemWebCachingSectionGroup object from the configuration file associated with an existing Web application. You can use this object to access the sections contained in the `caching` group.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#1](~/add/codesnippet/csharp/t-system.web.configurati_82_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#1](~/add/codesnippet/visualbasic/t-system.web.configurati_82_1.vb)]"
  syntax:
    content: 'public sealed class SystemWebCachingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: SystemWebCachingSectionGroup()
  nameWithType: SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Skapar en ny instans av <xref href=&quot;System.Web.Configuration.SystemWebCachingSectionGroup&quot;> </xref>."
  remarks: "SystemWebCachingSectionGroup-konstruktorn är inte avsedd att användas direkt från din kod. Den anropas av ASP.NET-konfigurationssystemet. Du har fått en instans av den <xref:System.Web.Configuration.SystemWebCachingSectionGroup>klassen med hjälp av den <xref:System.Configuration.Configuration.GetSection%2A>metoden.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.SystemWebCachingSectionGroup>"
  syntax:
    content: public SystemWebCachingSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  id: Cache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: Cache
  nameWithType: SystemWebCachingSectionGroup.Cache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar den <xref uid=&quot;langword_csharp_cache&quot; name=&quot;cache&quot; href=&quot;&quot;> </xref> avsnittet som ingår i konfigurationen."
  remarks: "Den <xref:System.Web.Configuration.CacheSection>objektet refererar till den `cache` avsnittet i konfigurationsfilen.</xref:System.Web.Configuration.CacheSection> Du kan använda den <xref:System.Web.Configuration.CacheSection>klassen om du vill ändra den `cache` avsnittet programmässigt.</xref:System.Web.Configuration.CacheSection>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.CacheSection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#2](~/add/codesnippet/csharp/p-system.web.configurati_388_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#2](~/add/codesnippet/visualbasic/p-system.web.configurati_388_1.vb)]"
  syntax:
    content: public System.Web.Configuration.CacheSection Cache { get; }
    return:
      type: System.Web.Configuration.CacheSection
      description: "Den <xref href=&quot;System.Web.Configuration.CacheSection&quot;> </xref> objekt."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.Cache*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  id: OutputCache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: OutputCache
  nameWithType: SystemWebCachingSectionGroup.OutputCache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar den <xref uid=&quot;langword_csharp_outputCache&quot; name=&quot;outputCache&quot; href=&quot;&quot;> </xref> avsnittet som ingår i konfigurationen."
  remarks: "Den <xref:System.Web.Configuration.OutputCacheSection>objektet refererar till den `outputCache` avsnittet i konfigurationsfilen.</xref:System.Web.Configuration.OutputCacheSection>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.OutputCacheSection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#3](~/add/codesnippet/csharp/p-system.web.configurati_104_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#3](~/add/codesnippet/visualbasic/p-system.web.configurati_104_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheSection OutputCache { get; }
    return:
      type: System.Web.Configuration.OutputCacheSection
      description: "Den <xref href=&quot;System.Web.Configuration.OutputCacheSection&quot;> </xref> objekt."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  id: OutputCacheSettings
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: OutputCacheSettings
  nameWithType: SystemWebCachingSectionGroup.OutputCacheSettings
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar den <xref uid=&quot;langword_csharp_outputCacheSettings&quot; name=&quot;outputCacheSettings&quot; href=&quot;&quot;> </xref> avsnittet som ingår i konfigurationen."
  remarks: "Den <xref:System.Web.Configuration.OutputCacheSettingsSection>objektet refererar till den `outputCacheSettings` avsnittet i konfigurationsfilen.</xref:System.Web.Configuration.OutputCacheSettingsSection>       Inställningar för cachelagring av utdata för att aktivera eller inaktivera diskbaserad beständiga utdatacache, definiera platsen för att spara data som ska cachelagras och ange den maximala storleken på cacheminnet per program.       ASP.NET kan du cache-lagra flera versioner av sidan svar deklarativt genom att använda attribut i direktivet och genom programmering med egenskaper och metoder i <xref:System.Web.HttpCachePolicy>klassen.</xref:System.Web.HttpCachePolicy>       Du kan uppnå samma resultat genom att konfigurera de program som använder den <xref:System.Web.Configuration.OutputCacheSettingsSection>eller <xref:System.Web.Configuration.OutputCacheProfile>typ.</xref:System.Web.Configuration.OutputCacheProfile> </xref:System.Web.Configuration.OutputCacheSettingsSection>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.OutputCacheSettingsSection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#4](~/add/codesnippet/csharp/p-system.web.configurati_173_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#4](~/add/codesnippet/visualbasic/p-system.web.configurati_173_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheSettingsSection OutputCacheSettings { get; }
    return:
      type: System.Web.Configuration.OutputCacheSettingsSection
      description: "Den <xref href=&quot;System.Web.Configuration.OutputCacheSettingsSection&quot;> </xref> objekt."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  id: SqlCacheDependency
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: SqlCacheDependency
  nameWithType: SystemWebCachingSectionGroup.SqlCacheDependency
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Hämtar den <xref uid=&quot;langword_csharp_sqlCacheDependency&quot; name=&quot;sqlCacheDependency&quot; href=&quot;&quot;> </xref> avsnittet som ingår i konfigurationen."
  remarks: "Den <xref:System.Web.Configuration.SqlCacheDependencySection>objektet refererar till den `sqlCacheDependency` avsnittet i konfigurationsfilen.</xref:System.Web.Configuration.SqlCacheDependencySection>       SQL-cacheberoende upprättar ett förhållande mellan ett objekt som lagras i cachen för ett ASP.NET-program och en specifik SQL Server-databastabell. En instans av den <xref:System.Web.Caching.SqlCacheDependency>klassen måste övervaka tabellen så att när tabellen ändras objektet tas automatiskt bort från cachen.</xref:System.Web.Caching.SqlCacheDependency>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.SqlCacheDependencySection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#5](~/add/codesnippet/csharp/p-system.web.configurati_8_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#5](~/add/codesnippet/visualbasic/p-system.web.configurati_8_1.vb)]"
  syntax:
    content: public System.Web.Configuration.SqlCacheDependencySection SqlCacheDependency { get; }
    return:
      type: System.Web.Configuration.SqlCacheDependencySection
      description: "Den <xref href=&quot;System.Web.Configuration.SqlCacheDependencySection&quot;> </xref> objekt."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SystemWebCachingSectionGroup()
  nameWithType: SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: Cache
  nameWithType: SystemWebCachingSectionGroup.Cache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
- uid: System.Web.Configuration.CacheSection
  parent: System.Web.Configuration
  isExternal: false
  name: CacheSection
  nameWithType: CacheSection
  fullName: System.Web.Configuration.CacheSection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCache
  nameWithType: SystemWebCachingSectionGroup.OutputCache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
- uid: System.Web.Configuration.OutputCacheSection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheSection
  nameWithType: OutputCacheSection
  fullName: System.Web.Configuration.OutputCacheSection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCacheSettings
  nameWithType: SystemWebCachingSectionGroup.OutputCacheSettings
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
- uid: System.Web.Configuration.OutputCacheSettingsSection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection
  fullName: System.Web.Configuration.OutputCacheSettingsSection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SqlCacheDependency
  nameWithType: SystemWebCachingSectionGroup.SqlCacheDependency
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
- uid: System.Web.Configuration.SqlCacheDependencySection
  parent: System.Web.Configuration
  isExternal: false
  name: SqlCacheDependencySection
  nameWithType: SqlCacheDependencySection
  fullName: System.Web.Configuration.SqlCacheDependencySection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SystemWebCachingSectionGroup
  nameWithType: SystemWebCachingSectionGroup.SystemWebCachingSectionGroup
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.Cache*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: Cache
  nameWithType: SystemWebCachingSectionGroup.Cache
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCache
  nameWithType: SystemWebCachingSectionGroup.OutputCache
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCacheSettings
  nameWithType: SystemWebCachingSectionGroup.OutputCacheSettings
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SqlCacheDependency
  nameWithType: SystemWebCachingSectionGroup.SqlCacheDependency
