### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory
  id: ApplicationServicesHostFactory
  children:
  - System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor
  - System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(System.Type,System.Uri[])
  langs:
  - csharp
  name: ApplicationServicesHostFactory
  nameWithType: ApplicationServicesHostFactory
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory
  type: Class
  summary: "Innehåller fabriksklass för en som skapar instanser av autentiseringstjänst, rolltjänsten och profiltjänsten i värdbaserade miljöer."
  remarks: "Den här klassen är ett sätt att skapa instanser av den <xref:System.Web.ApplicationServices.AuthenticationService>, <xref:System.Web.ApplicationServices.ProfileService>, och <xref:System.Web.ApplicationServices.RoleService>klasser.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.ProfileService> </xref:System.Web.ApplicationServices.AuthenticationService>       Om du vill använda den här klassen, skapa en WCF-tjänst (.svc)-fil och ange ApplicationServicesHostFactory i den `ServiceHosting` attribut för den `@ ServiceHost` direktiv."
  example:
  - "The following example shows how to specify ApplicationServicesHostFactory in the `@ ServiceHost` directive of a .svc file to configure the authentication service.  \n  \n```c#  \n<%@ ServiceHost   \n  Language=\"C#\"   \n  Service=\"System.Web.ApplicationServices.AuthenticationService\"   \n  Factory=\"System.Web.ApplicationServices.ApplicationServicesHostFactory\"   \n%>  \n  \n```  \n  \n```vb  \n<%@ ServiceHost   \n  Language=\"VB\"   \n  Service=\"System.Web.ApplicationServices.AuthenticationService\"   \n  Factory=\"System.Web.ApplicationServices.ApplicationServicesHostFactory\"   \n%>  \n```"
  syntax:
    content: 'public class ApplicationServicesHostFactory : System.ServiceModel.Activation.ServiceHostFactory'
  inheritance:
  - System.ServiceModel.Activation.ServiceHostFactory
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor
  id: '#ctor'
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  langs:
  - csharp
  name: ApplicationServicesHostFactory()
  nameWithType: ApplicationServicesHostFactory.ApplicationServicesHostFactory()
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.ApplicationServicesHostFactory()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Initierar en ny instans av den <xref href=&quot;System.Web.ApplicationServices.ApplicationServicesHostFactory&quot;> </xref> klass."
  syntax:
    content: public ApplicationServicesHostFactory ();
    parameters: []
  overload: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(System.Type,System.Uri[])
  id: CreateServiceHost(System.Type,System.Uri[])
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  langs:
  - csharp
  name: CreateServiceHost(Type,Uri[])
  nameWithType: ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Skapar en instans av tjänstklassen som har basadressen eller adresser."
  remarks: "Vanligtvis den här metoden anropas automatiskt av [!INCLUDE[vsindigo](~/add/includes/vsindigo-md.md)] som en del av tjänsten aktivering och du inte behöver anropa metoden manuellt."
  syntax:
    content: protected override System.ServiceModel.ServiceHost CreateServiceHost (Type serviceType, Uri[] baseAddresses);
    parameters:
    - id: serviceType
      type: System.Type
      description: "Typ av tjänstvärden för att skapa."
    - id: baseAddresses
      type: System.Uri[]
      description: "En matris med basadresser för tjänsten."
    return:
      type: System.ServiceModel.ServiceHost
      description: "En <xref href=&quot;System.ServiceModel.ServiceHost&quot;> </xref> instansen för typ av tjänst som har basadressen eller adresser."
  overload: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activation.ServiceHostFactory
  isExternal: false
  name: System.ServiceModel.Activation.ServiceHostFactory
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: ApplicationServicesHostFactory()
  nameWithType: ApplicationServicesHostFactory.ApplicationServicesHostFactory()
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.ApplicationServicesHostFactory()
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(System.Type,System.Uri[])
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: CreateServiceHost(Type,Uri[])
  nameWithType: ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
- uid: System.ServiceModel.ServiceHost
  parent: System.ServiceModel
  isExternal: false
  name: ServiceHost
  nameWithType: ServiceHost
  fullName: System.ServiceModel.ServiceHost
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Uri[]
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri[]
  spec.csharp:
  - uid: System.Uri
    name: Uri
    nameWithType: Uri
    fullName: Uri[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor*
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: ApplicationServicesHostFactory
  nameWithType: ApplicationServicesHostFactory.ApplicationServicesHostFactory
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost*
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: CreateServiceHost
  nameWithType: ApplicationServicesHostFactory.CreateServiceHost
