### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  id: OutputMessage
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.GetArguments
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Name
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Text
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Type
  langs:
  - csharp
  name: OutputMessage
  nameWithType: OutputMessage
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  type: Class
  summary: "Den här klassen representerar en fel, varning eller information utgående meddelande för manifestet generator."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class OutputMessage
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.GetArguments
  id: GetArguments
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  langs:
  - csharp
  name: GetArguments()
  nameWithType: OutputMessage.GetArguments()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.GetArguments()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Returnerar en strängmatris argumenten för meddelandet."
  syntax:
    content: public string[] GetArguments ();
    parameters: []
    return:
      type: System.String[]
      description: "Returnerar en strängmatris argumenten för meddelandet."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.GetArguments*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Name
  id: Name
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  langs:
  - csharp
  name: Name
  nameWithType: OutputMessage.Name
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Name
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Returnerar en identifierare för meddelandet."
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "En sträng som anger vilket meddelande."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Name*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Text
  id: Text
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  langs:
  - csharp
  name: Text
  nameWithType: OutputMessage.Text
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Text
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Returnerar texten i meddelandet."
  syntax:
    content: public string Text { get; }
    return:
      type: System.String
      description: "En sträng som anger meddelandetexten."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Text*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Type
  id: Type
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  langs:
  - csharp
  name: Type
  nameWithType: OutputMessage.Type
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Type
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Returnerar om meddelandet är ett fel, varning eller ett informationsmeddelande."
  remarks: "Värdena kan vara <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType>, <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType>, eller <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType>.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType> </xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType> </xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType> Mer information finns i <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType>.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType>"
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType Type { get; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
      description: "En <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType&quot;> </xref> objekt som indikerar meddelandetypen."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.GetArguments
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  isExternal: false
  name: GetArguments()
  nameWithType: OutputMessage.GetArguments()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.GetArguments()
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Name
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  isExternal: false
  name: Name
  nameWithType: OutputMessage.Name
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Text
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  isExternal: false
  name: Text
  nameWithType: OutputMessage.Text
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Text
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Type
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  isExternal: false
  name: Type
  nameWithType: OutputMessage.Type
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Type
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: OutputMessageType
  nameWithType: OutputMessageType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.GetArguments*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  isExternal: false
  name: GetArguments
  nameWithType: OutputMessage.GetArguments
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Name*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  isExternal: false
  name: Name
  nameWithType: OutputMessage.Name
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Text*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  isExternal: false
  name: Text
  nameWithType: OutputMessage.Text
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage.Type*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  isExternal: false
  name: Type
  nameWithType: OutputMessage.Type
